### ISSUE TITLE
how to deal with "net::ERR_CERT_AUTHORITY_INVALID" with wrong certificate ?

### ISSUE THREAD

**Issue by bi-kai** [browserless/chrome#1004]
target page with wrong or without certificate, chrome show page "net::ERR_CERT_AUTHORITY_INVALID", how to ignore this?
I have used `ignoreHTTPSErrors`, like this:
```
browser = await puppeteer.connect({
          browserWSEndpoint: `ws://${gConfig.chromeInstance}`,
          ignoreHTTPSErrors: true
        })
```
but it's not work.

**Comment by bi-kai** [comment]
https://github.com/puppeteer/puppeteer/issues/1137
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions
https://github.com/puppeteer/puppeteer/issues/1159
https://bugs.chromium.org/p/chromium/issues/detail?id=721739

**Comment by bi-kai** [comment]
solved by adding `-e "DEFAULT_IGNORE_HTTPS_ERRORS=true"` to docker start param.

**Comment by mik3fly** [comment]
i have the isse even if i add ""DEFAULT_IGNORE_HTTPS_ERRORS=true" in my docker-compose file.

**Comment by StayPirate** [comment]
Same here, I do have `DEFAULT_IGNORE_HTTPS_ERRORS=true` set and I still get `ERR_CERT_AUTHORITY_INVALID`.

According to https://github.com/browserless/browserless/issues/2485#issuecomment-1634324702 @AndyMathys mentioned that **SSL Protocol Errors** are not treated by Chromium via `DEFAULT_IGNORE_HTTPS_ERRORS`. But, for what I see `ERR_CERT_AUTHORITY_INVALID` should not be part of **SSL Protocol Errors**.

Any idea how to fix this?

**Comment by StayPirate** [comment]
This can be reproduced by pointing to https://untrusted-root.badssl.com

**Comment by StayPirate** [comment]
@bi-kai do you mind to re-open this issue?

**Comment by StayPirate** [comment]
FTR: I managed to fix it in [changedetection](https://github.com/dgtlmoon/changedetection.io) by changing `PLAYWRIGHT_DRIVER_URL` from `ws://172.16.10.8:3000/?stealth=1&--disable-web-security=true` to `ws://172.16.10.8:3000/?stealth=1&--disable-web-security=true&--ignore-certificate-errors`
