### ISSUE TITLE
Include .mp4 video support

### ISSUE THREAD

**Issue by MarianAlexandruAlecu** [browserless/chrome#1005]
The issue with current state of browserless is that it can play only `.webm`.

It would be nice to support at least .mp4 video. Checking [this thread](https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13515) it looks like a custom build of chromium is needed.

**Comment by joelgriffith** [comment]
Have you tried a chrome stable tag? `browserless/chrome:1-chrome-stable`

**Comment by joelgriffith** [comment]
Closing due to stable having this alrwady

**Comment by MarianAlexandruAlecu** [comment]
Hey,

Yeah, it worked! But what's the explanation? I was using `:latest` - is it a bug in the latest?
