### ISSUE TITLE
Chrome crashes when streaming video

### ISSUE THREAD

**Issue by MarianAlexandruAlecu** [browserless/chrome#1057]
**Describe the bug**
Chrome crashes when streaming video for more than ~10 minutes.

**To Reproduce**
Run this code in 4 concurrent sessions:
```
module.exports = async ({ page }) => {
  await page.goto('https://webrtc.github.io/samples/src/content/capture/video-video/', { waitUntil: 'networkidle2' });
  
  await page.click('#leftVideo');
};
```
Our use case is very similar to the above - we are taking a video from web and streaming it to native camera. It turns out that stream from one source to another is very CPU expensive! Which **results in page running for ~10 minutes before crashing.**
We run maximum 4 concurrent sessions on a 4 CPU 8 gb ram in Amazon ECS Fargate.

**Expected behavior**
Page should not crash. In the worst case, the video should lag.

**Desktop (please complete the following information):**
 - 4 CPU 8 GB ram in Amazon ECS Fargate for 4 concurrent sessions
 - browserless/chrome:1-puppeteer-2.1.1 Docker image

**Comment by joelgriffith** [comment]
Our overhead is fairly minimal at this point — did you have something in particular in mind?

**Comment by MarianAlexandruAlecu** [comment]
So you are saying this is a Chrome issue and not something particular with browserless?

**Comment by joelgriffith** [comment]
Yup, it's extremely rare that we'd have a huge impact on CPU and Memory -- it's almost always Chrome's fault :/
