### ISSUE TITLE
Windows docker image?

### ISSUE THREAD

**Issue by rgl** [browserless/chrome#1087]
**Is your feature request related to a problem? Please describe.**

I would like to be able to run browserless in a Windows container.

**Describe the solution you'd like**

A Windows container image.

**Describe alternatives you've considered**

Currently I'm using an ad-hoc image at https://github.com/rgl/HelloSeleniumWebDriver/tree/master/chrome. 

**Additional context**

This will only work with the windows base image (13.3GB); it will not work with the other windows base images.

**Comment by joelgriffith** [comment]
Due to the licensing issues, we can't use Windows as a base for our image. If you're currently running Windows, and want to use this docker image, it _should_ just work without any need from us. Please let me know if that's not the case.
