### ISSUE TITLE
/sessions result request to http://127.0.0.1:43593/json/list failed

### ISSUE THREAD

**Issue by zahlio** [browserless/chrome#1093]
**Describe the bug**
We are running ~100 sessions per browserless container, and when under load we are getting 400 errors when we try to access `GET /sessions`.

Additional questions:
- is there a better way of getting the `browserWSEndpoint` then using `GET /sessions`, we do this every time we create a new browser to get the `browserWSEndpoint` of the current browser to save in cache.

**To Reproduce**
1. Run ~100 of sessions and use `keepAlive` (we use 30mins)
2. `GET /sessions`
3. Results in `Error: Unexpected server response: 400` `request to http://127.0.0.1:43593/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:43593'`

**Expected behavior**
Returning the json as normal

**Comment by zahlio** [comment]
we are runinng this in docker using `browserless/chrome:1.41.0-puppeteer-5.4.1`

**Comment by zahlio** [comment]
I have added a fix for getting the `browserWSEndpoint` using `GET /sessions` when including `trackingId` as a GET query param.

https://github.com/zahlio/chrome/commit/31a2dc3e7863eb3cb413a12d8845a28541a015c3

**Comment by joelgriffith** [comment]
Should be addressed in https://github.com/browserless/chrome/pull/1208
