### ISSUE TITLE
start script stalls on "rm: remove write-protected regular file '/tmp/.X99-lock'?"

### ISSUE THREAD

**Issue by opicron** [browserless/chrome#1095]
**Describe the bug**
rm in start.sh does not forcefully remove file '/tmp/.X99-lock'.

**To Reproduce**
- Install browserless/chrome on Synlogy docker
- restart docker
- can not connect to docker through browser
- start.sh manually

**Expected behavior**
- Expected to see forceful removal of file '/tmp/.X99-lock'

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: DSM 6.2 (latest)
 - Browser: n/a

**Additional context**
Fixed by adding -f to rm command in ./start.sh

**Comment by opicron** [comment]
Sorry to have contaminated your pull request: https://github.com/browserless/chrome/pull/674.

**Comment by joelgriffith** [comment]
Thanks for the PR! Merged :)
