### ISSUE TITLE
No docker build for USE_CHROME_STABLE=true with node 14?

### ISSUE THREAD

**Issue by amotzte** [browserless/chrome#1097]
Hi,
Looking in dockerhub. I see the latest chromium build with node 14 was generated. But can't find the chrome version with 
```USE_CHROME_STABLE=true```. The latest of that is with node 13.

Am I missing something ?

Thanks 😄

**Comment by joelgriffith** [comment]
Yup, will be released tomorrow AM, just need time to let it bake since it's a big change :)
