### ISSUE TITLE
Node 14 Docker image

### ISSUE THREAD

**Issue by Kikobeats** [browserless/chrome#1100]
Hello,

<img width="1284" alt="Screen Shot 2020-11-16 at 12 20 00" src="https://user-images.githubusercontent.com/2096101/99246738-17d9da00-2806-11eb-9553-e19cbf95a64b.png">

Although Node 14 at Docker image-level was pushed days ago

https://github.com/browserless/chrome/commit/a78960fd956ec12540413d87dff3b2103338f16e

The docker image present on the registry is not reflecting the change

**Comment by joelgriffith** [comment]
I’ll push up the `latest` tag as well, however `1.6.0` has the change here https://hub.docker.com/layers/browserless/base/1.6.0/images/sha256-41854e78b00b99c99b89089f4d3be08d9323610c395e3cea96df09a0398ca755?context=explore, which is what the chrome image uses on `latest`

**Comment by Kikobeats** [comment]
@joelgriffith oh true, `1.6.0` uses `node14`.

The missing thing is `node14` on `latest` 🙂
