### ISSUE TITLE
Scrape API to return size, location and visibility of elements 

### ISSUE THREAD

**Issue by ankur-sharda** [browserless/chrome#1117]
It would be great to be able to get back the **size**, **location** and **visibility** of an element with the Scrape API.

Size = the length and width of the element
Location = the x, y coordinates of the top left corner of the element
Visibility = whether or not the element is visible when the page is loaded

These are available on the selenium API.
In Python I access them like this:

for x in elems:
    print(x.location)
    print(x.size)
    print(x.is_displayed())

Which will display for each element something like this:
{'x': 366, 'y': 2863}
{'height': 50.0, 'width': 171.0500030517578}
True

Of course the actual size and location values will depend on the dimensions of the browser so I guess screen dimensions may also need to be provided, or a documented default used for all cases. 
In my case any default dimensions that approximate a desktop would work, but I imagine others may want to be able to specify dimensions.

**Comment by joelgriffith** [comment]
Visibility is covered via the `timeout` option (won't load if the elements never are in the DOM or timeout). The rest are added in https://github.com/browserless/chrome/pull/1210
