### ISSUE TITLE
Protocol error (Page.printToPDF): PrintToPDF is not implemented

### ISSUE THREAD

**Issue by cxs1427** [browserless/chrome#1131]
**Is the function of pdf still available?**

I used Postman to create a Post request to 
`http://192.168.99.100:3000/pdf`

 I followed the official example,
`  {
"url": "https://example.com/",
  "options": {
    "displayHeaderFooter": true,
    "printBackground": false,
    "format": "A0"
  }`

But it returns the following error:
`Protocol error (Page.printToPDF): PrintToPDF is not implemented`

**Environment:**
- Postman
- browserless/chrome:1.39.0-puppeteer-2.1.1

Looking forward to your reply, thanks.

**Comment by joelgriffith** [comment]
Are you running in headful or headless mode?
