### ISSUE TITLE
Issue: Opening active-session debugger hangs Puppeteer script

### ISSUE THREAD

**Issue by bland328** [browserless/chrome#1147]
### The problem
While successfully automating Browserless via a simple Pyppeteer _(Python-based Puppeteer port)_ script, every time I  open the active-session debugger and click the current session, the script hangs seemingly forever as soon as DevTools opens. DevTools shows the page I expect to see, but I can find no way to get the script to continue.

_Edit: I've narrowed things a tiny bit, observing that after opening the debugger, the script still successfully runs a few lines analyzing the DOM and finding various elements, then hangs on the first click of an element._

### What I've tried
Within DevTools, under Sources, I find:
- Script execution is not paused
- No Breakpoints, XHR/fetch Breakpoints or DOM Breakpoints exist
- Deactivate Breakpoints is off by default; turning it on makes no difference
- Pause on Exceptions is off by default

I've also tried the Restore Defaults and Reload button in Preferences.

### My configuration
Everything is being run locally on a simple single LAN.

The host running the Browserless container is also running a container providing Nginx reverse proxy services, so after initially not being able to access the active-session debugger at all due to immediate "Websocket disconnected" failures, I added appropriate PROXY_HOST and PROXY_PORT environment variables for the Browserless container per [this issue](https://github.com/browserless/chrome/issues/591), which fixed things right up. _(I freely admit, however, that I don't quite grasp why this was necessary for local access, and can't quite shake my suspicion that this is all related.)_

Hopefully, I'm just missing something obvious here. Can anyone point me in the right direction?

**Comment by joelgriffith** [comment]
What browser are you using for loading the debugger? Unfortunately this only work with Chrome for the time being. Otherwise, check the network calls and make sure the the WebSocket connection is working.

**Comment by bland328** [comment]
I'm using Chrome 86.0.4240.198 (Official Build) (x86_64) under macOS Catalina.

By "check the network calls," do you mean packet sniffing? Or something higher-level than that?

**Comment by bland328** [comment]
Ah--I just discovered something I should've seen before now:

Just after I open the live debugger, Console shows a series of `DevTools failed to load SourceMap: Could not load content for https://<various file names>.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE` failures.

**Comment by bland328** [comment]
Figured it out--I was pulling `browserless/chrome` without a tag, which means I was getting `:latest`, which means I was getting a non-stable Chrome release that was newer than the Chrome build I was using to access the live debugger, and apparently causing all the weirdness.

I'm now pulling `browserless/chrome:1.43-chrome-stable`, and everything is fine.

Expensive lesson learned!

**Comment by rtlong** [comment]
Just want to link to this issue noted in Puppeteer, possibly related https://github.com/puppeteer/puppeteer/issues/5730

**Comment by rtlong** [comment]
In my case switching to the current stable did _not_ resolve this. I still see this call just hang while the screencasting is enabled: 
```json
{"method":"Input.dispatchMouseEvent","params":{"x":502.359375,"y":1010.9609375,"type":"mousePressed","button":"left","clickCount":1,"modifiers":0},"id":1798}
```

(I realize this is a 2 year old issue but wanted to add some color in case others encounter this.)
