### ISSUE TITLE
Safari (Mac & iOS) - `SyntaxError: Invalid regular expression: invalid group specifier name`

### ISSUE THREAD

**Issue by mcnamee** [browserless/chrome#1156]
**Describe the bug**
When opening https://chrome.browserless.io and pressing run (the play button) in Safari on Mac and iOS, nothing happens (right pane remains blank/white). Viewing the Dev Tools Console reveals error/s:

- `SyntaxError: Invalid regular expression: invalid group specifier name`
- `Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name`

**To Reproduce**
1. Using Safari Go to [https://chrome.browserless.io ](https://chrome.browserless.io )
2. Click on the play/run button
4. See error in developer tools console

**Expected behavior**
The website and dev tools should open in the right pane/frame.

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser: Safari
 - Version: 14.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.2
 - Browser: Safari, Edge, Brave

**Comment by joelgriffith** [comment]
This is an unfortunate issue in how Chrome's devtools works, and is ultimately only supported on Chromium-based browsers. I hate that that is the case, but here we are...
