### ISSUE TITLE
Now that Docker supports Apple's ARM M1 chip as does Chrome, is it possible for an ARM image of Browserless?

### ISSUE THREAD

**Issue by lonkle** [browserless/chrome#1161]
The subject says it all, I'm just curious if it's possible.

**Comment by joelgriffith** [comment]
Definitely possible, however docker (I think) needs to support Apple's ARM chip before browserless will work. Once done, I imagine it'll work without issues.

**Comment by lonkle** [comment]
@joelgriffith Docker does need to support Apple's ARM chip and their latest technical preview (v7 now) does support the M1. All containers work, as does browserless EXCEPT there's no live debugging in Chrome anymore (despite the debug page being served properly). I tried using Intel Chrome and ARM Chrome when using your Intel Browserless container, but both methods crash the chrome session as does passing a command to `/function` via cURL.

My only assumption as to why this is is because of the chrome process being translated from x86 to ARM on the fly. And since Chrome has ARM support, I imagined adding an ARM docker file whom's only difference is to download the ARM version of Chrome may actually work **immediately** on Docker Technical Preview v7 (it's public).

**Comment by joelgriffith** [comment]
Yup, that's a fair point. Adding ARM support might be tricky since we have a lot of dependencies on Ubuntu packages that might be hard to find in ARM-land. It's definitely doable, just would be a fair bit of work

**Comment by lonkle** [comment]
Oh, for as complex a project as this, I'm quite certain it would be only a priority if ARM becomes the predominant CPU architecture for servers and consumers alike (which until the new MacBook, it was an Intel world). Just keep this on your mind for the future - I have there's going to be an ARMs race!

**Comment by kohenkatz** [comment]
ARM is rapidly becoming a big player in the server world, with Amazon's "Graviton" processors in the lead.

I am going to have a look at making this work on Graviton.

**Comment by lonkle** [comment]
@kohenkatz Absolutely! Post your findings and / or if you need help at all, I've been working hard on trying to get Browserless working on my M1 MacBook. No matter what I do, it can't read **anything** from Dev Tools. That seems to be the only disconnect left. That dev tools can't connect on M1 Macs, everything else works (this is under QEMU emulation btw which Docker officially employees to support M1 MacBooks).

**Comment by simneu** [comment]
hi @lonkle,

I've been trying to make browserless run correctly on a M1 macbook too to see if it would fit for our usage and our team but I am still struggling. We're also interested in running it later on AWS Graviton if that happens to work.

Could you explain how you managed to make everything except dev tools work please ? Did you rebuild a custom image ? Did anything special ? Would be very grateful to know how you achieved that.

Thanks !
