### ISSUE TITLE
Issue: Can't disable session timeout for single session

### ISSUE THREAD

**Issue by bland328** [browserless/chrome#1173]
### Problem
I'm generally successfully using pyppeteer (Python port of puppeteer) to automate a Browserless Docker container, but unable to figure out how to disable the session timer for just a single session.

### What I've tried
If I set the `$CONNECTION_TIMEOUT` environment variable to `-1`, [per this page](https://docs.browserless.io/docs/docker.html#connection-timeout), it works.

And if I set `$CONNECTION_TIMEOUT=10000` but then [override that timeout](https://docs.browserless.io/docs/chrome-flags.html#overriding-the-session-timer) with `ws://server:3000?timeout=20000`, that also appears to work.

However, using -1 (`ws://server:3000?timeout=-1`) doesn't disable the session timer. Zero doesn't disable it, either.

I'm not sure if I'm reporting a bug, making a feature request, or simply doing something wrong.

Is there a way to disable the session timer for a single session?

**Comment by joelgriffith** [comment]
Seems like a bug, and you’re in the right place. Will take a look!

**Comment by joelgriffith** [comment]
Fix is in the npm package we use, but depends on them releasing. Follow https://github.com/jessetane/queue/issues/76 for more updates!
