### ISSUE TITLE
Adding Google Font Support

### ISSUE THREAD

**Issue by mmoonport** [browserless/chrome#1185]
**Is your feature request related to a problem? Please describe.**
We build a lot of static html comes from a rich text editor in our ios app. we use google fonts as our font choices and having to load these in the browser page adds unwanted time.

**Describe the solution you'd like**
Add google fonts to the base installed fonts. 

**Describe alternatives you've considered**
The way we are currently implementing it seems to be the only alternative. Use JS to load the fonts with FontLoader.

**Additional context**
https://gist.github.com/keeferrourke/d29bf364bd292c78cf774a5c37a791db#file-install-google-fonts-sh
Here is a simple Gist to get this into the font library

**Comment by joelgriffith** [comment]
We've got quite a bit of fonts available, is there a particular one missing you think is necessary? Fonts add quite a bit of weight to the image, and you can definitely install more atop of your own image (instructions here: https://docs.browserless.io/docs/extending-docker.html#docsNav)

**Comment by mmoonport** [comment]
We are a greeting card company called Felt. we have a mobile app that lets people create and mail greeting cards with a rich text editor that you can use any google fonts you wish. So no one particular font. We are currently on the usage based plan. We dont have a commercial liscense as of yet. I fully understand not adding the fonts as the weight would be significant. Thanks!

**Comment by joelgriffith** [comment]
Thanks for the issue following up via email.
