### ISSUE TITLE
Logging is not off by default as stated in the docs

### ISSUE THREAD

**Issue by SupremeTechnopriest** [browserless/chrome#1187]
**Describe the bug**
The docs say logging is off by default in the docker container (https://docs.browserless.io/docs/docker.html#logging), but this is not true. See here:

https://github.com/browserless/chrome/blob/7ce560b790c50035a514c299b953eea14f7e97a4/src/config.ts#L15-L27

If you have to pay for log capturing this could run up a bill pretty fast. I worked around the issue by setting the env var to 
```
DEBUG=-*
```

Thanks for the awesome project.  Saved me a ton of headache. 🥂

**Comment by joelgriffith** [comment]
Thanks for that, we'll tweak the docs. Right now the default set is fairly slim (only what the system records itself), but good point!

**Comment by joelgriffith** [comment]
Added to docs, closing.
