### ISSUE TITLE
 Docker requirements

### ISSUE THREAD

**Issue by leobevi** [browserless/chrome#1191]
Hi! I am looking to use Browserless with docker with 50 or more concurrent sessions, I have already set the timeout to -1. Am I wanting to provision my equipment, on average what is the memory consumption per active session?

**Comment by joelgriffith** [comment]
You'll need a good amount for 50 concurrent. We suggest at _least_ 2CPU and 4GB RAM for 10 - 20, so at least double that and possibly more. Ideally, you'll likely want to use more machines versus fewer, as it's better to scale horizontally versus vertically. Good luck!
