### ISSUE TITLE
Can you upgrade chrome docker to latest LTS node.js?

### ISSUE THREAD

**Issue by amotzte** [browserless/chrome#1200]
Hi,
Thanks for your excellent work.

Currently latest image of chrome (browserless/chrome:1.43-chrome-stable) use node.js 14.15.0. would it be possible to upgrade to latest node.js (14.15.3+) ? The reason is that they fixed a major bug related to streaming (https://github.com/nodejs/node/pull/35941).  We are hitting this problem on streaming video via ssh2 on the container, with their latest version this is resolved.

Thanks.

**Comment by joelgriffith** [comment]
`latest` will soon have the update! Going to close out for now
