### ISSUE TITLE
"connect ECONNREFUSED" when using browserless/chome docker image on AWS Lambda

### ISSUE THREAD

**Issue by OwaisSiddiqui** [browserless/chrome#1227]
**Describe the bug**
I am new to both AWS and Docker. I wanted to deploy my data extraction script (which uses a running local docker instance) to AWS Lambda for performance reasons. I have deployed the browserless docker image on AWS Lambda using this article: https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/. I have created an AWS ECR with the browserless/chrome docker image loaded and then created a browserless-chrome AWS Lambda function with the container as the ECR image. Afterwards, I created an HTTP API Gateway for it and it gave me a API endpoint URL. I tried to use this URL (by replacing `https` with `ws`) for the `puppeteer.connect` browserWSEndpoint but it is giving me a error:

```
****** Error:  ErrorEvent {
  target: WebSocket { ...
  type: 'error',
  message: 'connect ECONNREFUSED...'
```

**To Reproduce**
1. Follow this article: https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/ to deploy browserless/chrome to AWS Lambda and create a HTTP API Gateway
2. Use the API URL with `ws` instead of `https` for the `puppeteer.connect` browserWSEndpoint.
3. Run script locally

**Expected behavior**
Connect to the AWS Lambda docker image and run like if I had run docker locally.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur (11.1)
 - Browser: Chrome
 - Version: Puppeteer Version

**Comment by joelgriffith** [comment]
Hrm, does AWS container image's support WebSockets? AFAICT most other providers don't...

**Comment by OwaisSiddiqui** [comment]
Oh yes. I found that you can create a WebSocket API for Lambda with the AWS API Gateway service. However, I am not sure how I could configure it for this e.g. what would be the "Route selection expression"?

**Comment by joelgriffith** [comment]
Unfortunately I couldn't help you much there as I'm not an AWS expert. I'd imagine some kind of wild-card expression to route it to your container is ideal?

**Comment by OwaisSiddiqui** [comment]
Okay. It says that it is "A route selection expression tells API Gateway which route to call when a client sends a message". I am still not sure, right now I went with the default "$request.body.action" and see if it will work.

One question if you don't mind is that how does Browserless serve its docker on the cloud? Is it with another cloud service like Azure or something else?

**Comment by joelgriffith** [comment]
No problem: we’re hosted on DigitalOcean given it’s flexibility on web sockets and other things. Made it pretty easy when we were getting started

**Comment by OwaisSiddiqui** [comment]
So I set the defaults of the AWS WebSocket API and then deployed the API to obtain the WebSocket `wss` URL. When I sent a request and try to connect to the WebSocket using `wscat` I get a 502 error. I looked into the logs for the Lambda browserless function container and found that I get this error: `IMAGE	Launch error: Couldn't find valid bootstrap(s): [./start.sh]	Entrypoint: []	Cmd: [./start.sh]	WorkingDir: [/usr/src/app]` and sometimes `Error: Couldn't find valid bootstrap(s): [./start.sh] Runtime.InvalidEntrypoint`. Do you know what could be the problem by any chance @joelgriffith?

**Comment by joelgriffith** [comment]
Sadly no. That shell script is just a startup/process management script. Might be a permissions issue or nonsupported file?

**Comment by OwaisSiddiqui** [comment]
I looked more into the issue and forgot to read that the docker images requires to follow the Lambda Runtime API and other requirements to run on Lambda, see: https://docs.aws.amazon.com/lambda/latest/dg/images-create.html. It is possible in the future for browserless to implement a version of its docker image for AWS Lambda?

For now, I would have to use a service like AWS Fargate to run the docker image on AWS.
