### ISSUE TITLE
question: Add routes to browserless from browserlessServer instance

### ISSUE THREAD

**Issue by panpann** [browserless/chrome#1237]
Hello,

I'm creating an app that creates custom routes on browserless API.

What it does is to receive arguments, compile a script (VMScript from vm2) and
give them to args `code` and `context` of `puppeteerProvider.runHTTP`.

Currently I am using the **externalRoutes** hook by adding my routes in the
external/ folder at the root of browserless project. This is simple using
your dockerfile or by forking the project but I find it more cumbersome when installing
the browserless-chrome package because the
only way to dev and test my app is to start browserless with docker
or to copy my files in the `node_modules/browserless-chrome` folder, if I understood correctly.

What I would like to do is to be able to add routes through the `browserlessServer`
class so that I can instantiate my code and the browserless server as I want.

I was thinking of something like:

```js
const { browserless } = require("browserless-chrome");
const { router } = require("./myrouter.js");

browserless.app.use(router)
// or by a method browserless.addRoute(router)
browserless.startServer()
```

I've looked at the `BrowserlessServer` code and found that the express app is
created in the promise created by `startServer`, so I can't get it before
the server starts to listen (and block the whole code).

I'm not an expert of JS and browserless, maybe I've missed something in your code or a way to do that ? 

If not, would it be possible to expose, somehow, the express `app` ?
(by a method, public attribute like in my example, an other way ?)

I've also tried to install `browserless-chrome` as a package, but I couldn't make it work.

```bash
mkdir /tmp/mytest && cd /tmp/mytest
npm i browserless-chrome
echo "const browserless = require('browserless-chrome');" > main.js
node main.js
```

stacktrace:

```
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module './browserless'
Require stack:
- /tmp/mytest/node_modules/browserless-chrome/build/index.js
- /tmp/mytest/main.js
```

I've looked into my node_modules/browserless-chrome and I can only see the file index.js
but no other compiled files. Did I do something wrong ?

**Comment by joelgriffith** [comment]
Ouch! Our package file isn’t letting built code get published in NPM. It’s not our recommended way of extending the image, but I’ll publish a new version and fix shortly

**Comment by joelgriffith** [comment]
Release in `+ browserless-chrome@1.44.0`

**Comment by panpann** [comment]
thx for your quick answer and PR !

About exposing the express app in `browserlessServer`,
is it something you are agree to or do you see a better way to achieve what I want ?

**Comment by panpann** [comment]
@joelgriffith ping for my question above
