### ISSUE TITLE
Read timeout issue while using browserless/chrome docker image

### ISSUE THREAD

**Issue by ShariqTyagi** [browserless/chrome#1246]
Hi,

We are getting intermittent read timeout issues while we use browserless/chrome docker image. 
By using browserless/chrome:1.43-chrome-stable version , the timeout issue is resolved but we would love to if this issue will be addressed in any future release.

Regards,
Shariq

**Comment by joelgriffith** [comment]
Aside from the read timeout, there isn't much to go off of here. If you can, please re-open with more details other than just "We are getting intermittent read timeout issues". The issue template is there to provide us with what we need so we can find and investigate these problems.
