### ISSUE TITLE
deviceScaleFactor for PDF on browserless.io

### ISSUE THREAD

**Issue by adrienpoly** [browserless/chrome#1300]
**Describe the bug**

I would like to use the viewport deviceScaleFactor option to generate a PDF as describe in this PR https://github.com/browserless/chrome/pull/434.
I am using the `/pdf`API with browserless.io

**To Reproduce**
```json
{
  "url": "https://example.com/",
  "options": {
    "viewport": {
        "deviceScaleFactor": 2
    }
  }
}
```
**Expected behavior**

The API call should return a PDF

**Actual behavior**

```json
[
    {
        "message": "\"options.viewport\" is not allowed",
        "path": [
            "options",
            "viewport"
        ],
        "type": "object.unknown",
        "context": {
            "child": "viewport",
            "label": "options.viewport",
            "value": {
                "deviceScaleFactor": 2
            },
            "key": "viewport"
        }
    }
]
```

**Screenshots**
![Screen Shot 2021-02-19 at 9 18 54 AM](https://user-images.githubusercontent.com/7847244/108477442-80b47080-7293-11eb-8d1f-32ffeec45d87.jpg)

**Comment by joelgriffith** [comment]
Thanks! Will add this soon

**Comment by joelgriffith** [comment]
Looks like we've already got it supported. Here's an example cURL command:


```sh
curl --request POST \
  --url https://chrome.browserless.io/pdf \
  --header 'Content-Type: application/json' \
  --data '{
  "url": "https://example.com/",
	"viewport": {
		"deviceScaleFactor": 5,
		"height": 1080,
		"width": 1920
	}
}'
```
