### ISSUE TITLE
Playwright: Browser needs to be launched with the global proxy

### ISSUE THREAD

**Issue by asveloper** [browserless/chrome#1318]
**Describe the bug**
I am using playwright and want to setup global proxy for the browser but it always gives an error when trying to create a context

**browser.newContext: Browser needs to be launched with the global proxy. If all contexts override the proxy, global proxy will be never used and can be any string, for example "launch({ proxy: { server: 'per-context' } })**

 await chromium.connect({ wsEndpoint: `${process.env.PLAYWRIGHT_SERVICE_URL}/playwright?token=${process.env.PLAYWRIGHT_TOKEN}&--proxy-server=${proxy.host}:${proxy.port}` });

i did tried going through the docs of browserless but didn't able to fix this issue, any help will be great, thank you

**Comment by joelgriffith** [comment]
Thanks for the report, this does sound like something on our end. I'll take a look into what it'd require to support this!

**Comment by asveloper** [comment]
Thank you @joelgriffith looking forward for it

**Comment by asveloper** [comment]
@joelgriffith any update on this?

**Comment by joelgriffith** [comment]
Sorry on the delay: this is a bit more involved due to how params are passed in playwright. Taking the time it needs to get it right

**Comment by gajus** [comment]
Hey, This is something we'd benefit a lot from too. Any updates on this?

**Comment by joelgriffith** [comment]
Yup, will prioritize and get something out this week for testing.

**Comment by joelgriffith** [comment]
As gnarly as it sounds, looks like doing some kind of stringification of the object:

```
{
  server: 'http://myproxy.com:3128',
  user: 'usr',
}
```

Would be like:

```ws://my-url.com?playwrightProxy=%7B%22server%22%3A%22http%3A%2F%2Fmyproxy.com%3A3128%22%2C%22user%22%3A%22usr%22%7D```

Code would look like:

```
encodeURIComponent(JSON.stringify({
  server: 'http://myproxy.com:3128',
  user: 'usr',
}))
```

**Comment by joelgriffith** [comment]
https://github.com/browserless/chrome/pull/1433

**Comment by joelgriffith** [comment]
Released in our production branches, closing!

**Comment by gortizloza** [comment]
What was the solution, I am still having the same problem with chromium, is there a workaround?

**Comment by towfik2564** [comment]
The original answer has been given [here](https://github.com/microsoft/playwright/issues/10008#issuecomment-959960274).

Chromium browser has this issue. Try using firefox or opera.
