### ISSUE TITLE
request interception in browserless 1.44 version failed for puppeteer 4.0.0

### ISSUE THREAD

**Issue by obh** [browserless/chrome#1329]
Migration from docker image 1.36-stable to 1.44 stable broke code for us. We were using puppeteer 4.0.0 with 1.36-stable. Ideally after this migration nothing should have broken as only waitFor is deprecated. However, our request interceptor broke after this change. 

Following is our code to intercept a request and convert it into post - 
```
async function postToTestPage(page, url, params) {
       await page.setRequestInterception(true);
       page.on('request', interceptedRequest => {
           // we don't want these things
           if (['image', 'stylesheet', 'font'].indexOf(interceptedRequest.resourceType()) !== -1) {
               interceptedRequest.abort()
               return
           }
           logger.info("Staring request to: %s", interceptedRequest.url())
           var data = {}
           if (interceptedRequest.url() === url) {
               data = {
                   'method' : 'POST',
                   'postData': qs.stringify(params),
                   headers: {
                       ...interceptedRequest.headers(),
                       "Content-Type": "application/x-www-form-urlencoded",
                   }
               };
           }
           interceptedRequest.continue(data);
       });
       // this is navigation timeout for the loading page. But since we could have redirects involved
       const response = await page.goto(url, pageGoToConf);
       return true
   }
```

As we migrated to 1.44, the request method changed to POST but the payload was empty. The fix included migrating puppeteer to 5.4.1 and everything worked fine from there on. 
Browserless runs on our k8 cluster and we connect our services to it through  await puppeteer.connect({browserWSEndpoint: "http://localhost:3001"})

**Comment by joelgriffith** [comment]
Did you notice the same issue when using just puppeteer? We didn't really change any behavior here, so I'm guessing that it's something to do either with Chrome or puppeteer.

**Comment by joelgriffith** [comment]
Going to chock this one up as an issue in the chromium revision and not necessarily an issue in browserless
