### ISSUE TITLE
apt-get clean in a distinct layer is pointless

### ISSUE THREAD

**Issue by athoune** [browserless/chrome#1338]
**Describe the bug**
The docker image is very large.

One common mistake is doing `apt-get update` in one layer, and `apt-get clean && /var/lib/apt/lists/*` in another layer.

You did it : 

In https://github.com/browserless/chrome/blob/master/base/Dockerfile#L87

With more `&&` you can handle all apt-stuff in one layer, and save image weight.

**Comment by joelgriffith** [comment]
Fixed in https://github.com/browserless/chrome/pull/1339
