### ISSUE TITLE
Make `browserless.token` a valid W3C Capability

### ISSUE THREAD

**Issue by osddeitf** [browserless/chrome#1343]
I'm just forward the issue from [browserless docs](https://github.com/browserless/docs/issues/1). I think it's more appropriate to make an issue here.

Summary: could not supply `browserless.token` to Webdriver.io because it's not a W3C-standards capability.

Proposed solution: deprecate `browserless.token` and instead use `browserless:token` for W3C conformance.

**Comment by joelgriffith** [comment]
Thanks for pointing this out. I'd love to have conformance to the standard, but this would potentially break a lot of our users that have code running.

I think we can support potentially both for now -- would that work?

**Comment by osddeitf** [comment]
Yes, that exactly what I meant. You should mark it as deprecated to be removed in the future major version.
And could you please fix that soon? I prefer Browserless for it simplicity.

**Comment by joelgriffith** [comment]
The kid for the PR!
