### ISSUE TITLE
How do I automatically fill in user names and passwords when our system uses iframes to nest login pages of different domains?

### ISSUE THREAD

**Issue by sasadaisy** [browserless/chrome#1363]
How do I automatically fill in user names and passwords when our system uses iframes to nest login pages of different domains?thanks

**Comment by joelgriffith** [comment]
Without knowing the details of the page it's hard to offer suggestions. Puppeteer does have a way to do this, and there's information online about it: https://stackoverflow.com/questions/46529201/puppeteer-how-to-fill-form-that-is-inside-an-iframe. I'd recommend using that API to do what you need. Once the iframe is "page-ified" then all of the puppeteer API is available (clicking/typing, etc).

Closing as this isn't an issue with browserless necessarily.
