### ISSUE TITLE
Tagged PDFs for accessibility

### ISSUE THREAD

**Issue by mortona42** [browserless/chrome#1376]
**Is your feature request related to a problem? Please describe.**
Some organizations are required to produce accessible PDFs for section 508 compliance. From what I understand so far, this means the document is "tagged" and contains some html for screen readers. 

**Describe the solution you'd like**
In this announcement from the Chromium team, they  have added support for tagged PDFs created in the browser:
https://blog.chromium.org/2020/07/using-chrome-to-generate-more.html

It may just need an api option to set the export-tagged-pdf browser flag.

**Describe alternatives you've considered**
Other PDF libraries, such as WKHTMLTOPDF, DOMPDF, TCPDF, MPDF do not seem to support this feature. Will be looking into the Reactor PDF docker container as well.

**Additional context**
There is a lot of info about how to create PDFs with acrobat pro, but there seems to be a big gap in the tech ecosystem for batch creating tagged documents from web content.

**Comment by joelgriffith** [comment]
Interesting. My guess is that the headless implementation of pdf doesn’t yet support this as we’re past the chrome version where this was introduced.

**Comment by joelgriffith** [comment]
Looks like `--export-tagged-pdf` might make it work?

**Comment by jamesonhill** [comment]
Anybody have success using the `--export-tagged-pdf` param? I'm still running into a lot of issues with Adobe's accessibility checker.
