### ISSUE TITLE
Restart browser stack automatically when number of requests have failed

### ISSUE THREAD

**Issue by Tsopic** [browserless/chrome#1390]
**Is your feature request related to a problem? Please describe.**

Is it possible to somehow trigger the relaunch automatically?

If in an hour there are 50 failed requests or 5 attempts to connect to the browser are unsuccessful?

I've been finding myself pretty often manually restarting this browser stack as it becomes unusable.

**Describe the solution you'd like**

Restart stack automatically when the threshold of failed requests is crossed. 
Restart stack automatically when n attempts to connect to the browser are unsuccessful?

**Describe alternatives you've considered**
Count the failures myself and trigger restart with API - but this sucks I don't want to have this logic mixed with my business logic.

**Context**

I'm running services that scheduled and it's hell to find them being down when my data is relaying on these.

**Comment by Tsopic** [comment]
Still have this issue, getting mails of concurrency threshold violation, which I use for manually reloading the worker right now.

**Comment by Tsopic** [comment]
@joelgriffith

**Comment by joelgriffith** [comment]
We're taking a closer look at this and seeing if we can utilize an external container (that simply monitors browserless), and automatically restart it since browserless can get into a state where it faults and can't auto-restart.
