### ISSUE TITLE
Improve health checks for better Kubernetes support

### ISSUE THREAD

**Issue by sagikazarmark** [browserless/chrome#1420]
**Is your feature request related to a problem? Please describe.**
I'd like to reopen the discussion started in #348, #99 and #101.

Kubernetes currently has two kinds of health checks (well, three, but two matters here):

- liveness checks to determine whether a process is still running, even if not healthy at the moment. This is used to kill containers that cannot recover or in an unknown state.
- readiness checks determine whether a container is able to answer to requests. A container can be temporarily unhealthy (ie overloaded) in which case Kubernetes won't direct any traffic to the container.

I'm trying to run the official images on Kubernetes and I'm struggling to find a good solution.

`EXIT_ON_HEALTH_FAILURE` somewhat replaces liveness checks (although Kubernetes won't know why the container exited, so it'll make debugging somewhat harder. Leaving the restart to Kubernetes would be slightly better).

But there is no good alternative to readiness checks.

**Describe the solution you'd like**
Add two new endpoints:

- `/health/alive` should respond with 5xx if the container should be killed, 200 otherwise
- `/health/ready` should respond with 5xx or 429 if the container can accept new requests, 200 otherwise

**Describe alternatives you've considered**
Kubernetes can execute commands as health checks, so I could technically poll the `/pressure` endpoint and grep for `"isAvailable":false`, but that's not a great solution IMHO.

We could, however, add a script or a tool to the official image that helps with that.

**Comment by joelgriffith** [comment]
OK, to get some consensus on this, I'm assuming these logical conditions for these routes:

`/health/alive` => responds with 200 on if CPU/Memory are underneath their required parameters set in the environment variables.

`/health/ready` => responds with a 200 only if a session can be ran immediately or queued. No CPU/Ram checks.

**Comment by sagikazarmark** [comment]
From a Kubernetes perspective (which is what made me open this issue), the application is alive if everything is running (ie. the browser didn't stop for whatever reason). CPU and memory limit enforcing can be done by Kubernetes itself. From a generic application perspective, CPU/memory checks can be part of that as well I guess.

The application is ready if it's able to serve requests, so I think your description is accurate.
