### ISSUE TITLE
Playwright: Session endpoint empty, pressure endpoint reporting queue and running browsers

### ISSUE THREAD

**Issue by regbo** [browserless/chrome#1423]
**Describe the bug**
I can't figure out how to reproduce this, but current and stable versions of browserless will get stuck with "running" sessions in the /pressure endpoint, and nothing in the /session endpoint. FWIW we are using the /playwright endpoint exclusively.

**To Reproduce**
Unsure, seems to happen after about an hour of use

**Expected behavior**
If no sessions are running the queue should be empty.

**Desktop (please complete the following information):**
 - OS: Docker image

**Additional context**
I can't figure out how to reproduce this, but current and stable versions of browserless will get stuck with "running" sessions in the /pressure endpoint, and nothing in the /session endpoint. Eventually requests start being added to the queue, and I can't find anything in the logs describing an error. Here are my two commands on the docker container:

```
curl localhost:3000/sessions?token=[REDACTED]
[]
```
```
curl localhost:3000/pressure?token=[REDACTED]
{"pressure":{"date":1618970237453,"reason":"","message":"","isAvailable":true,"queued":34,"recentlyRejected":0,"running":4,"maxConcurrent":4,"maxQueued":2147483647,"cpu":1,"memory":37}}
```
I can't figure out a way to reproduce this quickly, but it never happened with puppeteer. Is there perhaps some kind of disconnect between playwright closing and that not being passed onto puppeteer or the CDP? Is there some kind of test you'd recommend me trying?

**Comment by joelgriffith** [comment]
Hrm, having a hard time reproducing this. Anything you've found to help repro this?

**Comment by reggiepierce** [comment]
I haven't, I will close for now.

**Comment by joelgriffith** [comment]
Thanks @reggiepierce, closing for now
