### ISSUE TITLE
browserless chrome latest Docker image does not run

### ISSUE THREAD

**Issue by nasonfish** [browserless/chrome#1474]
**Describe the bug**

The current latest Docker image (also `1.46-chrome-stable`) does not run.

**To Reproduce**

Run the following docker command.
```
$ docker run docker.io/browserless/chrome
docker: Error response from daemon: unable to find user node: no matching entries in passwd file.
ERRO[0000] error waiting for container: context canceled
```

**Expected behavior**
This should not error, and instead spit out the configuration and begin browserless.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

It appears that you all are transitioning from `blessuser` to use the built-in user `node` from your `base` file.

However, it looks like there is a mismatch, and the old base file is being used with the newly updated `chrome` Dockerfile.

To fix this, it looks like you will need to re-publish the new version of your `browserless/base` file, and then upgrade `browserless/chrome` to reference that new file.

**Comment by joelgriffith** [comment]
Yup, just caught, working on a fix.

**Comment by joelgriffith** [comment]
Should be fixed now, closing.

**Comment by basav-raj** [comment]
The latest ARM64 image has this issue again
