### ISSUE TITLE
BrowserContext support for Playwright

### ISSUE THREAD

**Issue by liweixi100** [browserless/chrome#1508]
The APIs for creating a new browser context are different in Playwright and Puppeteer:
* Playwright:
`const context = await browser.newContext();`
* Puppeteer:
`const context = await browser.createIncognitoBrowserContext();`

The code in browserless appears to be using the Puppeteer version of the API only:
https://github.com/browserless/chrome/blob/e5a199c24e08bba4c654af877a58d1fde9f75a11/src/puppeteer-provider.ts#L662

Was that intentional?

**Comment by joelgriffith** [comment]
Yes, this was intentional, as we only supported puppeteer at the time from what I recall.

**Comment by liweixi100** [comment]
If we allow playwright browserContext with an `if-else` here, would there be any other concerns?

**Comment by joelgriffith** [comment]
I don't think so, at least not initially. There's some page setup and work that needs to be done that we might not be able to achieve with playwright `page`s in a REST call. Is there a reason you're looking to use playwright over puppeteer (just curious)?

**Comment by liweixi100** [comment]
A few reasons we wanted to explore Playwright:
* Automatic actionability checks against selected element
* Selector automatically pierces ShadowDom root
* Custom header support in `connect()`

Is the setup you mentioned related to https://github.com/microsoft/playwright/issues/4054#issuecomment-704512554 ? I was wondering if that could be simplified since https://playwright.dev/docs/api/class-browsertype/#browsertypeconnectovercdpparams is available.

**Comment by joelgriffith** [comment]
Going to close this since it's been a while. Feel free to re-open and we can revisit this!
