### ISSUE TITLE
/sessions API over nginx reverse proxy/LB

### ISSUE THREAD

**Issue by jitoot** [browserless/chrome#1548]
**Describe the bug**
Hello, does browserless support session information via the /sessions API over docker containers in an nginx load balanced cluster? I tried using the PROXY_URL setting but it doesn't seem to work.

**To Reproduce**
My nginx conf settings:
```
upstream cluster-test {
        least_conn;
        server localhost:3001;
        server localhost:3002;
}

server {
        listen 3000;
        location / {
                proxy_pass http://cluster-test;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```
I tested setting up browserless via the following commands:
```
docker run -e "PROXY_URL=http://localhost:3000" -p 3001:3000 --restart always -d --name node1 browserless/chrome:1.46-chrome-stable
docker run -e "PROXY_URL=http://localhost:3000" -p 3002:3000 --restart always -d --name node2 browserless/chrome:1.46-chrome-stable
```

When I open a browser session, calling http://localhost:3000/sessions returns empty data, but if I call it on localhost:3001 or localhost:3002 instead, it returns the session information.

I also saw that there is a newly introduced trackingId parameter, can this also be used in the /sessions API call to retrieve the specific session information? Thank you

**Comment by thegtagamer** [comment]
Facing a similar kind of issue, have deployed browserless containers in ECS in front of a load balancer when i run a single container it runs just fine but when I deploy 2 containers.

I Get this error from the selenium web driver
{ UnsupportedOperationError: get: Couldn't access session, did it timeout?

**Comment by joelgriffith** [comment]
Yeah, since this is a single "node" in a multi-node setup, your load-balancing layer needs to know how to properly route to the appropriate machines (sticky sessions). Unfortunately this really depends on _where_ you deploy your code, and that environment will need to support some kind of sticky session support.
