### ISSUE TITLE
WebDriver throws "Couldn't access session, did it timeout?" => When deployed on AWS ECS with multiple containers

### ISSUE THREAD

**Issue by thegtagamer** [browserless/chrome#1558]
Deploying browserless/chrome service on ECS with multiple counts under an NGINX sidecar throws When tried to access from selenium client end service
:

UnsupportedOperationError: get: Couldn't access session, did it timeout?

**Steps to reproduce:**
1. Deploy browserless chrome on ECS as a service
2. Set the desired count to 1 
3. Test using selenium client => It works when the desired container number is 1
4. Increase the container count
5. Try accessing the remote web driver again using client =>
   It throws : UnsupportedOperationError: get: Couldn't access session, did it timeout?

**Container specifications**
Memory assigned to the container: 1024
CPU: 1024

ENV Variables assigned to container def:

"environment": [{
                    "name": "CONNECTION_TIMEOUT",
                    "value": "-1"
                },
                {
                    "name": "MAX_CONCURRENT_SESSIONS",
                    "value": "10"
                },
                {
                     "name": "QUEUE_LENGTH",
                     "value": "10"
                },
                {
                    "name": "DEFAULT_IGNORE_HTTPS_ERRORS",
                    "value": "true"
                },
                 {
                    "name": "MAX_PAYLOAD_SIZE",
                    "value": "900mb"
                },
                {
                    "name": "KEEP_ALIVE",
                    "value": "true"
                }
            ]

Tried adding a sticky session to ELB, It didn't work as well :(

Really struggling with this, @joelgriffith Please help!!

**Comment by joelgriffith** [comment]
Unfortunately, whatever is load-balancing in front of you containers needs to have some kind of sticky session management. In our hosted service we do this in our load-balancers, so that sessions started on one machine can be routed back to that same machine.

I'm sure ECS has some kind of solution to the problem?
