### ISSUE TITLE
proposal: support page_limit parameter. This would stop converting html to pdf at the page limit specified

### ISSUE THREAD

**Issue by andrewmayer00** [browserless/chrome#1566]
support page_limit parameter. This would stop converting html to pdf at the page limit specified

**Comment by joelgriffith** [comment]
Well! After doing some digging it appears we do support this natively via the `pageRanges` parameter in our pdf API: https://chrome.browserless.io/docs/#/Browser%20API/post_pdf. This will allow you to set a limit, IE 5 pages:

```sh
curl --request POST \
  --url https://chrome.browserless.io/pdf \
  --header 'Content-Type: application/json' \
  --data '{
	"url": "https://example.com",
	"options": {
		"pageRanges": "1-5"
	}
}'
```

If there's less than `5` pages, this will just pass through the total it generated (in this case 1)
