### ISSUE TITLE
Default launch arg don't include DEFAULT_STEALTH

### ISSUE THREAD

**Issue by kadaan** [browserless/chrome#1571]
**Describe the bug**
Pre-booted chrome instances don't respect DEFAULT_STEALTH

**To Reproduce**
1. Set environment variable `DEFAULT_STEALTH` to `true`
2. Start browserless
3. Check logs
```
c.e.d.s.e.r.e.d.BrowserlessContainer     : STDERR:   "playwright": false,
c.e.d.s.e.r.e.d.BrowserlessContainer     : STDERR:   "stealth": false,
c.e.d.s.e.r.e.d.BrowserlessContainer     : STDERR:   "executablePath": "/usr/bin/google-chrome",
```

**Expected behavior**
Pre-booted chrome instances should respect DEFAULT_STEALTH

**Screenshots**
N/A

**Additional context**
None

**Comment by joelgriffith** [comment]
Merges!
