### ISSUE TITLE
Cannot set property '_trackingId' of undefined

### ISSUE THREAD

**Issue by gufoe** [browserless/chrome#1578]
It's been a couple weeks now and I sometimes get the following error calling POST on /pdf

```
400 Bad Request:
Cannot set property '_trackingId' of undefined
```

I am using `browserless/chrome:latest` (pulled today 5 July) on a docker swarm but it was happening on the previous version as well.

The problem happens once in a while, but as time passes, it becomes more frequent until i reboot the container, which seems to make the problem go away for a while.

My env variables:
      - MAX_CONCURRENT_SESSIONS=4
      - CONNECTION_TIMEOUT=30000
      - MAX_QUEUE_LENGTH=4
      - PREBOOT_CHROME=true
      - DEMO_MODE=false
      - ENABLE_DEBUGGER=false
      - TOKEN=...
      - WORKSPACE_DELETE_EXPIRED=true
      - DEFAULT_USER_DATA_DIR=/tmp/my-profile
      - PROXY_HOST=...
      - PROXY_PORT=443
      - PROXY_SSL=true

**Comment by gufoe** [comment]
The issue seems fixed now, i got the last error on July 7th, thank you and keep up the good work you are doing :)

**Comment by joelgriffith** [comment]
Should be fixed in https://github.com/browserless/chrome/pull/2228
