### ISSUE TITLE
Browserless latest docker image not rendering images in PDFs

### ISSUE THREAD

**Issue by j-ahmd** [browserless/chrome#1662]
When making a call to  `/pdf?token={your_token}` with HTML that contains image tags for instance: 

```
<img src="https://images.com/some-logo.png"
             alt="logo"
             class="header-logo" />
```
this is not being rendered in the PDF.
This issue has been reproduced locally by downloading the latest image. 

```
docker run -p 3000:3000 browserless/chrome
```
In docker hub, it seems to have been updated yesterday: https://hub.docker.com/r/browserless/chrome/tags?page=1&ordering=last_updated

However, when using a previous image eg: `1-chrome-stable` the images are being rendered as expected in the PDFs.

**Comment by j-ahmd** [comment]
For now, we have rolled back the image to `1-chrome-stable` and that seems to be working with the changes.

**Comment by joelgriffith** [comment]
Thanks for posting, seems like it’s a potentially big regression, will take a look soon!

**Comment by joelgriffith** [comment]
Unfortunately I can't seem to replicate:

```sh
$ docker run -p 3000:3000 browserless/chrome
```

Images work with the following URL:

```sh
curl --request POST \
  --url 'http://localhost:3000/pdf?stealth=' \
  --header 'Content-Type: application/json' \
  --data '{
	"url": "https://pixabay.com/images/search/testing/"
}'
```

**Comment by RyanBertrand** [comment]
@j-ahmd you can try passing gotoOptions to delay the PDF until the network requests are finished. 

```
curl --request POST \
  --url 'http://localhost:3000/pdf?stealth=' \
  --header 'Content-Type: application/json' \
  --data '{
	"url": "https://pixabay.com/images/search/testing/",
	"gotoOptions": {"waitUntil":"networkidle0"}
}'
```

**Comment by joelgriffith** [comment]
Going to close out for now since this can’t be easily reproduced
