### ISSUE TITLE
Screencast API and pages with videos that autoplay

### ISSUE THREAD

**Issue by saas-developer** [browserless/chrome#1727]
**Describe the bug**
I noticed that if a page has an autoplaying video, then the screencast API does not record the video. From what I can debug, looks like the video fails to play.

Eg with a mp4 video:

**To Reproduce**
1. Run the code below

```
curl --output videomp4.webm -X POST \
  https://chrome.browserless.io/screencast?token=MY_TOKEN \
  -H 'Content-Type: application/javascript' \
  -d 'module.exports = async ({ page, startScreencast, stopScreencast }) => {
  await page.setViewport({ width: 1000, height: 1000 });
    await page.goto('\''https://www.theloadout.com/wp-content/uploads/web-stories-assets/assets/biggest-streamers/1.mp4'\'');
    
    startScreencast();
    await page.waitFor(10000);
    stopScreencast();
}'
```

**Expected behavior**
Video plays and is captured by the screencast api.

**Comment by joelgriffith** [comment]
Hey there: this is likely due to mp4's only working chrome proper (and not _Chromium_). You can try this easily by using docker locally and trying `browserless/chrome:1-chrome-stable`

**Comment by saas-developer** [comment]
Ah I see. Do you offer `chrome` for the API at https://docs.browserless.io/docs/screencast.html or is it only `chromium` ?

**Comment by joelgriffith** [comment]
Yup, all APIs are available for chrome, going to close this out since it should fix the issue
