### ISSUE TITLE
Response Headers are not returned

### ISSUE THREAD

**Issue by samharnack** [browserless/chrome#1728]
**Describe the bug**

Custom response headers are not returned, according to the [http.spec.ts](https://github.com/browserless/chrome/blob/master/src/tests/integration/http.spec.ts#L467-L470) tests, `/screenshot` should be returning `x-response-url`, `x-response-code`, `x-response-status`, `x-response-ip`, and `x-response-port` as sent by [functions/screenshot.js](https://github.com/browserless/chrome/blob/master/functions/screenshot.js#L129-L133)

I just noticed the tests are expecting `x-response-por` and not `x-response-port`.

**To Reproduce**

```shell
curl -D - --request POST \
  --url 'https://chrome.browserless.io/screenshot?token=<TOKEN>' \
  --header 'Cache-Control: no-cache' \
  --header 'Content-Type: application/json' \
  --data '{
	"url": "https://www.browserless.io",
	"viewport": {
		"width": 1200,
		"height": 600
	}
}'
```

**Expected behavior**

I'd expect `x-response-url`, `x-response-code`, `x-response-status`, `x-response-ip`, and `x-response-port`  to be available in the response headers.

Based on the code I'd expect to be able to return custom headers from `/screenshot` and `/function` by returning a `headers` attribute along with `data` and `type`.

**Comment by joelgriffith** [comment]
@samharnack were a bit behind in usage-based release, and have a new version going out tomorrow that’ll have this. Does it work when you’re token is removed (thus routing your request to our demo server)?

**Comment by samharnack** [comment]
@joelgriffith confirmed! it does work as expected without the `token` param 🥳

**Comment by samharnack** [comment]
@joelgriffith Just verified using my `token` and it looks to be working as expected.
