### ISSUE TITLE
CLI for running from the command line (outside of docker)

### ISSUE THREAD

**Issue by broofa** [browserless/chrome#1780]
**Is your feature request related to a problem? Please describe.**

I haven't been able to get the container-ized version of this project to work.  (New Apple M1 architecture, yadda, yadda).  However I am able to run it from the command line like this:
```
$ node node_modules/browserless-chrome/build
```
While this works, it is non-standard, and relies on knowledge about where the package is installed.  This turns out to be problematic in contexts where a module may be "hoisted" into a different directory.  For example by `lerna` or where yarn "workspaces" may be used.

**Describe the solution you'd like**
```bash
$ npm i browserless-chrome  # etc...

$ browserless <options...> #  Runs browserless, as above
```

**Describe alternatives you've considered**

**Additional context**

**Comment by joelgriffith** [comment]
Hey, sadly this isn’t something we’ll get to anytime soon. We do now support M1 in latest, as well as our release tags (see README). You can also run things via `npm run dev` and use our env file to specify arguments.
