### ISSUE TITLE
[Bug]: dumpio with Puppetteer.connect(..) does not work 

### ISSUE THREAD

**Issue by gionapaolini** [browserless/chrome#1802]
**Describe the bug**
Refer to https://github.com/puppeteer/puppeteer/issues/7580
It seems the problem is caused by the browser rather than the library.

**Comment by askdesigners** [comment]
Any fix on this one?

**Comment by joelgriffith** [comment]
Hey there -- you'll need to supply that as a query-string parameter as `puppeteer.connect` doesn't let you do `dumpio` in it's API:

```js
puppeteer.connect({
  browserWSEndpoint: 'ws://localhost:3000?dumpio=true',
  ignoreHTTPSErrors: true,
  defaultViewport: {
    width: 1920,
    height: 2520
  },
})
```

The contents _will_ be mixed in with the logs that browserless produces, however I can confirm it's working locally.
