### ISSUE TITLE
Issue with chrome.browserless.io access. SSL expired 

### ISSUE THREAD

**Issue by aroksetx** [browserless/chrome#1825]
I am receiving next error starting from October 1st. After investigation from my side I did found that issues appears because chrome.browserless.io using Let's Encrypt certificate.  From September 30 Let's Encrypt certificates were facing huge issues, because their core certificate expired https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ .
Can you update certificate for chrome.browserless.io. If you wanna I can buy wildcard certificate for you)

`CAN NOT CONNECT TO BROWSERLESS!!!!!! exc =  ErrorEvent {
  target:
   WebSocket {
     domain: null,
     _events: { open: [Object], error: [Object] },
     _eventsCount: 2,
     _maxListeners: undefined,
     readyState: 3,
     protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1006,
     _extensions: {},
     _receiver: null,
     _sender: null,
     _socket: null,
     _isServer: false,
     _redirects: 0,
     url: 'wss://chrome.browserless.io?token=************************f',
     _req: null },
  type: 'error',
  message: 'certificate has expired',
  error: { Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'CERT_HAS_EXPIRED' } }`

**Comment by joelgriffith** [comment]
This should be easily addressed by upgrading your websocket client to a newer version. This list of devices that don't support this is somewhat old here: https://letsencrypt.org/docs/certificate-compatibility/.

Ware you running on an older machine, and what version of puppeteer? I'm very hesitant to re-setup a new certificate provider, as it's a very risky swap to make (plus maintaining ongoing cert updates, etc). We've had a few folks come up with this, and it was pretty trivial for them to update their libraries to make stuff work again.
