### ISSUE TITLE
Using a proxy via the query parameters does not complete the request

### ISSUE THREAD

**Issue by gousta** [browserless/chrome#1835]
**Describe the bug**
I simply get one of the following errors, seems random but I believe it is not:
1. Navigation failed because browser has disconnected!
2. Error: Protocol error (Page.navigate): Target closed.

**To Reproduce**
1. Create a directory somewhere on your machine
2. Run `npm init`
3. Run `npm install puppeteer`
3. Create a file test.js and paste the following code inside it:
4. Add your own browserless and proxy server (I can't share mine ofc)
```
const puppeteer = require('puppeteer');
(async () => {
  try {
    const wssHost = 'BROWSERLESS_HOST_OR_IP';
    const wssQuery = new URLSearchParams({
      token: 'AUTHENTICATION_KEY_FOR_BROWSERLESS_REMOVE_IF_YOU_DONT_HAVE_ONE',
      keepalive: '900000',
      adblock: '',
      stealth: '',
      timeout: '10000',
      '--proxy-server': 'PROXY_HOST_OR_IP_WITH_PORT',
      '--no-sandbox': '',
      '--no-zygote': '',
    });
    
    const browserWSEndpoint = `wss://${wssHost}/?${wssQuery.toString()}`;

    const browser = await puppeteer.connect({
      browserWSEndpoint,
      ignoreHTTPSErrors: true,
    });

    const page = await browser.newPage();
    page.authenticate({
      username: 'PROXY_USERNAME',
      password: 'PROXY_PASSWORD',
    });

    await page.goto('https://www.google.com');
    await page.screenshot({
      path: 'hey.png',
      fullPage: true,
    });
    // other actions...
    await browser.close();
  } catch (e) {
    console.error('TEST FUNCTION ERROR HANDLER', e);
  }
})();
```

**Expected behavior**
I expected a screenshot to be captured and saved inside the same folder of the script with name `hey.png`

**Screenshots**
```
TEST FUNCTION ERROR HANDLER Error: Navigation failed because browser has disconnected!
    at *******/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at *******/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (*******/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (*******/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (*******/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:256:14)
    at Connection._onClose (*******/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:138:21)
    at WebSocket.<anonymous> (*******/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (*******/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (events.js:314:20)
```

**Desktop (please complete the following information):**
 - OS: macOSX using docker on our own cloud
 - Browser: unspecified
 - Version: unspecified

**Smartphone (please complete the following information):**
 - Device: unspecified
 - OS: unspecified
 - Browser: unspecified
 - Version: unspecified

**Additional context**
I have created an ubuntu machine on DigitalOcean and run:
```
apt update
apt upgrade

# Install docker.io
apt install docker.io -y

# Start the new container
docker run -e "TOKEN=****" -e "CONNECTION_TIMEOUT=60000" -e "DEBUG=-*" -e "ENABLE_CORS=true" -e "KEEP_ALIVE=true" -d --restart=always -p 3000:3000 browserless/chrome
```

**Comment by gousta** [comment]
> I tried something similar and it's not working for me either. I"m trying to use the TOR proxy which is running on my machine but passing the`--proxy-server` flag does not work with `ws:...` or `wss:...`
> 
> **EDIT:** After thinking through the issue, I realized that the docker container did not have access to the tor proxy on the host since the port was only available on localhost by default. After changing the config to `0.0.0.0:9050`, I passed the ip address of the host from the docker bridge which fixed everything.

can you please provide an example of how you had the localhost configuration before so I can understand how I can apply 0.0.0.0 and where?

thanks

**Comment by hatemjaber** [comment]
@gousta 

In the `/etc/tor/torrc` file, you need to add the `0.0.0.0:9050` anywhere in the file (at the end so you can find it quickly). Reload tor on the host system. In my case, my docker ip to link to the host is 172.17.0.1 which I passed in like so:
```
       ....
        const proxy = `socks5://172.17.0.1:9050`;
        const params = new URLSearchParams({
            "--proxy-server": proxy,
            "--user-data-dir": "/tmp/session-123",
            keepalive: "30000"
        });
        const browser = await puppeteer.connect({
            browserWSEndpoint: `ws://localhost:3000?${params}&blockAds`,

        });
        ....
```
I hope that helps!

**Comment by sorryusernameisalreadytaken** [comment]
Was it also possible to visit onion andressen with this?
