### ISSUE TITLE
Bad request error on POST: /pdf with safeMode: true

### ISSUE THREAD

**Issue by and-zverev** [browserless/chrome#1852]
**Describe the bug**
Hi, guys! I'm using browserless/chrome docker image for PDF generation. I'm using https://docs.browserless.io/docs/pdf.html API with such options:
{
    "url": "https://<your-domain>/index.html",
    "safeMode": true,
    "waitFor": ".page-loaded",
    "options": {
        "format": "A4",
        "margin": {
            "top": "50",
            "bottom": "50",
            "left": "25",
            "right": "25"
        }
    }
}
If my html has high resolution images, 8433 × 11606 in my case - i got bad request error(400).
If i set safeMode to false or decrease images resolution - it works fine.

**To Reproduce**
1. Setup browserless/chrome docker container with such options:
    maxConcurrentSessions: 3
    maxQueueLength: 10
    prebootChrome: false
    enableDebugger: false
    enableXvbf: false
    keepAlive: false
    exitOnHealthFailure: true
    limits:
      memory: 2Gi
    requests:
      cpu: 150m
      memory: 2Gi
2. Set up port-forward from container port tcp:3000 to any localhost port
3. Make POST /pdf request using html with high resolution images and with options above via Postman or another rest client.
4. You will see bad request error(400).

**Expected behavior**
PDF generation via POST /pdf should works fine with safeMode: true and any number of images with highest resolution/size.

**Screenshots**
Container logs:
![logs](https://user-images.githubusercontent.com/89831381/138705617-2f3cb437-2f53-492f-a491-b89195d88d62.png)

**Desktop (please complete the following information):**
 - Browserless/chrome docker image version(running in Kubernetes) - 1.46-chrome-stable

**Comment by and-zverev** [comment]
@outerim @apeckham @olofsj @HawaiianSpork 
Сan someone help me?

**Comment by joelgriffith** [comment]
More recent versions of chromium are much more stable with this, so I'd recommend using a later tag, preferably `1-puppeteer-10.4.0`

**Comment by and-zverev** [comment]
Hi @joelgriffith 
I tried `1-puppeteer-10.4.0` version and the result was the same. Do you have other ideas?

**Comment by and-zverev** [comment]
Hi @joelgriffith 
Sorry for the persistence, but this is very important to me. Have you tried to reproduce my case on your own? Please write me what you think about this so that I know what to do next.
