### ISSUE TITLE
JSON Logging

### ISSUE THREAD

**Issue by kevin-lindsay-1** [browserless/chrome#1867]
**Is your feature request related to a problem? Please describe.**
We use a log aggregation service that surfaces up logs, and browserless is being detected as errors all over the place because it's just logging normal strings.

**Describe the solution you'd like**
An option to use JSON logging as an environment variable or some such.

It would also be preferred if code that we log inside of the browserless pod via `/function` or the like could be given a logger that supports standard log levels and JSON logging, and whether or not it uses JSON or string encoding would be connected to the same environment variable as browserless itself.

**Describe alternatives you've considered**

**Additional context**

**Comment by joelgriffith** [comment]
@kevin-lindsay-1 do you run this as a docker image, or as bare-metal node? We use the debugger module for node, however you can "console.log" inside of your function calls which will print to stdout in the docker container.

In our cloud we use:

```
  --log-driver json-file \
  --log-opt max-size=10m \
  --log-opt max-file=5\
```

Which might help your log aggregation woes

**Comment by kevin-lindsay-1** [comment]
I run this in kubernetes, so docker.
