### ISSUE TITLE
image upload failed in docker browserless 

### ISSUE THREAD

**Issue by namilkimfree** [browserless/chrome#1874]
**Describe the bug**
var  imagePath = "file:///usr/src/app/workspace/cat.png";
PuppeteerService.ImageUpload(imageInput, imagePath);  

don't file uploaded 

**To Reproduce**
`
docker run -p 3000:3000 -e "DEFAULT_HEADLESS=false" -e "MAX_CONCURRENT_SESSIONS=20" -e "CONNECTION_TIMEOUT=60000" -e "PREBOOT_CHROME=true" -e "EXIT_ON_HEALTH_FAILURE=true" -e "DEFAULT_BLOCK_ADS=true" -e "DEFAULT_LAUNCH_ARGS=[--lang=ko]" -v C:\Users\free\Desktop\browserless:/usr/src/app/workspace/ --restart always -d --name browserless browserless/chrome

`

docker browserless have a image file
/usr/src/app/workspace/cat.png

docker screenshot

![image](https://user-images.githubusercontent.com/44854923/140040616-be0ecc44-5849-494f-9f07-15f76003b1a9.png)

**Expected behavior**
upload file success

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [latest]

**Additional context**

**Comment by joelgriffith** [comment]
Have you tried `/usr/src/app/workspace/cat.png` for the path?

**Comment by namilkimfree** [comment]
@joelgriffith  yes,

```
var imagePath = "/usr/src/app/workspace/cat.png";
await element.UploadFileAsync(value);
```
but don't upload image file

**Comment by taewookim** [comment]
@joelgriffith 

Just ran another test (browserless/chrome:1-chrome-stable).

```
const form = new FormData();
const buffer = await fs.readFileSync(temp_file_path);

form.append('file', buffer, {
	"contentType"	: params["mime_type"],
	"name"			: 'file',
	"filename"		: temp_file_name
});

let resp = await fetch(params["docker_url"], { 
	method: 'POST', 
	body: form 
});
```

After running this, when i query workspace content via curl, i can clearly see the images there:

```
{ fieldname: 'file',
  originalname: 'b6a35d93-abd2-4602-8977-186911670801.jpg',
  encoding: '7bit',
  mimetype: 'image/jpg',
  destination: '/usr/src/app/workspace',
  filename: 'b6a35d93-abd2-4602-8977-186911670801.jpg',
  path:
   '/usr/src/app/workspace/b6a35d93-abd2-4602-8977-186911670801.jpg',
  size: 136655,
}
```


But if try to access via puppeter:

```
let files = [
    '/usr/src/app/workspace/b6a35d93-abd2-4602-8977-186911670801.jpg',
    '/workspace/b6a35d93-abd2-4602-8977-186911670801.jpg'
]

files.forEach(f=>{
    console.log(fs.existsSync(f));
});
```

Response:
```
false
false
```
