### ISSUE TITLE
Print to PDF with footerTemplate & headerTemplate options

### ISSUE THREAD

**Issue by TiuSh** [browserless/chrome#1879]
**Describe the bug**
I'm trying to print a page to PDF with a custom footer. But when I use either `footerTemplate` and/or `headerTemplate` options the footer and/or header disapear. 

**To Reproduce**
1. Start browserless: `docker run --rm -p 3000:3000 -e "MAX_CONCURRENT_SESSIONS=10" browserless/chrome:1.49-chrome-stable`
2. Go to http://localhost:3000/
3. Execute this example
```ts
export default async ({ page }: { page: Page }) => {
  await page.goto('about:blank');
  await page.addStyleTag({ content: `
    @media print {
      @page {
        margin: 15mm;
      }
    }
  `});
  
  return page.pdf({
    displayHeaderFooter: true, 
    footerTemplate: "<span class='pageNumber'></span>" 
  });
};
```

**Expected behavior**
The footer should be visible, with the page number. 

**Desktop (please complete the following information):**
 - Version: browserless/chrome:1.49-chrome-stable

**Additional context**
I found that another headless browser docker image is having a similar issue that is caused by a missing "locales"  folder, but I don't know if it might be linked: https://github.com/chromedp/chromedp/issues/922#issuecomment-937500493

**Comment by andyMrtnzP** [comment]
Hi!
[According to Puppeteer's docs ](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions), the `<span>` elements **must be the children of an element with id `header-template`**. If you run the following example:

``` javascript
export default async ({ page }: { page: Page }) => {
  await page.goto('about:blank');
  await page.addStyleTag({
    content: `
      @media print {
        @page {
          margin: 15mm;
        }
      }
    `});

  return page.pdf({
    displayHeaderFooter: true,
    headerTemplate: `<div id="header-template" style="font-size:10px !important; color:#ff0000; padding-left:10px">
                        <span class="date"></span>
                        <span class="title"></span>
                        <span class="url"></span>
                        <span class="pageNumber"></span>
                        <span class="totalPages"></span>
                      </div>`,
    footerTemplate: `<div id="header-template" style="font-size:10px !important; color:#ff0000; padding-left:10px">
                        <span class="date"></span>
                        <span class="title"></span>
                        <span class="url"></span>
                        <span class="pageNumber"></span>
                        <span class="totalPages"></span>
                      </div>`,
    margin: {
      top: '100px',
      bottom: '200px',
      right: '30px',
      left: '30px',
    },
  });
};
```
you'll get this pdf:

![pdf-output](https://user-images.githubusercontent.com/93541085/142270553-402ddda3-c850-4fcb-94e7-84c421d73521.PNG)
