### ISSUE TITLE
How are functions/scripts debugged?

### ISSUE THREAD

**Issue by cskwrd** [browserless/chrome#1887]
Sorry for such a vague issue title.

I am trying to scrape my ISP's data usage page, using the `browserless/chrome` docker container. I wrote the script using the in-browser editor as described on the docker hub page. The script seems to run near flawlessly in the browser, but the script has completed successfully only once while using the `/function` API endpoint. I have tried using both attached runs and detached runs as outlined in the documentation.

When I do an attached run I get errors like `Execution context was destroyed, most likely because of a navigation.` and others stating that a node couldn't be found. In the case of missing nodes, the nodes appear when I watch it in the dev tools and often look like they have received a click from the browserless script.

Is there a way to output log messages and browser DOM to a file, or run all of the interacations through an mitm-proxy container so i can see all the requests being made? How should I better diagnose these issues?

**Comment by joelgriffith** [comment]
You can `console.log` stuff in your function, as well as use the `debugger` abilities here: https://docs.browserless.io/blog/2019/04/18/live-debugger.html. It sounds like you might be getting redirected when running your script or it timing out?

**Comment by cskwrd** [comment]
Like I said, when using the live debugger, my test runs are successful. It is when I try to use the `/function` API endpoint, that everything breaks down.

You mention redirects. I am currently using the keep alive functionality. Are cookies and other session data persisted across use?

**Comment by joelgriffith** [comment]
Yes, with `keepalive` they are, however you'll have to find that browser (not just a regular connect URL) by using the sessions API: https://chrome.browserless.io/docs/#/Management%20API/get_sessions. Once you have the `browserWSEndpoint` back, use that in your connect call.
