### ISSUE TITLE
/screenshot api: scrollPage to trigger lazyloaded elements

### ISSUE THREAD

**Issue by tomasc** [browserless/chrome#1922]
**Is your feature request related to a problem? Please describe.**
Lazyloaded elements missing on full page screenshots

**Describe the solution you'd like**
Scroll through page before taking screenshot. 
See implementation here https://github.com/alvarcarto/url-to-pdf-api/blob/2a02f0c14a8eec2d63d1f7ff0e7d369e0c8cad20/src/core/render-core.js#L210-L238
Is that still the best solution to the problem?

**Describe alternatives you've considered**
Inject custom script that lazyloads the elements. However that’d be specific to a url.

**Comment by andyMrtnzP** [comment]
Closing as it was implemented on https://github.com/browserless/chrome/pull/1934
