### ISSUE TITLE
latest tagged image using arm64 arch

### ISSUE THREAD

**Issue by SuJiKiNen** [browserless/chrome#1924]
**Describe the bug**
`docker pull` on amd64 platform actually pull latest pushed arm64 image. 
this break normal default behavior.

**Comment by aashari** [comment]
I got the same issue, I used latest in production environment, all of my browserless cluster breaks because I use amd64 platform

**Comment by joelgriffith** [comment]
Sorry for the disruption! Just a heads up, if you're using this for production systems, I'd stay away from `latest` as it'll sometimes break unintentionally.

Should be back to normal now.
