### ISSUE TITLE
Would it be possible to publish an image with Chrome 97+?

### ISSUE THREAD

**Issue by yurique** [browserless/chrome#1930]
**Is your feature request related to a problem? Please describe.**
There's a new version of Puppeteer, `v12.0.0`, which requires a newer Chrome.

**Describe the solution you'd like**
If it's possible, I'd like to have a `browserless/chrome` image with Chrome version 97 :)

**Describe alternatives you've considered**
An alternative is not to update to Puppeteer `v12.0.0` (for example, keep using `v11.0.0`). This works, and that's what I'm doing.

**Additional context**
https://github.com/puppeteer/puppeteer/issues/7805

**Comment by joelgriffith** [comment]
Cool -- will work on doing a production builds Monday.

**Comment by yurique** [comment]
Awesome! Thank you! :)

FYI: the puppeteer-ticket (puppeteer/puppeteer#7805) got re-opened. As far as I understand this not only depends on Chrome being 97+, but also on a build being >= a specific build no. Apparently if fails with `97.0.4691.0`, as puppeteer requires `97.0.4692.0` or later.

**Comment by joelgriffith** [comment]
Looks like `v12.0.1` fixes the issue, I'll update and see if so

**Comment by joelgriffith** [comment]
OK, `latest` has 12.0.1 as a target
