### ISSUE TITLE
VNC support

### ISSUE THREAD

**Issue by zedtux** [browserless/chrome#1971]
**Is your feature request related to a problem? Please describe.**
Coming from Selenium in Docker, using the [SeleniumHQ/docker-selenium](https://github.com/SeleniumHQ/docker-selenium) images, we are used to use the `-debug` image which runs a VNC server.

That allows us to see the entire session live, and interact with the Chrome debugger (like this image does with the very nice live debug feature).

**Describe the solution you'd like**
Similarly with the Selenium image, a `-debug` secondary Docker image would add the VNC server.

**Describe alternatives you've considered**
I tried to access the ongoing session from the live debug feature, but it seems to block the execution of the test, and making it failing due to timeout on waiting for the next element to appear/disappear/interact with, so it seems that feature is only useful with the debug/pause mode.

**Additional context**
We are developing a Ruby On Rails platform, and we've followed the great blog article [System of a test:
Proper browser testing in Ruby on Rails](https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing) by Evil Martians.

So we're using Capybara/Cuprite and this Docker image.

**Comment by joelgriffith** [comment]
Awesome, this is a great idea. I think we can probably support this -- but it might be some time before it gets implemented due to the work required.

There is also a remote debugger, which you may or may not have seen, which functions rather similiarly but doesn't require VNC on either side (it's all web based). Check it out here https://docs.browserless.io/blog/2019/04/18/live-debugger.html

**Comment by joelgriffith** [comment]
nm, read your comment about the blocking of test execution... have you tried the `latest` tag? I see in the blog post they're using an older tag

**Comment by zedtux** [comment]
I'm using the image `browserless/chrome:1.49-chrome-stable`.

**Comment by joelgriffith** [comment]
Unfortunately this isn’t something we’ll be able to get to in the near future. This unfortunately is something that can mess with focused page when running more than one session at a time

**Comment by zedtux** [comment]
Oh, that's unfortunate. It's quite hard to debug a scenario without seeing what is happening. How are you using this image in this case today when you need to understand what is happening ?

**Comment by zedtux** [comment]
@joelgriffith could you please explain me how, today, you're debugging without VNC ?
