### ISSUE TITLE
What will happen to the requests in queue, if the browserless server restarts

### ISSUE THREAD

**Issue by krisalay** [browserless/chrome#1994]
What will happen to the requests in queue, if the browserless server restarts?

**Comment by joelgriffith** [comment]
Unfortunately those are lost as they're not a "formal" queue, per se, but an HTTP connection that isn't immediately ran. It's essentially just a connection keep open and run when a "spot" opens up. You'll see this as an error in the connection in the client-side, and can retry the connection/call
