### ISSUE TITLE
Latest tag and versioning

### ISSUE THREAD

**Issue by hotrush** [browserless/chrome#2010]
Hello.

I can see that the latest tag on docker hub was created 10 hours ago, but I don't see any mentions on github, the latest tag here is 1.50 and it was tagged 21 days ago.

Is it a mistake or you got hacked?

**Comment by joelgriffith** [comment]
Not an issue: we create `latest` on every push to master. The versioned tags are done manually, and only after vetting them.

**Comment by hotrush** [comment]
> we create latest on every push to master

oh, that's so weird... would be good to note this on top of docs 😉
