### ISSUE TITLE
Not able to set api key or basic auth

### ISSUE THREAD

**Issue by kingrupam** [browserless/chrome#2039]
**Describe the bug**
Not able to set api key or basic auth, please fix it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joelgriffith** [comment]
Your bug mentions “ Not able to set api key or basic auth, please fix it”, but we have no idea what you mean. Are you using the hosted service? Puppeteer? An API call? What key is this for or from?

please provide some more details

**Comment by malaxmimdkm** [comment]
Yes, I am using self hosted browserless/chrome.
How to authenticate via nodejs?
is any authentication method available ??

**Comment by malaxmimdkm** [comment]
> Your bug mentions “ Not able to set api key or basic auth, please fix it”, but we have no idea what you mean. Are you using the hosted service? Puppeteer? An API call? What key is this for or from?
> 
> please provide some more details

Yes, I am using self hosted browserless/chrome.
How to authenticate via nodejs?
is any authentication method available ??
