### ISSUE TITLE
video not play

### ISSUE THREAD

**Issue by ordomalleus** [browserless/chrome#2099]
Why can't video playback and errors in the console work? Checked on sites trovo.live, twitch.com. On local puppeteer with google chrome works fine.
![image](https://user-images.githubusercontent.com/12936839/151859631-832698ad-af66-4a02-8b7f-ca79bdeb4453.png)

**Comment by joelgriffith** [comment]
You’ll likely need to use chrome stable, which we have as a dedicated option for hosting or as a docker tag as well
