### ISSUE TITLE
Interactive debugger limits script size

### ISSUE THREAD

**Issue by nigelellis** [browserless/chrome#210]
Hi,

Love what you've built here @joelgriffith - when attempting to debug an issue, I was using an inline script which had a large HTML snippet I wanted to use with `page.setContent`.   This failed when sending to the server with HTTP error 413 (entity too large).    Looking at the source it appears you're not setting a body size or buffer size.

I think the following would fix it:
```js
   // Express 4.0 - replace XX with number, ex: 5mb
   app.use(bodyParser.json({ limit: 'XXmb' }));
   app.use(bodyParser.urlencoded({ extended: true, limit: 'XXmb' }));
```

Thanks,
Nigel.

**Comment by joelgriffith** [comment]
Thanks for the kind words @nigelellis! Looking at our code I think it is configurable here: https://github.com/browserless/chrome/blob/master/src/routes.ts#L50, though we don’t have it documented yet. I’m assuming you’re running the docker image? If so — give that a whirl!

**Comment by nigelellis** [comment]
Awesome, I'll give that a whirl.

Thank you.

...

**Comment by nigelellis** [comment]
That didn't work.   The issue is the debugger frame sends a request to https://chrome-devtools-frontend.appspot.com/serve_file/ ( https://chrome-devtools-frontend.appspot.com/serve_file/@7dcf9ab595accf60cb03faf2225011cfabc3fe02/inspector.html?remoteFrontend=true&ws=localhost:9222/debugger )..  This request is <2K in size and returns HTTP error 413.   It looks like a change needs to be applied to the service deployed in Appspot.

Thanks,

Nigel.

https://cl.ly/701779/Image%202019-06-07%20at%205.22.45%20PM.png

...

**Comment by joelgriffith** [comment]
Ah, so it’s out dependency on the hosted chromium tools that’s killing us. We know how to work around it now, so guess it’s time!

**Comment by nigelellis** [comment]
@joelgriffith do you have an ETA on when this might get resolved?   In the interim, is there a workaround I can use for my self-hosted image?   Thanks.

**Comment by nigelellis** [comment]
@joelgriffith do you have an ETA on when this might get resolved?   In the interim, is there a workaround I can use for my self-hosted image?   Thanks.

**Comment by joelgriffith** [comment]
@nigelellis unfortunately don't have a solid ETA just yet -- we've had a few more urgent issues that required my un-devoted attention.

A workaround might be running the image locally, and using our built-in puppeteer debugger here: https://docs.browserless.io/blog/2019/04/18/live-debugger.html. This does require you to run locally, or have a hosted account with browserless.

I'm aiming to get to this next week, but it is somewhat of an involved change!

**Comment by nigelellis** [comment]
Thanks Joel, appreciate the update.

...
