### ISSUE TITLE
Playwright not working using official API

### ISSUE THREAD

**Issue by rhlr** [browserless/chrome#2137]
**Describe the bug**
I am trying to use the commercial API for one of my projects which uses playwright. Upon connecting, I'm getting this error 

> (node:698070) UnhandledPromiseRejectionWarning: Error: browserType.connect: Server disconnected: 

Even though the server doesn't connect, the dashboard shows successful requests.

**To Reproduce**
1. Trying the official API documentation from here https://docs.browserless.io/docs/playwright.html
2. Below code to reproduce: `(https://docs.browserless.io/docs/playwright.html#playwrightchromiumconnectovercdpwsendpoint-string)`
`    

         const pw = require('playwright');

         (async () => {

          const browser = await pw.chromium.connect("wss://chrome.browserless.io/playwright?token=MY-API-TOKEN");

          const context = await browser.newContext();
           const page = await context.newPage();

          await page.goto('https://www.example.com/');
          await page.screenshot({ path: 'example.png' });
        
          await browser.close();
          })();`

**Expected behavior**
Screenshot of the webpage should have been saved.

**Screenshots**
![Screenshot from 2022-02-13 19-48-23](https://user-images.githubusercontent.com/1620866/153757339-8bec87ba-c926-4326-a9f4-ca3b2c77ae4b.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]

**Comment by joelgriffith** [comment]
What version of playwright are you running locally?
