### ISSUE TITLE
/screencast low frame rate

### ISSUE THREAD

**Issue by JoeUp** [browserless/chrome#214]
I have been tinkering with the /screencast rest api and have found that in some situations the resulting frame rate of the video recorded is very low.

While a youtube video as shown in the example code returns acceptable frame rates, the browser game example below is not usable.
https://playcanv.as/p/LwskqxXT/

code used (load, click, hold down right arrow, record for 5 seconds)
```
"code": 'module.exports = async ({ page, startScreencast, stopScreencast }) =>
{
await page.goto("https://playcanv.as/p/LwskqxXT/");
await page.waitFor(5000);
await page.mouse.click(100,100);
startScreencast();
await page.keyboard.down("ArrowRight");
await page.waitFor(5000);
stopScreencast();
}'
```
Example output from screencast:
https://drive.google.com/file/d/1XOLmHEMNIJ6UC9yOfxmq-ViSAzvZ6QN-/view?usp=sharing

Is there any ability to expose video​Bits​PerSecond to attempt to increase or is there another solution which is preferred?
(Is it possible for browserless to take multiple screenshots? that could later be joined back together with ffmpeg)

Use case is to be able to generate short video files using a web browser game.  May not be possible but any input is appreciated!

Joe

**Comment by joelgriffith** [comment]
How provisioned is the host/machine running the docker image? Unfortunately there's a lot of demands being placed on that host as it has to do CPU-backed WebGL rendering as well as capture that source too. I think we have framerate set pretty high in the implementation, and all other alternatives I've seen are choppy under heavy use as well :(

I think about the only option is increasing the amount of CPU/Memory to the docker image or the machine itself...

**Comment by joelgriffith** [comment]
If you have a GPU attached this performs much better, since chromium can use that to do the webgl parts and leave the CPU available for recording. We're not setup to build the image with GPU support, but that's something we can look to add.

**Comment by JoeUp** [comment]
Thanks for the response Joel! That makes sense.  I have been enjoying the Browserless API but have not attempted to host an image of it.

Do you have a recommended hosting environment for this application or a good example to reference for a beginner to achieve deploying on a hosted machine with GPUs added?  I am a hobbyist that has limited experience hosting images in my own cloud account VMs on google or aws.  I am aware that this is an extensive learning ramp beyond the scope of this issue but if you have insight in how you would approach I would appreciate it.

Feel free to close this though if you have no plans of altering or enabling the /screencast API to run something GPU intensive.

**Comment by joelgriffith** [comment]
Yeah, unfortunately after doing some looking into this, it appears that getting GPU support for docker containers is pretty risky business. There's a lot of things out there, and they're all platform-dependent (AMD/Nvidia), which makes it tough to find good solution.

I wish I had a better answer for this, however for the time being I'm going to close this out as it's not something that can be readily fixed given the current landscape.
