### ISSUE TITLE
Use with a video card?

### ISSUE THREAD

**Issue by voodee** [browserless/chrome#2184]
When developing locally the performance is very good. But when I try to run the service in the docker, the performance drops 10-20 times. This is especially visible when visiting sites written in unity.

As I understood the problem in `xvfb`. When I start the service locally most of the load is on the video card but when I run it in docker all the computation is CPU based.

I rented Compute Engine from Google Cloud with NVIDIA Tesla T4. But from what I understand, the browser does not see the GPU.

Naturally, I start the browser with the flag `headless=false`. I also use the flags `--enable-webgl` and `--use-gl=desktop`, but this does not help.

How do I run a browser, with GPU rendering, but without a physical monitor?

**Comment by joelgriffith** [comment]
I think a lot has to do with graphic card drivers and their compatibility with docker. I haven't researched much on the subject as it's not something we see terribly often, but adding a driver to the image would likely enable it to be used (the graphics card that is)

**Comment by unlikelyzero** [comment]
@voodee i was hoping to give this a shot when i had the need: https://github.com/NVIDIA/nvidia-docker

Have you tried that yet?

**Comment by joelgriffith** [comment]
Going to close this for now. Link above looks worth looking into!
