### ISSUE TITLE
Running on Lambda?

### ISSUE THREAD

**Issue by astrike30** [browserless/chrome#2223]
In principle, is there anything that makes running the docker container in Lambda impossible / not a good idea? The docs make reference to Lambda with the SINGLE_RUN env variable, but I can't seem to find anything else.

I haven't set it up yet so I'm not even sure that the container works as expected, but I figured I'd ask here first to make sure.

Thanks!

**Comment by joelgriffith** [comment]
With single run this is possible if lambda supports the container size? Worth a shot but not something we’ve tested explicitly
