### ISSUE TITLE
Named tags don't support arm64

### ISSUE THREAD

**Issue by weeix** [browserless/chrome#2313]
**Describe the bug**
In https://hub.docker.com/r/browserless/chrome/tags, only the *latest* tag supports `linux/arm64`. Named tags, e.g., *1-chrome-stable*, *1-puppeteer-1.20.0*, and *1.52-puppeteer-5.4.1*, only support `linux/amd64`.

**To Reproduce**
1. On an arm64 device, run `docker run -p 3000:3000 browserless/chrome:1.52.0-chrome-stable`
2. See error

    ```
    WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    standard_init_linux.go:228: exec user process caused: exec format error
    ```

**Expected behavior**
The container continues to run after being created.

**Screenshots**

![image](https://user-images.githubusercontent.com/6592791/164019152-7692d81d-3336-4db3-9e07-fa69db367626.png)

![image](https://user-images.githubusercontent.com/6592791/164019610-2e782795-cafc-4531-9f90-ad8aca529c32.png)

**Additional context**
 - OS: Debian GNU/Linux 11 (arm64)
 - Docker: v20.10.14

**Comment by joelgriffith** [comment]
Yup, coming very soon, we've got a fix in development right now and will push it soon.

**Comment by joelgriffith** [comment]
@weeix how important is `chrome-stable` for this? Unfortunately it doesn't look like chrome-stable isn't very well supported on arm64. This is having read through various threads online as well as this bit of code in playwright: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/bin/reinstall_chrome_stable_linux.sh#L5

**Comment by weeix** [comment]
Sorry, I failed to find the difference between the `chrome-stable` and the
`puppeteer` tags.

For me, supporting arm64 in either tags is quite fine. I only want to be
able to reverse to older tags in rare cases where  the `latest` tag doesn't
work.

**Comment by joelgriffith** [comment]
Got it -- for the last few revisions of puppeteer (I think as old at 10.x.x), we can support ARM. Older than that there's no support for those tags, and unfortunately chrome-stable as Chrome proper doesn't yet build for linux arm64, only for Mac M1's.

**Comment by weeix** [comment]
That's fine. Thank you.

**Comment by joelgriffith** [comment]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1499985/164563344-865e0670-eb27-46b3-9c9f-465fe1da0d89.png">
OK, puppeteer-9.x.x and greater (aside from chrome-stable) now have support for amd64 and arm64. Closing!
