### ISSUE TITLE
screenshot failed

### ISSUE THREAD

**Issue by bestRunner** [browserless/chrome#2461]
Using browserless deployed by docker, using springboot to take screenshots of long html fails, as shown in the figure, it will be stuck on this page
screenshot url：http://www.0515yc.cn/m2o/redirect.php?id=568443

![image](https://user-images.githubusercontent.com/36727232/173999890-add9fd0b-eab0-41a2-a2f2-538a88b953fe.png)

**Comment by andyMrtnzP** [comment]
Just curious, why are you using the DevTools debugger page? We've tested screenshotting the URL and we couldn't reproduce the issue. Please message us at support@browserless.io
