### ISSUE TITLE
Playwright cannot find ffmpeg when using the /playwright endpoint

### ISSUE THREAD

**Issue by OLibutzki** [browserless/chrome#2503]
**Describe the bug**
When I connect to the browserless chrome container via the /playwright endpoint it's not possible to record videos as Playwright cannot find ffmpeg.

Error message:
`Executable doesn't exist at /usr/src/app/ffmpeg-1007/ffmpeg-linux`

**To Reproduce**
I described the issue here: https://github.com/microsoft/playwright/issues/15265

**Expected behavior**
A video can be recorded

**Additional context**
As stated [here](https://github.com/microsoft/playwright/issues/15265#issuecomment-1170934532) you need to install chromium + ffmpeg via the Playwright CLI as part of your image build to make it work.

**Comment by OLibutzki** [comment]
After adding this line to the docker file the error does not occur anymore.
`npx playwright install;`

Unfortunately no video is saved after closing the context.

**Comment by rwoll** [comment]
See https://github.com/microsoft/playwright/issues/15265#issuecomment-1172860134 for further info/explanation. Just install ffmpeg via Playwright CLI will do. `npx playwright install ffmpeg`

**Comment by rwoll** [comment]
See https://github.com/microsoft/playwright/issues/15265#issuecomment-1172860134 for further info/explanation. Installing just ffmpeg into the container (but using CR that's already in the Browserless container will do) via Playwright CLI: `npx playwright install ffmpeg`.

**Comment by joelgriffith** [comment]
This likely might be fixed with how we install Dependencies now.

Closing but feel free to reopen if that's not the case
