### ISSUE TITLE
Feature Request: Include Stack trace in API response body on failure

### ISSUE THREAD

**Issue by mpskovvang** [browserless/chrome#251]
When an API request fails it can be hard to troubleshoot the error from just the message. Especially, in larger scripts.

Would it be possible to include the `error.stack` in the response or would it leak too sensible details about the environment? 

https://github.com/browserless/chrome/blob/c6adbe8c056a60b063bc7d1ddea85dfe4a5484c8/src/puppeteer-provider.ts#L213

**Comment by joelgriffith** [comment]
Great point! In some cases having a stack trace is a security threat (I can read over the source and potentially find an attack vector).

Would having it return more information be useful when `NODE_ENV !== 'production'`?

**Comment by mpskovvang** [comment]
I see the concerns in a untrusted public environment, but perhaps behind a private network only accessed from trusted clients it might be useful to have an option to enable the stack trace without putting the entire application in a non-production environment.

I believe, I remembers the API request being handled in a VM sandbox. If that is the case, the amount of sensible details in the stack trace might be limited?

I'll experiment in a local fork and keep you posted.

**Comment by mpskovvang** [comment]
The stack trace seems to be limited to the NodeVM context:

```
TimeoutError: Navigation Timeout Exceeded: 10000ms exceeded
    at Promise.then (/usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
    -- ASYNC --
    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:23)
    at Object.base.apply (/usr/src/app/node_modules/vm2/lib/contextify.js:467:32)
    at module.exports (/usr/src/app/browserless-function-Aj5oUr6su.js:12:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

What is your opinion of an environment variable controlling the stack trace exposing? This would allow trusted environments outputting the error - either in response or in logs.

Browserless already exposes some error details in some cases catchable by e.g. the Stackdriver Error Reporting tool:

```
(node:6) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/usr/src/app/node_modules/puppeteer/lib/JSHandle.js:204:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by joelgriffith** [comment]
Yeah, I'd be open to an ENV variable for exposing stack traces. Something like:

`SHOW_STACK_TRACES=true`

We set these in the config.ts file, and either import them directly or through the classes constructor.

**Comment by joelgriffith** [comment]
Hey @mpskovvang, wanted to check in with you on this. Is this still something you're pursuing in a fork? AFAICT the stack trace in your example isn't super helpful (the top-level error is all the detail you need). Are you still interested in working on this?
