### ISSUE TITLE
Cancel download of CSS, fonts and images.

### ISSUE THREAD

**Issue by victormoj** [browserless/chrome#2555]
I would like to know if it is possible to avoid downloading images, CSS and fonts in the requests. I would like to do it through the API rest in a similar way to stealth. I know it is possible in Puppeteer: https://www.scrapehero.com/how-to-increase-web-scraping-speed-using-puppeteer/

Many thanks!

**Comment by jfgreffier** [comment]
Are you using `/scrape` API ? If so, it is in the docs

https://docs.browserless.io/docs/scrape.html#cookies-headers-and-other-options Intercepting requests

```
{
  "url": "https://example.com/",
  "elements": [{
      "selector": "h1"
  }],
  "rejectRequestPattern": ["png", "jpg"]
}
```

**Comment by victormoj** [comment]
I have already fixed it in both the content API and the scrape API, it supports rejectRequestPattern and rejectResourceTypes. Thank you very much for your help. I thought it only worked in scrape.

**Comment by victormoj** [comment]
Fixed.
