### ISSUE TITLE
difference between browserless/chrome and original chrome

### ISSUE THREAD

**Issue by kwf2030** [browserless/chrome#256]
os: debian 10 x64(Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux)
docker: 18.09.7
browserless/chrome: browserless/chrome:1.10-chrome-stable
pc chrome: win10(1903) x64, chrome 75.0.3770.142

I use chrome devtools protocol(my own impl of the protocol, not puppeteer/node/selenium) with my pc chrome, and everything is ok. but switch to browserless/chrome, its broken, the endpoint response is not the same:
create tab: http://host:port/json/new
browserless response is array:
```js
[
{
"description":"",
"devtoolsFrontendUrl":"/devtools/inspector.html?ws=192.168.33.83:9001/devtools/page/-3XmHd1mp",
"targetId":"/devtools/page/-3XmHd1mp",
"title":"about:blank",
"type":"page",
"url":"about:blank",
"webSocketDebuggerUrl":"ws://192.168.33.83:9001/devtools/page/-3XmHd1mp"
}
]
```

but pc chrome response is object:
```js
{
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/6E20012AE9E4D881931770A8907CDD27",
   "id": "6E20012AE9E4D881931770A8907CDD27",
   "title": "",
   "type": "page",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://127.0.0.1:9222/devtools/page/6E20012AE9E4D881931770A8907CDD27"
}
```

so the deserialization failed. 
also the field in pc chrome calls 'id' but in browserless/chrome has changed to "targetId", it made me wonder, please give me a hand.

**Comment by joelgriffith** [comment]
Definitely a bug, we don't disambiguate between `/json` and `/json/new`. I'll remedy this!

**Comment by kwf2030** [comment]
also `/json/activate/<tab_id>` and `/json/close/<tab_id>`

**Comment by joelgriffith** [comment]
https://github.com/browserless/chrome/pull/261 addresses your issue.

The JSON API isn't well supported for those commands, I'd favor using the protocol commands for closing versus the JSON API. We actually just "mock" the API responses in order to better manage sessions internally.
