### ISSUE TITLE
Two different versions of docs !?

### ISSUE THREAD

**Issue by jfgreffier** [browserless/chrome#2567]
**Describe the bug**
https://docs.browserless.io and https://www.browserless.io/docs are not aligned.

**To Reproduce**
1. Go to https://docs.browserless.io/docs/playwright.html and https://www.browserless.io/docs/playwright
2. The documentation pages are slightly different and the first one does not mention **playwright being tightly version-coupled**

**Expected behavior**
Browserless should offer a unique documentation, with the playwright note.

**Comment by andyMrtnzP** [comment]
Those https://docs.browserless.io docs are actually deprecated and no longer receive updates. Though it is true that we still have links on the README pointing to those docs
