### ISSUE TITLE
Update Playwright version

### ISSUE THREAD

**Issue by jfgreffier** [browserless/chrome#2568]
**Is your feature request related to a problem? Please describe.**
According to documentation, the hosted Playwright version is 1.18.0  
See https://www.browserless.io/docs/versions

It is outdated and makes it impossible to use with Playwright Test. Playwright Test opened a configuration point options for remote connection only recently (probably 1.20 or 1.21) https://playwright.dev/docs/api/class-testoptions#test-options-connect-options

**Describe the solution you'd like**
Playwright on the hosted service should be upgraded, ideally to the same version as the latest Docker image.

**Describe alternatives you've considered**
`browserless/chrome:latest` works flawlessly with Playwright Test connected to it via `connectOptions`

**Comment by andyMrtnzP** [comment]
We just bumped Playwright to `v1.24.0` via https://github.com/browserless/chrome/pull/2572. Could you try that Playwright test with the latest release?

**Comment by jfgreffier** [comment]
Playwright 1.24.0 does not work with `wss://chrome.browserless.io/playwright`. The documentation didn't change and still claims de hosted version is 1.18.0

Is there a way to know what is the deployed version ?

Playwright 1.24.0 works well locally with the new `browserless/chrome` Docker image, so you're good to go. It just needs to be deployed.

**Comment by joelgriffith** [comment]
@jfgreffier unfortunately we've got quite a bit of diligence to do with regards to playwright as they seem to like to break stuff version to version, and we need to see how backwards compatibly different versions are.

We're going to start the process of doing playwright-specific tags as well as puppeteer for Dedicated accounts, but usage-based is always going to be a bit slower to change since it's a shared service used by many.

**Comment by jfgreffier** [comment]
Thanks for the sensible answer. Playwright's team is indeed moving fast, and sometimes breaking things. I'm looking forward to usage-based updates.

**Comment by andyMrtnzP** [comment]
Last year [we introduced Playwright versioning](https://www.browserless.io/docs/versions#playwrights-versioning), and updated the main Playwright version. As of right now, we support connections from Playwright 1.23.0 to 1.27.1
