### ISSUE TITLE
LocalAddress implementation (assigning network interface)

### ISSUE THREAD

**Issue by murat-mehmet** [browserless/chrome#258]
Is there any way to specify which network interface to use? We have multiple network interfaces on the machine. On node.js we can fill localAddress field to specify the outgoing ip address. Is there any way to do it here as well? Or is it easy to implement?

**Comment by joelgriffith** [comment]
Hrm, I'm not sure if you can specify... right now we offer means to bind to a host and port, I haven't experimented with other interfaces. Do you have an example of how this would ideally operate?

**Comment by murat-mehmet** [comment]
Thanks for fast response! For example here is how we do this with [request js](https://github.com/request/request): 
```
request.get({
   uri: 'http://www.google.com',
   localAddress: '123.123.123.123'
}
```
So if we have 2 ips assigned to our machine 111.111.111.111 and 123.123.123.123, this request will be called from the latter one. 

> right now we offer means to bind to a host

Is this the same binding? If we bind it to 123.123.123.123, will all outgoing browser requests use this interface?

**Comment by joelgriffith** [comment]
Oh interesting. We do allow setting a `host` for the webserver portion of browserless (to bind and listen for incoming requests).

Chrome has to have a flag for which network interface to use, however I'm not seeing it atm :/

**Comment by murat-mehmet** [comment]
Actually it has but reversed: https://peter.sh/experiments/chromium-command-line-switches/#netifs-to-ignore
Here we can give a list of all other network interfaces and it will pick the remaining one. But we can't make multiple chrome instances work nicely. They will use the same interface as the first one. I'm not sure about how browserless isolates chrome instances yet, but this could actually work.

Next week we are planning to implement browserless in place of plain puppeteer, just wanted to have some info about this before we dive in.

**Comment by joelgriffith** [comment]
Yup, you can copy these command-line switches over as query-string parameters, so in this case:

```
ws://host:port?--netifs-to-ignore=SOME_LIST
```

**Comment by murat-mehmet** [comment]
Thanks so much! Now only what remains to see is that if multiple `.conntect`s will work as expected. Otherwise we will have to run multiple browserless instances to isolate chromes (which is bad practice I guess). I'm closing this task as I got my answers, and will keep it updated about how it goes.

**Comment by joelgriffith** [comment]
Sounds good! I've got my fingers crossed!

**Comment by bifot** [comment]
does it work now?

```js
const puppeteer = require('puppeteer');

const PRIMARY_ADDRESS = '111.222.333';
const SECONDARY_ADDRESS = '222.111.333';

(async () => {
  const browser = await puppeteer.launch();
  const endpoint = browser.wsEndpoint();
  const endpointNew = `${endpoint}?--netifs-to-ignore=${PRIMARY_ADDRESS}`;

  console.log({
    endpoint,
    endpointNew,
  });

  const browser2 = await puppeteer.connect({
    browserWSEndpoint: endpointNew,
  });

  const page = await browser2.newPage();
  const response = await page.goto('https://api.ipify.org/');
  const text = await response.text();

  console.log(text); // still '111.222.333'
})();
```
