### ISSUE TITLE
Request blocking support?

### ISSUE THREAD

**Issue by snipebin** [browserless/chrome#266]
Hi there,

I'd like to block all requests to common Ad trackers and analytics services during browser-less sessions, by leveraging  EasyList and EasyPrivacy.

I'm wondering about support for request blocking in two ways:

1. https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue
2. use the [brave browser](https://github.com/brave/brave-browser) instead of chrome - thoughts on feasibility?

Thanks

**Comment by joelgriffith** [comment]
We do have our own built-in ad-blocker: https://docs.browserless.io/docs/chrome-flags.html#blocking-ads

**Comment by joelgriffith** [comment]
Closing cause I think this solves it
