### ISSUE TITLE
How do I build usable browserless When the kernel PAGESIZE is 64k？

### ISSUE THREAD

**Issue by s1eke** [browserless/chrome#2693]
**Describe the bug**
browserless does not work on arm64 systems with 64k page sizes.

**Screenshots**
![image](https://user-images.githubusercontent.com/10690839/190863403-dedcdf40-a36d-4672-8cd1-1f02598c20e4.png)
![image](https://user-images.githubusercontent.com/10690839/190863425-ebd9eddc-c97d-431e-ac9c-c1b9f53d01a6.png)

**Additional context**
Normally, the kernel PAGESIZE is 4k, but some arm64 Linux distributions use 64k by default, like CentOS 8 / RHEL 8 / Oracle Linux Server 8.6. so when I run browserless/chrome latest on arm64 centos8, I only get an error, because the google-chrome inside the image is built based on 4k page sizes. So I would like to ask how I should build a browserless image for 64k page sizes.

But I'm not sure if chromium supports building on 64k page sizes, the only information I can find is [a commit that only supports 16k page sizes](https://chromium-review.googlesource.com/c/chromium/src/+/3545665)

**Comment by joelgriffith** [comment]
Definitely possible, but we use externally built chromium artifacts so as not to do that ourselves given the build complexity and potential for doing it improperly. I haven't looked into this too much, but happy to help guide folks if anyone has experience here?

**Comment by lemanschik** [comment]
i can help here but i am not sure if it is clever to do that. But ok i guess @joelgriffith will also release the ARM versions open source so why not.

- https://chromium.googlesource.com/chromium/src/+/main/docs/linux/chromium_arm.md
have a nice day.
