### ISSUE TITLE
Cannot disable the debugger devtools

### ISSUE THREAD

**Issue by isRyven** [browserless/chrome#2698]
Following the documentation instructions here https://www.browserless.io/docs/docker#disabling-the-debugger, i have passed to docker image the environmental variable `ENABLE_DEBUGGER=false`, yet after the launch i still can access the devtools opening up the page on `localhost:3000`.

The docker command i run:
`docker run -d -e "ENABLE_DEBUGGER=false" -p 3000:3000 browserless/chrome`

**Comment by andyMrtnzP** [comment]
`ENABLE_DEBUGGER` sets the _CDP debugger_, the one that allows you to debug Puppeteer scripts in real time

![image](https://user-images.githubusercontent.com/93541085/193920470-0e3cd365-ee83-4a66-b3d2-0662ed062a12.png)

To disable browserless' debugger, you have to disable as a feature `DISABLED_FEATURES=["debugViewer"]`:
` docker run -d -e 'DISABLED_FEATURES=["debugViewer"]' -p 3000:3000 browserless/chrome`
