### ISSUE TITLE
Sessions API fails after a session using devtools

### ISSUE THREAD

**Issue by qosha1** [browserless/chrome#2702]
**Describe the bug**
Having issues with /get-sessions after a session is connected to via devtools using tracking_id. We can still connect and spin up new browser connections, but are unable to retrieve the active sessions list and thus cannot connect to devtools for that session. This process all seemed to work fine before we were trying to connect to devtools during sessions. 

**To Reproduce**

1. To clear state, I relaunched the worker. 
2. I spin up a session using python, and a unique tracking ID
```
self.driver = webdriver.Remote(
            command_executor=settings.BROWSERLESS_URL,
            desired_capabilities=self.chrome_options.to_capabilities(),
            options=self.options
        )
```

4. We call `/sessions` and find the URL for devtools for this session
5. We wait for the session to complete and be shut down via python `driver.quit()`
6. Devtools window shows the message "browser shutdown"
7. After this, any call to `/sessions` returns the following error message:

`request to http://127.0.0.1:36405/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:36405`

**Expected behavior**
`/sessions` should go back to returning an empty list.

**Comment by qosha1** [comment]
update: 
- Tried with python selenium v3 & v4. The examples provided in the docs here - [python](https://www.browserless.io/docs/python) - seem to cause the same issue even without connecting to the devtools url so I guess it's not related to that. 
- Appears to be some sort of error with shutdown of the session after running `driver.quit()` while using python selenium drivers. 

I was able to clear whatever issue this is by calling `/kill/all`. Not exactly ideal to do that, but may give some indication of where the issue is occuring.

**Comment by joelgriffith** [comment]
This is very interesting -- do you happen to have a bit more code to provide that we can use to reproduce?

**Comment by joelgriffith** [comment]
This should be fixed now in https://github.com/browserless/chrome/pull/2718, going to close this out. We'll have production tags for the hosted service ready by mid-week next week!
