### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by hughsaffar** [browserless/chrome#274]
I am experiencing this weird issue with the proxy option!

If I run the docker image locally, everything works fine. However, if I load the image on digital ocean droplet, I get empty response for the requests I send using the same proxy. If I remove the proxy, everything is back to normal. 

I have Nginx as the proxy in front of docker and using SSL certificate on the domain serving the droplet.

**Comment by joelgriffith** [comment]
Seems others have claimed that wrapping your proxy server in quotes is a potential workaround. Might be worth a try?

**Comment by hughsaffar** [comment]
I tried and it didn't help. Now I get `ERR_NO_SUPPORTED_PROXIES` error.

**Comment by hughsaffar** [comment]
It happened that you need to whitelist ips in luminati. Thank you @joelgriffith

**Comment by numfin** [comment]
what is the solution and why is it closed?
