### ISSUE TITLE
Allow all cookies or set a specific

### ISSUE THREAD

**Issue by PlanetDyna** [browserless/chrome#2771]
Is there a way to tell browserless chrome to allow all cookies or set a specific? 
I got this problem: https://github.com/dgtlmoon/changedetection.io/issues/1027

Its running in a docker container on unraid.

**Comment by andyMrtnzP** [comment]
[Puppeteer allows setting cookies](https://pptr.dev/api/puppeteer.page.setcookie) fairly easily. 

``` js
const cookies = [
  {name: 'cookie1', value: 'hello', domain: 'example.com'},
  {name: 'cookie2', value: 'world', domain: 'example.com'},
];

await page.setCookie(...cookies);
```

If you are using browserless' HTTP APIs, you can set cookies as well, sending them on the JSON payload:

``` json
{
  "url": "https://example.com/", 
  "cookies": [
    {"name": "cookie", "value": "hello world", "domain": "example.com"}
  ]
}
```

Though there's no way to set or get HTTP-only cookies. We recommend checking [our blogpost about handling session data](https://www.browserless.io/blog/2022/05/13/manage-sessions/).
