### ISSUE TITLE
Mapbox Stopped working all of the sudden

### ISSUE THREAD

**Issue by volandoo** [browserless/chrome#2883]
**Describe the bug**
I use browserless to render a Mapbox screenshot. It was all working great up until two days ago. Now I only get an empty map view. Tried setting a time out to allow the map to render, and nothing. Not sure if anything changed on your end in the past couple of days.

**To Reproduce**
1. Go to [test.js](https://gist.github.com/volandoo/98e0a43b744d1be0b0090fcac90f86db)

**Expected behavior**
A screenshot should be saved to the filesystem with a map rendered

**Comment by andyMrtnzP** [comment]
Let's follow up at support@browserless.io. We tried the gist and we couldn't replicate the issue
