### ISSUE TITLE
Browserless chrome web UI doesn't shows all the sessions information when run in kubernetes with many replicas

### ISSUE THREAD

**Issue by abratnap** [browserless/chrome#2910]
**Describe the bug**
When I run a browserless chrome in kubernetes with many replicas in kubernetes and expose a service, the broserless UI won't show all the sessions from all replicas. 

The browserless image is chrome1-puppeteer-13.6.0. I can see only few sessions being reported there. 

<img width="1256" alt="Screen Shot 2022-12-13 at 11 33 27 AM" src="https://user-images.githubusercontent.com/5872666/207403948-53497a99-f359-4997-8e81-ed71bceae96c.png">

**Comment by joelgriffith** [comment]
This will only show the current containers running sessions for now. You'll need something to call your containers and aggregate that data together.
