### ISSUE TITLE
Playwright not working on docker

### ISSUE THREAD

**Issue by Umzario** [browserless/chrome#2915]
**Describe the bug**
Hey guys, sorry if this has been reported before, but I'm trying to connect playwright with browserless while using `ws://browserless/playwright` on docker container, but it isn't working. It works for `content`, `function` endpoints, but not for `playwright` (want to switch to playwright). So is it possible to use connect to playwright on docker container? 

p.s. I have `PREBOOT_CHROME` set to true on docker. If that makes a difference. I think I saw an issue stating that it might. Thanks in advance

**Desktop (please complete the following information):**
 - Browser latest docker
 - Playwright version: 1.24.0
 - Python version: 3.10.8

**Comment by andyMrtnzP** [comment]
Prebooting will spawn browsers using default args, and [by default](https://github.com/browserless/chrome/blob/master/src/chrome-helper.ts#L359) those browsers won't start a Playwright server, so they're always expecting Puppeteer/Chrome DP connections.

Can you use `browserType.connectOverCDP` and connect at `ws://localhost:3000`?

**Comment by Umzario** [comment]
> Prebooting will spawn browsers using default args, and [by default](https://github.com/browserless/chrome/blob/master/src/chrome-helper.ts#L359) those browsers won't start a Playwright server, so they're always expecting Puppeteer/Chrome DP connections.
> 
> Can you use `browserType.connectOverCDP` and connect at `ws://localhost:3000`?

Thanks for the quick response. I got no luck with that. I kept getting this error  `Protocol error (Browser.getVersion): undefined`

I also updated the playwright version to 1.28.0 to see if it'll work

**Comment by Umzario** [comment]
Thanks for the help. I made a silly mistake by using `ws://localhost:3000/playwright`. I changed it to `ws://localhost:3000` and it works perfectly!
