### ISSUE TITLE
 The module 'node-fetch' is not whitelisted in VM.

### ISSUE THREAD

**Issue by chrisbell08** [browserless/chrome#298]
Hey Guys,

I have my function running fine in "sync" mode but now trying to make it detached and running into some issues, 

Following the docs ````const fetch = require('node-fetch')```` is giving me the error " The module 'node-fetch' is not whitelisted in VM.". 

I also can't see a way of using the job ID returned to check the job status, is this possible?

**Comment by joelgriffith** [comment]
https://docs.browserless.io/docs/docker.html#exposing-external-modules-to-function Have you seen this? Not sure if you’re running on the hosted service or on your own

**Comment by joelgriffith** [comment]
@chrisbell08 just wanted to make sure you see my message above!
