### ISSUE TITLE
Audio is not present in video generated from screencast api.

### ISSUE THREAD

**Issue by alokmahor** [browserless/chrome#2984]
**Describe the bug**
I am using docker 20.10.5 and screencast api for recording video of webpage. I am able to record and watch video but that does not have audio. 

```
curl -X POST \
  http://localhost:3000/screencast?--window-size=1920,1080 \
  -o video.webm \
  -H 'Content-Type: application/javascript' \
  -d '
    module.exports = async ({ page }) => {
      const sleep = (ms) => new Promise((res) => setTimeout(res, ms));

      await page.setViewport({ width: 1920, height: 1080 });
      await page.goto(`https://www.youtube.com/watch?v=GnEmD17kYsE`);
      await sleep(10000);
    };
  '
```
What I am missing so audio is not getting recorded.

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Browser: puppeteer chrome inside docker
 - Version:

**Comment by joelgriffith** [comment]
Unfortunately we currently don't have audio support at the moment -- see this post: https://www.browserless.io/docs/screencast

**Comment by Jacquesjh** [comment]
Any news on this? I too am confused if is supported or not afterall
