### ISSUE TITLE
Couldn't establish a connection in WebGui. 'Is your browser running?' 

### ISSUE THREAD

**Issue by masterwishx** [browserless/chrome#3023]
After last Update , When press run button,on Search page getting :
Couldn't establish a connection "ws://192.168.0.199:3007/". Is your browser running?

Befor Working fine...

using Unraid (Linux 64) Docker lasted version

![image](https://user-images.githubusercontent.com/28630321/218682581-d80e8f15-c323-4e6c-bd87-ce182be9c54f.png)

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/218686013-585cd5ab-2e78-48d0-9d74-9953ba3bb2f7.png)

**Comment by rubentorresbonet** [comment]
Same issue here

**Comment by Shannon-Atkinson** [comment]
Same.

**Comment by vsDizzy** [comment]
Guys. Check the settings and your browser port:

![image](https://user-images.githubusercontent.com/5798340/219844242-91eb290e-c61f-40a4-8e8f-346e024fec7e.png)

**Comment by masterwishx** [comment]
> The last working version is
> browserless/chrome:1.57-chrome-stable

Yes , this is the same as "browserless/chrome:1-chrome-stable" , there is no problem with port , 
this version working on WebGUI and changedetection.io (that use it for Fetching content using Playwright) .
But before was latest version working for both , but now not working on WebGUI for some reason ....

**Comment by masterwishx** [comment]
@vsDizzy @rubentorresbonet @Shannon-Atkinson checked the latest version for now and its working again in WebGui , please confirm if possible ...

**Comment by vsDizzy** [comment]
For me latest is also working again, thanks!

**Comment by masterwishx** [comment]
@vsDizzy Thanks for confirming, asked becose I think I should close the issue.
If will be problems on lasted version in future, we can change to "browserless/chrome:1-chrome-stable" again.

**Comment by mredodos** [comment]
i have similar issue how can i solve this ?
