### ISSUE TITLE
Catching working process

### ISSUE THREAD

**Issue by MrAkblt** [browserless/chrome#3035]
**Is your feature request related to a problem? Please describe.**
I am using browserless with puppeter in kubernetes and isAvailable is not enough for me. In order to scale it, I need to know how many processes are running at that moment. I am using `KEEP_ALIVE=true` and `PREBOOT_CHROME=true` parameters and when i use these parameters /pressure always response like this `running = max_concurrent_session`. How can i catch working process in this situation?

**Describe the solution you'd like**
I need a property like `working_process` from /pressure endpoint

**Comment by joelgriffith** [comment]
Do you need _all_ processes or just the Chrome ones that are running?

**Comment by MrAkblt** [comment]
I need just the Chrome ones that are processing any url right now.

**Comment by joelgriffith** [comment]
Got it, yeah the way this is set up right now catches only the parent running procs. We do have a few external system utils to handle other proc-related tasks so this is possible
