### ISSUE TITLE
Stealth mode is not working when using playwright endpoint

### ISSUE THREAD

**Issue by 80982proton** [browserless/chrome#3071]
When using Browserless with Playwright, Stealth mode does not seem to work. Is this feature planned in the next version?

```
def test_browserless_stealth_mode():
    with sync_playwright() as context:
        browser = context.chromium.connect(
            ws_endpoint='ws://0.0.0.0:3000/playwright?stealth=1&timeout=60000', timeout=60000
        )

        page = browser.new_page()
        page.goto('https://bot.sannysoft.com')
        page.wait_for_timeout(5000)
        page.screenshot(path='testresult.png', full_page=True)
        browser.close()
```

![testresult](https://user-images.githubusercontent.com/125216699/223543620-fb2184c4-3687-4827-b62c-4a82976d34ed.png)

**Comment by andyMrtnzP** [comment]
Oddly enough, this doesn't happen with Playwright Node. Perhaps Playwright Python adds some extra config that overrides stealth. That's something we've seen happening with some WebDriver libraries.

Could you try `connect_over_cdp` instead?

**Comment by dextervip** [comment]
@andyMrtnzP any workaround for the playwright python library? Even in the latest version, I am unable to activate stealth and headfull.
