### ISSUE TITLE
Proxy when using webdriver

### ISSUE THREAD

**Issue by arunbabucode** [browserless/chrome#3072]
I have seen the example of how to use a proxy here. https://www.browserless.io/docs/chrome-flags#launching-with-a-proxy. However, it looks like it's on the puppeteer. I would like to know if it's possible to use a proxy on web driver?

**Comment by andyMrtnzP** [comment]
You _can_, however, that will depend on your library. For instance, with `selenium-webdriver`, you'd pass it among the `chromeCapabilities`:

```js
import webdriver from "selenium-webdriver";

const chromeCapabilities = webdriver.Capabilities.chrome();
chromeCapabilities.set("goog:chromeOptions", {
  args: [
    "--proxy-server=http://server:port",
    // ...
  ],
});
```

Keep in mind that this is actually a Chrome feature and not something WebDriver does for you. There is no way to authenticate a proxy using flags with Chrome, and as WebDriver [never planned ](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141#issuecomment-191404952) to allow setting HTTP Auth Headers, **you will require another third party library like `proxy-chain` to authenticate proxies** — in case it needs authentication.

**Comment by arunbabucode** [comment]
@andyMrtnzP Thanks for the example. It's unfortunate that they didn't want to allow proxy authentication. Since it has alternatives, it is ok. In my case, it worked as was shown in your example. 👍
