### ISSUE TITLE
Download file path with selenium

### ISSUE THREAD

**Issue by JNajera** [browserless/chrome#3110]
Hello! I have being trying to use browserless chrome to download files with selenium driver thought the Watir ruby gem without luck. If I use a regular chrome instance it works perfect and store the file on the download directory, but when trying to use browserless I can't find a way to tell the docker instance to change the download path. Any help will be appreciated. 

Example: 
```
chrome_url = 'http://localhost:3000'
download_directory = "./tmp"
prefs = {
   'download' => {
      'default_directory' => @download_directory,
      'prompt_for_download' => false,
      'directory_upgrade' => true,
   },
}

args = [ '--headless', '--no-sandbox']

@browser = Watir::Browser.new(:chrome, options: {prefs: prefs, args: args}, url: "#{chrome_url}/webdriver")
@browser.driver.download_path = @download_directory
# Sample file for testing
@browser.goto "https://www.dwsamplefiles.com/?dl_id=176"
```

**Comment by andyMrtnzP** [comment]
Sorry for the delay on this one. Browserless overrides the download configuration to set it to the `WORKSPACE_DIR` env var —which is the OS temp dir by default—. You should be able to set the path by [running the docker using the `WORKSPACE_DIR` flag](https://www.browserless.io/docs/docker#defining-a-workspace-location) _and_ not trying to override it on your client

```ruby
require 'watir'
require 'selenium-webdriver'

chrome_url = 'http://localhost:3000'
args = [ '--headless', '--no-sandbox']

browser = Watir::Browser.new(:chrome, options: {args: args}, url: "#{chrome_url}/webdriver")
# Sample file for testing
browser.goto "https://www.dwsamplefiles.com/?dl_id=176"
sleep 5

browser.close
```
