### ISSUE TITLE
Node is either not visible or not an HTMLElement + net::ERR_FAILED

### ISSUE THREAD

**Issue by masterwishx** [browserless/chrome#3113]
Having errors after latest update when press run button ...

![image](https://user-images.githubusercontent.com/28630321/227701214-274040d7-1107-457f-b216-02e330bd30a2.png)

Using Unraid (Linux x64) docker + Chrome or Firefox  on Computer

Tried **browserless/chrome:1-chrome-stable version** but having same error

**Comment by andyMrtnzP** [comment]
> `page.click('input[type="submit"]')`

Google actually has small layout changes depending on the region. Try changing that `await Promise.all()` with this:

```js
await Promise.all([
  page.keyboard.press('Enter'),
  page.waitForNavigation(),
]);
```

**Comment by masterwishx** [comment]
Thanks , its working but still having some errors in console ...

![image](https://user-images.githubusercontent.com/28630321/228004432-b18c5c00-c0c1-4a25-bbab-3f52aca8ec80.png)

**Comment by masterwishx** [comment]
> Interesting, it seems to be blocking ad domains. Are you using some kind of adblock or custom DNS server?

Yes , im using Adguard but its disabled for local address 192.168.0.199 , also disabled Adguard at all.
DNS in chrome is default not custom ...  
There was no this kind problems at some updates befor , and i didnt make some DNS or block changes ....

**Comment by andyMrtnzP** [comment]
Sorry for the delay on this one. Are you running browserless with any flags?

**Comment by andyMrtnzP** [comment]
After testing with an adblock DNS server, we had the same output as you. Since it's not directly related to browserless, we're closing this one. Let us know if we should re open it

**Comment by masterwishx** [comment]
> Are you running browserless with any flags?

Yes + token : 

![image](https://user-images.githubusercontent.com/28630321/234278714-6e954874-e3d4-49a5-88cd-aeb1ebfbf8a0.png)

Mostly i need broserless for changedetection.io but WebUI was also working with NO problem befor v1.57 i think ,
also i made Xml template of browserless for Unraid Users for easy install it in docker on Unraid...

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/234280481-5bd0949d-51de-4936-b601-55967a47cf3f.png)

**Comment by andyMrtnzP** [comment]
Ah, I see. The problem here is with the `DEFAULT_BLOCK_ADS=true` . When that flag is present, browserless blocks a list of ads-and-tracking domains, that's why those errors are arising on the console yet the whole workflow continues

**Comment by masterwishx** [comment]
OK Thanks, but strange befor v1.57 i think , console was working without errors ...
Do you mean now it affect only for console ? 
becose changedetection.io that using browserless for fetching pages via Playwright+Chrome is still working Fine.

**Comment by iG8R** [comment]
@masterwishx 
Hello.
Could you please tell what program/extension did you use in this screenshot that allows to edit or remove docker settings?

![](https://user-images.githubusercontent.com/28630321/234278714-6e954874-e3d4-49a5-88cd-aeb1ebfbf8a0.png)

**Comment by masterwishx** [comment]
> Could you please tell what program/extension did you use in this screenshot that allows to edit or remove docker settings?

its Unraid Server
