### ISSUE TITLE
Does browserless support proxy?

### ISSUE THREAD

**Issue by andrew0213** [browserless/chrome#315]
First of all, browserless is really convinent to use, but there is still a problem confused me for a long time.

While using pupputeer, I can config proxy like this:
```
    const browser = await puppeteer.launch({
        headless: false, 
        ignoreHTTPSErrors: true,
        args: [
            '--proxy-server=s4.proxy.mayidaili.com:8123', // => 2. Use Charles proxy for debug
        ]
    });
    const page = await browser.newPage();
    await page.setExtraHTTPHeaders(
        {'Proxy-Authorization': mayiProxy.getKey()},
    );
```

But when I use browserless, I don't know how to config like this. 
Can any one show me? Thanks a lot~

**Comment by andrew0213** [comment]
`mayiProxy.getKey()` returns a value. 
I tried like this:
1. start docker:
```
docker run -e "TOKEN=2cbc5771-38f2-4dcf-8774-50ad51a971b8" -p 3000:3000 --restart always -d --name browserless browserless/chrome
```
2. code:
```
const browser = await puppeteer.connect({
        browserWSEndpoint: 'ws://127.0.0.1:3000?token=2cbc5771-38f2-4dcf-8774-50ad51a971b8',
        ignoreHTTPSErrors: true,
        args: [
                '--proxy-server=s4.proxy.mayidaili.com:8123', // => 2. Use Charles proxy for debug
        ]
    });
    const page = await browser.newPage();

    await page.setExtraHTTPHeaders(
        {'Proxy-Authorization': mayiProxy.getKey()},
    );
   await page.goto('https://httpbin.org/get?show_env=1');
```
But `await page.setExtraHTTPHeaders({'Proxy-Authorization': mayiProxy.getKey()}, );` throws an exception:
```
Debugger attached.
(node:64890) UnhandledPromiseRejectionWarning: Error: net::ERR_INVALID_ARGUMENT
    at navigate (/Users/xinhuiyang/Documents/iCourtWork/code/demo/puppeteerDemo/node_modules/puppeteer/lib/Page.js:520:37)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:64890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64890) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...
```
Am I using in a wrong way?

**Comment by joelgriffith** [comment]
Yup, we definitely support proxies. The issue with `connect` is that it doesn't take the same parameters as `launch` does (in this case `args`). To get around that, we use query-string parameters in the `browserWSEndpoint`: https://docs.browserless.io/docs/chrome-flags.html#launching-with-a-proxy.

In short, any query-string parameter that starts with a `--` is treated as a CLI flag, and we pass that to our internal `puppeteer.launch` call's `args` argument. This allows you to define and use arbitrary CLI flags when doing connect.

Closing this for now since this _should_ resolve the issue, but please re-open if not.
