### ISSUE TITLE
/json/version endpoint is missing required property webSocketDebuggerUrl

### ISSUE THREAD

**Issue by knksmith57** [browserless/chrome#317]
#### overview
It looks like the implemented `/json/version` endpoint is [missing a required property](https://chromedevtools.github.io/devtools-protocol/#get-jsonversion): `webSocketDebuggerUrl`.

Unfortunately, this property is expected and required by Lighthouse ([source](https://github.com/GoogleChrome/lighthouse/blob/90ae4851/lighthouse-core/gather/connections/cri.js#L150-L154)) and I'm unable to find a workaround, thus running lighthouse audits using browserless directly is impossible at this time.

If it'd be more appropriate to file a bug issue elsewhere please let me know!

#### reproduce
```sh
❯ docker run -d -p 3000:3000 browserless/chrome
4fad8522f9f1b7914d893e77c2120c71d2e7c6edb274185b6fc60e8d14194377

❯ curl -s localhost:3000/json/version | jq
{
  "Browser": "HeadlessChrome/77.0.3844.0",
  "Protocol-Version": "1.3",
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/77.0.3844.0 Safari/537.36",
  "V8-Version": "7.7.180",
  "WebKit-Version": "537.36 (@312d84c8ce62810976feda0d3457108a6dfff9e6)",
  "Debugger-Version": "312d84c8ce62810976feda0d3457108a6dfff9e6",
  "Puppeteer-Version": "1.19.0"
}
```

**Comment by joelgriffith** [comment]
Good find. As a workaround, we do run lighthouse (via our /stats API). Source is in the repo, otherwise you can use the API as well?

**Comment by joelgriffith** [comment]
https://github.com/browserless/chrome/blob/master/functions/stats.js

**Comment by knksmith57** [comment]
Oh nice! Thanks for the tip.

I was super curious how y'all managed to get LH running given [only the `port`](https://github.com/browserless/chrome/blob/65f91dfa/functions/stats.js#L9) from an [existing](https://github.com/browserless/chrome/blob/65f91dfa/src/browserless.ts#L80) [puppeteer](https://github.com/browserless/chrome/blob/65f91dfa/src/puppeteer-provider.ts#L614-L618) [instance](https://github.com/browserless/chrome/blob/65f91dfa/src/chrome-helper.ts#L324-L334) is passed in.

I _think_ the reason why this works for the stats endpoint is because the [local, internal port](https://github.com/browserless/chrome/blob/65f91dfa/src/puppeteer-provider.ts#L131) for the literal chrome instance is used --is that right?

iiuc, there's at least one bummer with the `/stats` endpoint that patching this property would solve and that's that `/stats` doesn't currently support customization of the audit config.

Btw this codebase is super clean and idiomatic --really nice work. And thanks so much for getting back to me so quickly!

**Comment by joelgriffith** [comment]
Thanks for that! Just pushed up a fix -- let me know if it works for you!

**Comment by knksmith57** [comment]
@joelgriffith wow, thanks for pushing a patch so quickly!

unfortunately, the plot thickens. I set up a test harness over at https://github.com/knksmith57/browserless-lighthouse to ease reproduction. Additionally, I opened https://github.com/knksmith57/browserless-lighthouse/issues/2 under that project to reduce noise here.

if you're interested + have time, I'd love to pick your brain to figure out what's going on with lighthouse <> browserless.

thanks again!

**Comment by joelgriffith** [comment]
Will take a look, we’ll get to the bottom of it!

**Comment by knksmith57** [comment]
for posterity / anyone else looking to run custom lighthouse audits using browserless, while @joelgriffith and team investigate, it's possible to work around these public API quirks by leveraging the (super slick!) [`/function` public API endpoint](https://docs.browserless.io/docs/function.html) and adding lighthouse to the `FUNCTION_EXTERNALS` allow list.

See knksmith57/browserless-lighthouse#3 and [`lib/browserless/function.js`](https://github.com/knksmith57/browserless-lighthouse/blob/7863b9ad6a210cd84862e551274ad5ec53949925/lib/browserless/function.js) if you're curious about the implementation.
