### ISSUE TITLE
Webdriver not starting on ARM

### ISSUE THREAD

**Issue by harm-matthias-harms** [browserless/chrome#3200]
**Describe the bug**
I tried the Ruby example with a local container for development. The requests over Capybara time out, but the original issue looks like the web driver in the container didn't even start because of some missing dependency. The API like screenshot works fine.

**To Reproduce**
1. Follow https://www.browserless.io/docs/capybara
2. Replace `https://YOUR-API-KEY@chrome.browserless.io/webdriver` with `http://localhost:3000/webdriver`

**Expected behavior**
I can connect to the web driver.

**Desktop:**
 - OS: macOS 13.3.1
 - Apple Silicon Chip

**Additional context**
```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
2023-05-01T20:04:40.313609339Z Unhandled Rejection at: Promise {
2023-05-01T20:04:40.313815297Z   <rejected> Error: timeout
2023-05-01T20:04:40.313839006Z       at Timeout.timeoutFunc (/usr/src/app/node_modules/tcp-port-used/index.js:204:25)
2023-05-01T20:04:40.313849006Z       at listOnTimeout (node:internal/timers:564:17)
2023-05-01T20:04:40.313857631Z       at process.processTimers (node:internal/timers:507:7)
2023-05-01T20:04:40.313868464Z } reason: Error: timeout
2023-05-01T20:04:40.313877339Z     at Timeout.timeoutFunc (/usr/src/app/node_modules/tcp-port-used/index.js:204:25)
2023-05-01T20:04:40.313885922Z     at listOnTimeout (node:internal/timers:564:17)
2023-05-01T20:04:40.313894047Z     at process.processTimers (node:internal/timers:507:7)
```

Used docker-compose file
```
version: '3'
services:
  browserless:
    image: browserless/chrome
    ports:
      - 3000:3000
```

**Comment by usu** [comment]
I have a similar issue with the latest docker image (browserless/chrome:1.58.0-puppeteer-19.7.5). I assume it's caused by the fact, that there is no ARM build for this image.

The previous version (1.57.0-puppeteer-19.2.2) included an ARM build and worked fine for me on an Apple M1.

**Comment by harm-matthias-harms** [comment]
This was also my first thought, but for the latest tag arm64 exists, and `docker image inspect 619d33aa1ddb` also shows the container is for arm64.

```
...
"Architecture": "arm64",
"Os": "linux",
...
```

**Comment by usu** [comment]
Ah I see. @joelgriffith Any chance we can get ARM builds on docker hub not only for the `latest` tag but also for the 1.58 version? Or is there any issue in 1.58 that prevents ARM builds?

**Comment by joelgriffith** [comment]
Try as I might there doesn't seem to be widespread support for webdriver/Chrome on Linux ARM64 from what I've seen. Do either of you know of a binary out there that works?

**Comment by usu** [comment]
> Still not seeing much. Happy to accept a PR to address this, but from what I can see Chromedriver isn't well supported in linux ARM builds.

For linux ARM I understand. But for Mac ARM (M1/M2) the drivers should work, shouldn't they? At least I have not problem to run the image with the latest tag on my M1 machine. Unfortunately, ARM builds on docker hub are only available for the latest build and not for the production builds. Any chance we can have them also back for the production builds?
