### ISSUE TITLE
Rest API "deviceScaleFactor" restrictions

### ISSUE THREAD

**Issue by Grocker42** [browserless/chrome#321]
Hi,
in the screenshot Rest API, the "deviceScaleFactor" is restricted to a number between 1 and 100. But in the puppeteer's screenshot API I can set the "deviceScaleFactor" to lower than one. Is there any reason for this restriction in the Rest API?

**Comment by joelgriffith** [comment]
I think we just arbitrarily set an upper limit on it since the size can get out of hand pretty quickly (for instance 2 is double the size of 1, so it's an exponential scale).

Did you have a case where you needed more than `100`?

**Comment by Grocker42** [comment]
I do not need more than 100, but 0.5 would not be bad.

**Comment by joelgriffith** [comment]
Ah! Great point. Will remedy this shortly

**Comment by joelgriffith** [comment]
Ok, min set to 0.01, closing out now
