### ISSUE TITLE
Await.close() doesn't work

### ISSUE THREAD

**Issue by luminous8** [browserless/chrome#324]
Hi,

I have an issue with await.close() and browserless (it seems that's the same issue as here https://github.com/GoogleChrome/puppeteer/issues/4882).

index.js
`
'use strict';

const screenshot = require('./script');
screenshot(1, 'https://www.pinqponq.com/fr?fbclid=IwAR2e00y2Rgn4J4VNbSH80-DtfeQ3OEkH-sJ-2EkXml3422uttgDxXEI4C-4', ['desktop','tablet','mobile'], {
	cropped: false,
	delay: 3000,
	exportType: 'file',
	filetype: 'jpeg',
	jpegQuality: 92,
})
.then(results => {
	console.log(`end date : ${new Date().toLocaleString("en-US", {timeZone: "Europe/Paris"})}`);
	console.log({results});
})
.catch(e => {
	console.log({e});
});
`
script.js
`
'use strict';
require('dotenv').config({ path: '../../../.env' })

const puppeteer = require('puppeteer');
const blacklist = require('./../blacklist');
const devicesList = require('./../devices');

const CONF_DEBUG = false;
const CONF_DEFAULT_TIMER = 3000;
let CONF_TIMEOUT = 0;
let OPTION_CROPPED = false;

exports.default = async function(id, url, devices, screenshotOptions) {
  console.log(`${url} start date : ${new Date().toLocaleString("en-US", {timeZone: "Europe/Paris"})}`);

  let promises = [];

  /* Get the devices infos */
  let selectedDevices = [];
  for (var i = 0; i < devices.length; i++) {
    selectedDevices.push(devicesList.find(device => device.name === devices[i]));
  }

  console.log(`screenshotOptions ${JSON.stringify(screenshotOptions)}`);

  /* redefine options to have default value */
  const options = {
    cropped : screenshotOptions.cropped ? screenshotOptions.cropped : false,
    delay: screenshotOptions.delay ? screenshotOptions.delay : CONF_DEFAULT_TIMER,
    exportType: screenshotOptions.exportType ? screenshotOptions.exportType : 'file',
    filetype: screenshotOptions.filetype ? screenshotOptions.filetype : 'jpeg',
    jpegQuality: screenshotOptions.jpegQuality ? screenshotOptions.jpegQuality : 90,
  }

  let cropped = options.cropped;
  let exportInfo = {
    type: options.exportType,
    'info': null,
    'mobile': null,
    'tablet': null,
    'desktop': null,
  };

  const browserArgs = `&blockAds&ignoreDefaultArgs=--no-sandbox,--disable-setuid-sandbox,--disable-translate,--hide-scrollbars,--disable-translate,--ignore-certificate-errors,--ignore-certificate-errors-spki-list,--audio-output-channels=2,--disable-infobars,--window-position=0,0,--window-size=1920,1080,--lang=en-US,en;q=0.9'`;
  const browserEndPoint = `wss://screenshot.mydomain.com?token=TOKENTOKEN&blockAds${browserArgs}`;

  let browser = null;
  if(CONF_DEBUG === false) {
    browser = await puppeteer.connect({
      browserWSEndpoint: browserEndPoint,
      ignoreHTTPSErrors: true,
    });
  } else {
    browser = await puppeteer.launch({
      dumpio: true,
      headless: false,
      args: [
      ' --no-sandbox',
      '--disable-gpu',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-translate',
      '--hide-scrollbars',
      '--disable-translate',
      '--ignore-certificate-errors',
      '--ignore-certificate-errors-spki-list',
      '--audio-output-channels=2',
      ],
    });
  }

  selectedDevices.forEach(function(element) {
    promises.push((async() => {
      let fileName = `${id}_${url.replace(/[^\w\s]/gi, '').substring(0, 50)}_${element.name}.${options.filetype}`;

      return (async() => {
        try {
          let timer = CONF_DEFAULT_TIMER;
          const page = await browser.newPage();

          await page.emulate(element);
          await page.goto(url);

          await page.screenshot({ path: `./${fileName}`, fullPage: true });
          console.log('screenshot done;');

          await page.close();

          /********* ERROR HANDLING *******/

          page.on('error', err => {
            console.log(`on error ${element.name} > ${err}`);
            throw new Error(err.toString());
            return err.toString();
          })

          page.on('dialog', async dialog => {
            console.log(`on dialog ${dialog}`);
            await dialog.dismiss();
          });

          page.on('pageerror', async pageerror => {
            console.log(`on pageerror ${pageerror}`);
          });

  } catch (err) {
    throw new Error(`${url} ${element.name} : ${err.toString()}`);
  };
})();
})());
});

return Promise.all(promises)
.then(async function() {
  console.log(`exports infos ${exportInfo}`);
  await browser.close();
  return exportInfo;
})
.catch(err => {
  throw new Error(err.toString());
  console.log(`error ${err}`);
  browser.close();
})
};

module.exports = exports['default'];
`

I'm using tabs to make screenshots of different devices, so I need to wait for each page to be properly closed and then close the browser. Except that the tabs won't close themselves and will create a timeout issue..

Any guess on this?

Thanks!

**Comment by joelgriffith** [comment]
I've noticed this before, especially for the `browser` object. I'd suggest not awaiting for it to close unfortunately.

`browser.close` does kill everything under its domain -- is there a reason you need to manually close each page first?

**Comment by luminous8** [comment]
Not really, It seems that was the proper way to do it but it works fine with `page.close()` only.
I'll kill everything with browser.close(). 

Thanks for your help!
