### ISSUE TITLE
--user-data-dir not working

### ISSUE THREAD

**Issue by Themesaul** [browserless/chrome#3268]
**Describe the bug**
It doesn't get the parameter in the user data dir websocket URL. You never use the profile you should and always create a new one

**To Reproduce**
1. Create a chromium profile.
2. Export and mount in docker with the proper permissions
3. use the url `ws://192.168.x.x:3000?--user-data-dir=/opt/custom_profile` It has also been tested with the URL `ws://192.168.x.x:3000?--user-data-dir=/opt/custom_profile/Default`
4. session is not used 

**Expected behavior**
The session is used correctly 

**Additional context**
I have tried different versions of docker. Including the latest tag

**Comment by joelgriffith** [comment]
Does that file or directory exist? Might be good to see any logs you'd have as well.

**Comment by Themesaul** [comment]
> Does that file or directory exist? Might be good to see any logs you'd have as well.

I found out that the problem was with the implementation, not with browserless. In the implementation a new context was created each time and that is equivalent to an incognito browser

**Comment by Themesaul** [comment]
It's not a bug
