### ISSUE TITLE
Don't refresh Chrome process with ongoing activity

### ISSUE THREAD

**Issue by yvmarques** [browserless/chrome#329]
Hello,

I have a script that is basically doing several actions, such as scroll page, screenshot, click on links, etc.

Sometimes I receive errors that the page has been closed, and I noticed that it's happening around the moment the Chrome processes are being restarted.

I am wondering if the `CHROME_REFRESH_TIME` option could be the cause and if so, would that be possible, for e.g., kill the processes expecting task and schedule those having a task when it has done doing it ?

**Comment by joelgriffith** [comment]
This has been on my mind from time to time. I think we should just have a TTL on browsers, and after they're "done" then restart them if they're past the timestamp. I'll look into implementing this soon!
