### ISSUE TITLE
proposal: allow screencast output to workspace to support arbitrary /function-like responses

### ISSUE THREAD

**Issue by knksmith57** [browserless/chrome#330]
The [`/screencast`](https://docs.browserless.io/docs/screencast.html) API is super cool.

Because both `/function` and `/screencast` enable the user to run arbitrary code, the user is forced to make a tradeoff: either use `/screencast` and get a recording of the script to see what happened but forgo the ability to return parseable data (ie: JSON, HTML, etc), or use `/function` to get parseable data but forgo the ability to receive a recording.

We can see similar tradeoffs for `/screenshot`, `/pdf`, and `/download`. The bigger theme behind this GH issue, and the one I'd love to pick your brain on, is if unifying these interfaces is something worth considering.

Here's what I'm thinking:

`/screencast` (and `/pdf`, `/screenshot`, `/download`) support writing the rendered output (video, PDF, image, arbitrary file) to a [scoped download](https://docs.browserless.io/docs/workspace.html#scoping-downloads) workspace subdirectory instead of returning it directly. When operating in this mode,  HTTP response control is returned to the user, just like with `/function`.

The mechanics for this are all up in the air, but my gut says it should work similarly to how the scoped downloads interface works today: using a `trackingId` param (eg: as a query param in the request URI, or as a context property in the body).

<hr/>

What do you think?

**Comment by knksmith57** [comment]
To clarify: `/screenshot` and `/pdf` operate differently from `/download` and`/screencast` in that they don't use user-supplied code as input; for these endpoints the response body would likely be empty but the workspace output bit would remain the same.

**Comment by joelgriffith** [comment]
Yeah, this is a fantastic idea. My thought was original to supply a query-param like `record` to any API/connect call and have browserless do its screencasting instrumentation for that session. Once done, we'd have a directory (like you mentioned) that holds the videos and consumers can GET/DELETE videos from them. Possibly put a TTL on each file, which we have helpers to do.

What do you think @knksmith57? Might be also cool to have a `RECORD_ON_FAILURE` to record failed sessions, though that'd require us to _always_ record and optionally save the file.

**Comment by knksmith57** [comment]
I think that's a great idea!

Supporting something like `record` on any API/connect call would definitely address the bigger question of how to present end users with a simple and consistent way to get a screen recording without having to port existing `/function` (etc) code to `/screenshot`'s interface.

I _think_, based on something I read on your blog / indie hackers, we won't be able to support screen recording on _all_ endpoints because some _have_ to be run headless --am I remembering that correctly? If so, it sounds like this enhancement would still provide a ton of value to users and something like a simple call-out on the docs would be sufficient to avoid frustrating users with unexpected behavior.

> Might be also cool to have a RECORD_ON_FAILURE to record failed sessions, though that'd require us to always record and optionally save the file.

I'm torn on this one --on one hand, this could be hugely valuable to users when trying to debug misbehaving tests. On the other, I anticipate this would noticeably impact resource requirements and ultimately increase operating costs. That might not be a big deal for operators that opt to run on their own hardware as they could turn it off if need be, but for you and the managed browserless.io instances, this would cut into your bottom line (assuming it was made available on the pay-as-you-go plan); though, at the same time, would probably _increase_ revenue for dedicated plans :wink:. Totally up to you and interested to hear what you think!

**Comment by joelgriffith** [comment]
Good points -- one of the reasons we have to do "headful" is due to the fact that our current screencasting implementation uses a custom chrome-plugin to do the actual recording. This provides both video + audio for screencasts. Sadly, it seems that trying to use more native methods in chromium results in a forced user-initiated accept dialog, which is a block for automating it.

I'll do some experimenting soon and see what I find!

**Comment by bootrino** [comment]
Any update on this? thanks.
