### ISSUE TITLE
when i use browserless by docker.

### ISSUE THREAD

**Issue by yosom** [browserless/chrome#3329]
when i use browserless by docker.

i found swaggle debug Servers url is https://chrome.browserless.io
how i change to http://localhost:3000/docs/
![image](https://github.com/browserless/chrome/assets/129135961/6faf4d83-c942-4d8b-a1c4-12f9ab55888b)

**Comment by andyMrtnzP** [comment]
The swagger page is one of the default features. It should be present unless overridden. What's your Docker configuration?

**Comment by andyMrtnzP** [comment]
Closing this one due to lack of activity. Let us know if we should reopen this.
