### ISSUE TITLE
[BUG] Can't resolve cloudflare captcha

### ISSUE THREAD

**Issue by BlackYuzia** [browserless/chrome#3338]
**Describe the bug**

If you try resolve cloudflare captcha on any website by using browserless you will get 401 error on some ajax query, then page would be reloaded and you should resolve captcha again. That's will repeated until end.

I test on self-hosted instance with stealth enabled. That isn't help.
But, when I try use puppeteer + puppeteer-extra-stealth-plugin in solo with custom user-agent, then I can resolve captcha without infinitely reloading page.

**To Reproduce**
1. Open `https://nowsecure.nl/`
2. Wait until captcha
3. Try resolve captcha
4. Get reloading page after  each resolve of captcha

**Expected behavior**
If you manually resolve captcha you should go to website

**Screenshots**
The same website in headless mode but when I do not use browserless
![image](https://github.com/browserless/chrome/assets/25010528/5c0949dc-d5fd-4aa6-83e7-f0d172413f39)
![image](https://github.com/browserless/chrome/assets/25010528/d6d84bb9-72a0-46ce-a0ca-d7217e44a6f0)

**Additional context**
Don't sure did this **browserless bug**, but in solo play with `puppeteer` & `stealth plugin` all works better.

**Comment by Arsh1219** [comment]
Same issue here. They did not even respond with any updates. Pretty annoying.

**Comment by joelgriffith** [comment]
Can you share the connect URL you're using? We do "bundle" stealth in the docker repo so it should work similarly to native puppteer.

**Comment by BlackYuzia** [comment]
@joelgriffith did it fixed in chromium?

**Comment by Arsh1219** [comment]
It's working as expected now. Thank you team for the fix.
