### ISSUE TITLE
Ability to set number of pre-boot "warm" instances separate from the maximum concurrent instances

### ISSUE THREAD

**Issue by sammcj** [browserless/chrome#3344]
**Is your feature request related to a problem? Please describe.**

At present the number of pre-boot / "warm" instances to have running is hardcoded to be the same as the maximum concurrent instances.

I'm sure there was some logic as to why this was done, but from a scaling and resource usage perspective it would be advantageous to be able to separately configure these.

For example:

- If you have a machine that has limited memory.
- You need at least one warm chrome instance.
	- In my case it's for changedetection.io which seems to only work with warm instances.
- You want it to scale from 1 to say 10 maximum concurrent instances.

Right now, you're limited to setting `MAX_CONCURRENT_SESSIONS` which configures both.

This means if you only want the persistent memory usage of one chrome instance (about 220Mb it seems) when idle as it's quite a lot of wasted memory that could be used for active tasks - you're limited to a maximum concurrency at any time of 1.

**Describe the solution you'd like**

Replace preboot_chrome with a variable that can set the number of preboot instances.

- `PREBOOT_INSTANCES` - Set from 0 (don't warm / pre-boot chrome) to >= 1 for the number of warm instances to start.
- `MAX_CONCURRENT_SESSIONS` - only sets the limit for the maximum concurrent sessions.

**Describe alternatives you've considered**

Add another variable that sets the number of preboot instances:

- `preboot_instances`: `1`

**Additional context**

**Comment by andyMrtnzP** [comment]
We've realized that the `PREBOOT` flag introduces more problems than they solve, so for [version 2](https://github.com/browserless/chrome/pull/3345), they're going to be removed. This is definitely doable for the time being 👍.

**Comment by andyMrtnzP** [comment]
The fix is out! However, we decided that if `PREBOOT_QUANTITY` gets evaluated as `0`, browserless is going to use `MAX_CONCURRENT_SESSIONS`. The idea behind prebooting is to always have a chrome instance ready-to-use, so having 0 of them defeats the purpose of the flag.

**Comment by sammcj** [comment]
Isn’t that the opposite behaviour of what you’d want though?

If I want to have a max of 50, I’d want to have a warm pool that’s much smaller, maybe 1-5. Wouldn’t this mean that I would have to run 50 instances all the time for it to be performant?
