### ISSUE TITLE
Slow process

### ISSUE THREAD

**Issue by ashutosh-tikaj** [browserless/chrome#3369]
When I try to use puppeteer with browserless using connect method , I am facing very high latency in every request. When I use the puppeteer.launch option on my local that is pretty fast. To be precise, launch executes a script in about 3-4 seconds and connect takes over a minute and I am using pyppeteer which is an unofficial port of pyppeteer for python.
Link : https://pypi.org/project/pyppeteer/

```self.browser = await connect(browserWSEndpoint=BROWSERLESS_SESSION)```

**Comment by joelgriffith** [comment]
Can you share with us what service you're using? Is this locally or our hosted service?

Send us over an email to support@browserless.io!

**Comment by ilyazub** [comment]
Hey, @joelgriffith. Thanks for creating this project!

`browser.pages()` and `browser.newPage()` take 2.4-2.6s using the hosted version.

![Image](https://github.com/user-attachments/assets/6f9f58ac-0c90-4185-8335-2838660d8266)

For sure, it's not about the latency to the `production-sfo.browserless.io`:

<img width="633" alt="Image" src="https://github.com/user-attachments/assets/c639ca33-74ad-4ae4-a10d-3833b7778f92" />

What's the best way to improve performance using Puppeteer?

**Comment by avalanche-tm** [comment]
@ilyazub did you figure out what was the problem? I'm facing the same issue. Browserless instance seems to be 2-4 seconds slower than local pupeteer with launch

**Comment by ilyazub** [comment]
@avalanche-tm Nah, we proceeded with another Puppeteer wrapper.

**Comment by avalanche-tm** [comment]
@ilyazub may I know which one? I decided to go with pupeteer-cluster
