### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function 

### ISSUE THREAD

**Issue by Joly0** [browserless/chrome#3383]
**Describe the bug**
Whenever i try to use the page.waitForSelector or page.waitForFunction (these are the two i have tested) functions, i get this error "TypeError: Error.captureStackTrace is not a function" and the script exits.

I have take the default "Search" script and adjusted it slightly, it should work, but it gives the error. Here is the script:
```
// Full TypeScript support for both puppeteer and the DOM
export default async ({ page }: { page: Page }) => {

  // Full puppeteer API is available
  await page.goto('https://www.google.com/?hl=en');


  const [button] = await page.$x("//button[contains(., 'Reject all')]");
  if (!button) throw new Error("button not found");
  await button.click();

  await page.waitForSelector('textarea[type="search"]');
  await page.type('textarea[type="search"]', 'browserless.io');
  await Promise.all([
    page.click('input[type="submit"]'),
    page.waitForNavigation(),
  ]);

  // Logs show up in the browser's devtools
  console.log(`I show up in the page's console!`);

  const topLinks = await page.evaluate(() => {
    const results = document.querySelectorAll('a');
    return [...results].map(el => [el.innerText, el.getAttribute('href')]);
  });

  // Can pause by injecting a "debugger;" statement
  await page.evaluate(() => { debugger; });

  console.table(topLinks);
};
```

Without the page.waitForSelector() function it works, but i would like to use it and there is no way to use it, though i am very new to this and might have done something wrong.

**Expected behavior**
Should work without showing the error and exiting

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox?
 - Version: latest

**Additional context**

**Comment by andyMrtnzP** [comment]
Are you using the code from the debugger examples? Google has minor layout changes depending on your location,  `waitForSelector()` might be failing because of that layout discrepancy. You can try replacing the `textarea[type="search"]` selector for a `textarea`, as Google uses them instead of inputs on certain regions.

**Comment by andyMrtnzP** [comment]
I see. Unfortunately, browserless is not really meant to be used with Firefox. At its core, browserless was designed to be used with Chromium-based browsers. [V2](https://github.com/browserless/chrome/pull/3345) will have support for Firefox and WebKit, but it's not ready yet.

**Comment by Joly0** [comment]
Ahh, thank you for the explanation. Is there already like a test or alpha/beta version of V2 for Docker? Would like to give this a try and maybe help by rising issues with it :)
