### ISSUE TITLE
Screencast wrong output dimensions

### ISSUE THREAD

**Issue by html5maker** [browserless/chrome#341]
The example from [screencast api](https://docs.browserless.io/docs/screencast.html) is producing the wrong dimension:

curl -X POST \
  https://chrome.browserless.io/screencast?token=YOUR-API-TOKEN&--window-size=1920,1080 \
  -o video.webm \
  -H 'Content-Type: application/json' \
  -d '{
  "code": "module.exports = async function main({ page, context }) { await page.setViewport({ width: context.width, height: context.height, deviceScaleFactor: 1 }); await page.goto(context.url); await page.waitFor(context.wait);}",
  "context": {
    "url": "https://www.youtube.com/watch?v=GnEmD17kYsE",
    "wait": 5000,
    "width": 1920,
    "height": 1080
  }
}'

Instead of 1920x1080 it exports 1280x640 video!
I'm expecting to get the final video with the dimensions that I have passed to API.

After looking at the source code it seems that the extension that is recording video has a hardcoded limit for the video screencast and there is also an issue with recording dimensions.

**Comment by joelgriffith** [comment]
I've noticed that setting the viewport _after_ the goto seems to get better results on other integrations. Could you try with this API and see how it runs?

**Comment by vbarbarosh** [comment]
I think you should explicitly specify `maxWidth` and `maxHeight` in `extensions/screencast/background.js`.

The following shell script is reliable produces videos with required dimensions.

    #!/bin/bash

    # http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
    # http://redsymbol.net/articles/unofficial-bash-strict-mode/
    set -o nounset -o errexit -o pipefail

    docker run --rm -i \
        -e __URL__="${1-https://www.youtube.com/watch?v=GnEmD17kYsE}" \
        -e __TIMEOUT__="${2-5000}" \
        browserless/chrome:1.15.0-chrome-stable bash << 'EOF' | tar xf -

        set -o nounset -o errexit -o pipefail

        cat > background.js.patch << 'EOF2'
    --- 1.js 2019-09-11 10:46:20.893905459 +0300
    +++ 2.js 2019-09-11 10:46:57.872300246 +0300
    @@ -22,18 +22,16 @@
               // Get the stream
               navigator.webkitGetUserMedia(
                 {
    -              audio: {
    -                mandatory: {
    -                  chromeMediaSource: 'desktop',
    -                  chromeMediaSourceId: streamId,
    -                  echoCancellation: true
    -                },
    -              },
                   video: {
                     mandatory: {
                       chromeMediaSource: 'desktop',
                       chromeMediaSourceId: streamId,
    -                  minFrameRate: 60
    +                  minWidth: undefined,
    +                  maxWidth: 2100,
    +                  minHeight: undefined,
    +                  maxHeight: 2100,
    +                  minFrameRate: 60,
    +                  maxFrameRate: 60
                     }
                   }
                 },
    @@ -41,7 +39,8 @@
                   const chunks = [];
                   recorder = new MediaRecorder(stream, {
                     ignoreMutedMedia: true,
    -                mimeType: 'video/webm'
    +                mimeType: 'video/webm;codecs=vp8',
    +                videoBitsPerSecond: 10000000,
                   });

                   recorder.ondataavailable = (event) => {
    EOF2

        cat > screencast.js << 'EOF2'
    async function main({page, startScreencast, stopScreencast})
    {
        await page.setViewport({width: 1920, height: 1080});
        await page.goto(new Buffer('__URL__', 'base64').toString());
        await startScreencast();
        await page.waitFor(parseInt(new Buffer('__TIMEOUT__', 'base64').toString()) || 100);
        await stopScreencast();
    }
    module.exports = main;
    EOF2

        patch extensions/screencast/background.js 1>&2 < background.js.patch
        sed -i s:__URL__:`echo "$__URL__" | base64 -w0`: screencast.js
        sed -i s:__TIMEOUT__:`echo "$__TIMEOUT__" | base64 -w0`: screencast.js

        node build/index.js &
        while ! curl -sf 127.0.0.1:3000/workspace -o /dev/null; do sleep 0.2s; done

        W=1920
        H=1080
        curl -sfS http://127.0.0.1:3000/screencast?--window-size=$((W < 500 ? 500 : W)),$(((H < 2 ? 2 : H)+116)) \
            -H Content-Type:application/javascript \
            -o a.webm --data-binary @screencast.js

        # tar cf - a.meta a.webm
        # > tar: -: Wrote only 2048 of 10240 bytes
        # > tar: Error is not recoverable: exiting now
        # > tar: Unexpected EOF in archive
        # > tar: Unexpected EOF in archive
        # > tar: Error is not recoverable: exiting now

        tar cf /dev/stdout a.webm
    EOF
