### ISSUE TITLE
Tough Cookie Dependency Update

### ISSUE THREAD

**Issue by russell-maz** [browserless/chrome#3438]
Hi there, 

There is a npm dependency `request@2.88.2`  that has a dependency `tough-cookie@2.5.0`
Would you be able to update the `tough-cookie` dependency to the latest version?  We use the `browserless/chrome` image and AWS inspector let us know of the following dependency issue:

![image](https://github.com/browserless/chrome/assets/101345328/9720d906-6f2d-4546-a6b9-7f4746005387)

`npm ls -all` gave me the context for this request
![image](https://github.com/browserless/chrome/assets/101345328/758355e0-6593-4db7-a435-de9e4bda4a94)

**Comment by andyMrtnzP** [comment]
Oh, thanks for let us know. I believe we can override this. We'll work on that

**Comment by joelgriffith** [comment]
Yeah, we're going to do the following here:

- Drop the `request` dependency in favor of fetch. We're using request for webhooks but can easily migrate it over to the fetch API.
- Once done, drop node-fetch in favor of the native fetch global.

Thanks for raising!
