### ISSUE TITLE
Fonts render different? 

### ISSUE THREAD

**Issue by raDiesle** [browserless/chrome#345]
By using jests and puppeteer and using browserless, font render differences are reduced, but exist where browserless docker image runs on windows and Ubuntu. Might it be, that important flags from original puppeteer docker image are missing?

**Comment by joelgriffith** [comment]
Hey there!

We don't actually inject any other flags other than our own user-data-dir, so the differences you're probably seeing are due to os differences (sadly).

**Comment by raDiesle** [comment]
Hi, thanks for quick reply,

So you suggest me to expand browserless docker image or switch to puppeteer docker image? 

Best
David

**Comment by joelgriffith** [comment]
It's worth a shot if you want to, but we only inject one or two switches to make things work (namely `--no-sandbox`). Otherwise they're identical to pptr

**Comment by joelgriffith** [comment]
Closing this for now as it's likely do to OS differences and nothing we can really do better
