### ISSUE TITLE
Feature Request: REST endpoint allowlist/denylist

### ISSUE THREAD

**Issue by douglasmiranda** [browserless/chrome#346]
(I don't know if there's a way of doing that and I missed)

It should be nice to have a way of doing something like this:

```bash
docker run -e "ENDPOINT_ALLOW_LIST=screenshot,pdf" -p 3000:3000 --restart always -d --name browserless browserless/chrome

# OR

docker run -e "ENDPOINT_DENY_LIST=function" -p 3000:3000 --restart always -d --name browserless browserless/chrome
```

**Comment by joelgriffith** [comment]
Nice, we do that in some places (namely the debugger), but haven’t expanded it beyond it so far. I think this makes a lot of sense however, as you might want to limit access. 

I’ll probably go with disabling them per-route, as it works with the debugger, so it’s consistent

**Comment by kadaan** [comment]
@douglasmiranda Does #389 look like it would work for you?

**Comment by douglasmiranda** [comment]
Yes xD

That would definitely work!

**Comment by kadaan** [comment]
@joelgriffith Can you help categorize features?  I know some are incorrect.

**Comment by joelgriffith** [comment]
PR is merged, closing!
