### ISSUE TITLE
How to access browser directly without any other panels

### ISSUE THREAD

**Issue by engageub** [browserless/chrome#3463]
**Is your feature request related to a problem? Please describe.**
I would like to access only browser similar to demo shown https://hub.docker.com/r/kasmweb/chrome .
I have arm64 for which browserless/chrome is working fine but there are other panels and debuggers shown which I do not wish to use. 

**Describe the solution you'd like**
Accessing the vnc port should provide a browser in full screen without any other panels. 

**Describe alternatives you've considered**
The following alternative is considered as shown in demo https://hub.docker.com/r/kasmweb/chrome

**Comment by andyMrtnzP** [comment]
Sorry, but that's not possible with browserless. browserless is meant for web automation, not really for final browser usage. We can use the Chrome Devtools Protocol debugger to visualize content running on the browser, but it's meant as a debug-only tool.
