### ISSUE TITLE
Feature Request: healthcheck endpoint

### ISSUE THREAD

**Issue by douglasmiranda** [browserless/chrome#348]
I'm aware of #99 and #101. 

The [docs](https://docs.browserless.io/docs/docker.html#exit-on-health-failure) says:

> browserless routinely checks on the health of the image as it's running. Sometimes it's helpful to have it restart automatically when CPU or Memory usage are above 100% for a period of time (by default 5 minutes)...

:heavy_check_mark: this is useful for keeping each instance/container of browserless/chrome up and running
:heavy_check_mark: self-healing existing container
but ..
:negative_squared_cross_mark: usage in deployment workflow / rollback

But a health check endpoint would provide much more when using, for example, with the Docker's `healthcheck` feature.

- https://docs.docker.com/engine/reference/builder/#healthcheck
- https://docs.docker.com/compose/compose-file/#healthcheck

A health check endpoint `/healthcheck` could be used to make sure:

- Chrome is ready to receive requests
- Maybe those checks about RAM and CPU usage
- Maybe that `isAvailable` we can see at `/pressure` can provide something (I don't actually know what that checks)

That endpoint could return useful information in json and HTTP 200 when the status is OK. 

### Usage in Docker Swarm

Docker Swarm will monitor that endpoint and restart if necessary (when configured to do so). But the default browserless/chrome service already do that from what I understand. Using `EXIT_ON_HEALTH_FAILURE`.

That way we can use that endpoint to make sure Docker Swarm can monitor the health of all replicas when deploying. And in case of an unsuccessful start after an upgrade/change, Docker Swarm can rollback automatically.

I'm sure other container orchestrators like Kubernetes rely on health checks like that to provide features like that too.

**Comment by kadaan** [comment]
I'd love to have a health check as well.  Not sure at the moment what the semantics should be.  Not sure if the server should be unhealthy if there is no capacity to run more requests.

**Comment by douglasmiranda** [comment]
If "no capacity" you mean when we're using settings like `MAX_CONCURRENT_SESSIONS` or `MAX_QUEUE_LENGTH`.

https://docs.browserless.io/docs/docker.html#max-queue-length

yeah, that may not be a good idea.

**Comment by kadaan** [comment]
@douglasmiranda Check out #390

**Comment by kadaan** [comment]
> If "no capacity" you mean when we're using settings like `MAX_CONCURRENT_SESSIONS` or `MAX_QUEUE_LENGTH`.
> 
> https://docs.browserless.io/docs/docker.html#max-queue-length
> 
> yeah, that may not be a good idea.

Correct.  Should it return 200 is there is room to run more and 500 if there isn't?  If not that, what are good semantics for health?

**Comment by douglasmiranda** [comment]
I believe that actually when there's no room in the queue doesn't mean it is unhealthy, it just means you have to wait for being able to use it.

It would be nice if we're able to check if Chrome is able to receive connections, that would be a good parameter for the health check.

What browserless do with `EXIT_ON_HEALTH_FAILURE` may be useful for the health check also.

https://docs.browserless.io/docs/docker.html#exit-on-health-failure

**Comment by kadaan** [comment]
Totally. Depends on the use case. If the server is “full” and you want to take it out of the load balancer, it could be useful. If you want to know if it is “healthy” it is harder.

Following on your idea, what if we indicated that the server was healthy if it was able to delegate work to chrome and get a result (failing or succeeded). For low call volume times, we could automatically trigger a canary request to make sure we have data to use to determine the health.

**Comment by fmoessle** [comment]
What's about a health AND a readiness probe endpoint? E.g. kubernetes supports these two methods of checking if a container is healthy or ready.

**Comment by kadaan** [comment]
> What's about a health AND a readiness probe endpoint? E.g. kubernetes supports these two methods of checking if a container is healthy or ready.

There is a health and readiness endpoint in #390

**Comment by fmoessle** [comment]
That is my current approach with kubernetes:

```
livenessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        curl -X POST 'http://localhost:3000/function' -H 'Content-Type: application/json' -d '{ "code": "module.exports=async({page:a,context:b})=>{const{url:c}=b;await a.goto(c);const d=await a.content();return{data:d,type:\"application/html\"}};", "context": { "url": "https://example.com/" } }'
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 15
```

**Comment by lonkle** [comment]
@fmoessle What does your custom function return? And what is your personal use case for it? I think I want to use your solution as well to restart the container it's running in if I *notice* it's "getting sluggish / buggy".

**Comment by joelgriffith** [comment]
https://github.com/browserless/chrome/pull/1209/files Is our, which means pressure now includes health and memory checks to determine if it’s available. If nothing responds, especially this, that means that the server is decidedly unhealthy and shouldn’t be routed traffic to.

With that I think the source of this issue is effectively closed!
