### ISSUE TITLE
Unable to connect to WebSocket

### ISSUE THREAD

**Issue by yvmarques** [browserless/chrome#350]
Sometimes I am getting this error when I try to connect `puppeteer.connect({ browserWSEndpoint: 'ws://ip:3000'});`

```json
{
  "target": {
    "domain": {
      "domain": null,
      "_events": {},
      "_eventsCount": 3,
      "members": []
    },
    "_events": {},
    "_eventsCount": 2,
    "readyState": 3,
    "protocol": "",
    "_binaryType": "nodebuffer",
    "_closeFrameReceived": false,
    "_closeFrameSent": false,
    "_closeMessage": "",
    "_closeTimer": null,
    "_closeCode": 1006,
    "_extensions": {},
    "_receiver": null,
    "_sender": null,
    "_socket": null,
    "_isServer": false,
    "_redirects": 0,
    "url": "ws://ip:3000",
    "_req": null
  },
  "type": "error",
  "message": "Parse Error",
  "error": { "bytesParsed": 0, "code": "HPE_INVALID_CONSTANT" }
}
```

I looked on the Internet what does it could mean but I couldn't find a good answer. In my special case I first thought it was because I had many requests (about 10/s). But when I look at the logs of the docker, I always have about 5-6 chrome process ready (I have a maximum of 10).

**Comment by joelgriffith** [comment]
> Http Parse Error
Is what your code is hinting at. What's the size of the machine you're attempting to run this on?

**Comment by yvmarques** [comment]
I am using a Droplet : 

2 vCPUs
2GB / 60GB Disk

With CoreOS

**Comment by joelgriffith** [comment]
So 10 at once is kind of the upper limit of a node that size, would you try on a bigger machine and see if that works? Also, when disconnecting, are you doing browser.close or browser.disconnect?

**Comment by yvmarques** [comment]
Here is are the stats of CoreOS for the past 7 days, as you can see, I am only time to time reaching the 10req/s.

![droplet](https://user-images.githubusercontent.com/176204/65184798-8d151800-da66-11e9-8019-17107bad0e14.png)

I am only using `browser.disconnect()` as per the documentation, in order to keep the swarm available.

Actually, my function is launched by Google Cloud Functions, and from the same instance of my function, I can have two or more request.

So I am wondering if this could be the reason and I get this error only when I have two requests from the same Google Functions' container. But to confirm this I am not sure what to look at or how to log this.

**Comment by yvmarques** [comment]
Quick question, that can help me to debug it any further. Is there a way for me to find out which JobID I am currently using with I `puppeteer.connect()` ?

**Comment by joelgriffith** [comment]
You can specify a tracking-id to "tie" them back together, I believe we do log them: https://docs.browserless.io/docs/chrome-flags.html#setting-a-tracking-id

**Comment by yvmarques** [comment]
Thanks, I tried it but unfortunately it doesn't make the use of the pre-booted Chrome, it creates an instance each time.

**Comment by yvmarques** [comment]
Ok, I finally understood was going on. I was just using the same browser with two requests and then  sometimes they just couldn't get anymore requests and returned this error.
