### ISSUE TITLE
Question about ARM64 Version

### ISSUE THREAD

**Issue by Elyeu1** [browserless/chrome#3501]
Hey, I actually only have the question if the ARM64 version is only for the Mac (M1,...) or if the version can also be used for QNAP/Synology.
On my QNAP with an ARM processor (TS-832PX), the whole thing somehow does not work as desired. ("couldn't establish a connection" [...] "is your browser running?").
Does anyone have the ARM64 version running in Docker on a NAS?

**Comment by joelgriffith** [comment]
Anything on the repo with the `linux/arm64` tag should work here: https://hub.docker.com/r/browserless/chrome/tags
