### ISSUE TITLE
Every time I close and restart my Chrome browser, I need to log in again.

### ISSUE THREAD

**Issue by cold-bin** [browserless/chrome#3528]
- google chrome
117.0.5938.88 (正式版本) （64 位） 
- os version
Linux BPC 6.2.0-32-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Mon Aug 14 10:03:50 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joelgriffith** [comment]
Please provide more information so we can reliably reproduce this issue.
