### ISSUE TITLE
Enhancement suggested for /screenshot REST endpoint

### ISSUE THREAD

**Issue by douglasmiranda** [browserless/chrome#355]
Would be useful to have an option to wait for an element to show up before taking the screenshot, very useful for ajax content.

Puppeteer has something for that [`page.waitForSelector`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-pagewaitforselectorselector-options).

[`waitUntil`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-pagegotourl-options) with the `networkidle0` can be very useful for that.

But sometimes that's not enough. There's no way of knowing if the element you want to be visible is present. If that ajax call takes longer than `500ms` after the network activity ceases `waitUntil` won't do the trick.

**Comment by joelgriffith** [comment]
Would having `waitForSelector` be best or `waitFor` which could take a function or selector be better?

**Comment by douglasmiranda** [comment]
`waitFor` would be really nice to have. It would work for everything you can write with javascript. It would be awesome!

**Comment by joelgriffith** [comment]
Cool! I plan on building a larger PR to address this and a few other enhancement's in our Issues.

Thanks!

**Comment by melalj** [comment]
That would be great enhancements - Just stumbled upon this use case. Is there a work around to take the screenshot after 1000ms?
