### ISSUE TITLE
Support for Prometheus Metrics

### ISSUE THREAD

**Issue by anjo-swe** [browserless/chrome#357]
We are interested of using browserless within our organization. At this point we use Prometheus (https://prometheus.io/) for all our metrics & alerting. 

Current metrics endpoints (https://docs.browserless.io/docs/graphql-api.html#metrics) has a lot of valuable information but it would be great if it could be expose as Prometheus metrics as well.

**Comment by joelgriffith** [comment]
I'm not sure I follow, is there something specific that needs to be done in order for prometheus to collect metrics?

**Comment by anjo-swe** [comment]
@joelgriffith Prometheus requires you to expose your metrics using a specific format (https://prometheus.io/docs/instrumenting/exposition_formats/) so that it can pull them. 

There are a lot of client libraries: https://prometheus.io/docs/instrumenting/clientlibs/ that make it easy for you to add support for Prometheus.

**Other useful links:**
* Naming (Best Practices): https://prometheus.io/docs/practices/naming/

**Comment by joelgriffith** [comment]
Should be closed in #381 (Thanks @kadaan)!

**Comment by dewski** [comment]
May be worth re-opening this issue as #381 added support for nodejs and express metrics, but not metrics specific to browserless available currently via `/metrics` or `/pressure`.

**Comment by omri-shilton** [comment]
@joelgriffith I second @dewski for support for metrics and pressure
