### ISSUE TITLE
Generate one page of PDF

### ISSUE THREAD

**Issue by Richieyukio** [browserless/chrome#3591]
How do I need to set parameters to generate a PDF through a website address

**Comment by andyMrtnzP** [comment]
Hey there. You only need to set the `url` key on your JSON payload:

```jsonc
// JSON payload
{
  "url": "https://npmjs.com/"
}
```

cURL request:

```sh
curl --request POST \
  --url 'https://chrome.browserless.io/pdf' \
  --data '{ "url": "https://npmjs.com/" }'
```

Please refer to our docs for more info: https://www.browserless.io/docs/pdf#basic-usage
