### ISSUE TITLE
Support newer versions of playwright

### ISSUE THREAD

**Issue by oskarkivra** [browserless/chrome#3592]
**Is your feature request related to a problem? Please describe.**
As stated here: https://www.browserless.io/docs/versions browserless only supports version 1.34.3, 1.33.0, 1.32.3, 1.31.2, and 1.30.0 of playwright-core.

1.34.3 was released 5 moths ago and 1.30.0 was released 9 months ago.

It's a problem that I only can use older versions of playwright. 

**Describe the solution you'd like**
Support newer versions of playwright and make it as a regular update, like every second week or something like that. Is it possible for me to help?

**Describe alternatives you've considered**
Let me build a container with a custom playwright version. No idea how though

**Comment by oskarkivra** [comment]
Okay I now looked at the code and it looks like it we just need to add the new version here: https://github.com/browserless/chrome/blob/1cef7f380aa62b5cfb50380ee9e0dc80053becfe/package.json#L172 and let this function find the version: https://github.com/browserless/chrome/blob/1cef7f380aa62b5cfb50380ee9e0dc80053becfe/src/chrome-helper.ts#L515C9-L521

Is that correct?

**Comment by andyMrtnzP** [comment]
Actually, those versions mentioned on the docs refer to the supported versions on our cloud workers. The base browserless image supports the last five Playwright versions (1.35 to 1.39 as of Oct. 13, 2023), so, if you're running a Docker container, you should have access to those versions.

You can add Playwright versions outside that range using the method you're trying.
