### ISSUE TITLE
Support Incognito Browser Context

### ISSUE THREAD

**Issue by kadaan** [browserless/chrome#369]
Add support for creating pages in incognito browser context, so that cookies, local storage, etc. are not preserved across pages.

**Comment by joelgriffith** [comment]
Not sure I follow... by default all `connect` calls to browserless create a clean browser by default. You can also use puppeteer to create further browser contexts as well.

Is there something I'm missing?

**Comment by kadaan** [comment]
From my testing when using browserless with `keep_alive` and making calls via the `/function` endpoint, the state of cookie and local storage is persisted across runs.  Creating a new incognito browser context solves this issue.

**Comment by joelgriffith** [comment]
@kadaan this is mostly by intent: if you use the keepalive, you are opting into re-using the browser and all of it's current state.

We do actually support creating your own pages, as we inject the `browser` object into the module's you write: https://github.com/browserless/chrome/blob/master/src/puppeteer-provider.ts#L218. This means you can `browser` as a param:

```js
module.exports = async({ browser }) => {
// Do some stuff with the browser
};
```

**Comment by kadaan** [comment]
@joelgriffith As far as I can tell, what I'm suggesting will still use the same browser but a page in a new context.

```
private async newPage(browser: chromeHelper.IBrowser) {
  if (this.config.enableIncognitoMode) {
    const browserContext = await browser.createIncognitoBrowserContext();
    return await browserContext.newPage();
  }
  return browser.newPage();
}
```

**Comment by joelgriffith** [comment]
Thanks for the PR, merged
