### ISSUE TITLE
[🔴] Unable to use browserless using docker!

### ISSUE THREAD

**Issue by ArnavK-09** [browserless/chrome#3991]
**Describe the bug**
randomly syntax error is being thrown, although working fine tomorrow 

**To Reproduce**

1. Follow https://docs.browserless.io/docker/docker-quickstart/

**Expected behavior**
should start browserless server

![image](https://github.com/browserless/browserless/assets/69188140/bfa5a831-ee46-42cd-bbce-b0ba9e28181c)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linuix (GH CODESPACE)
- Browser [e.g. chrome, safari] Chrome. firefox
- Version [e.g. 22] latest

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6

**Additional context**
> working using docker version v2.6.0

**Comment by joelgriffith** [comment]
Should be fixed in https://github.com/browserless/browserless/pull/3993
