### ISSUE TITLE
Is browserless/base open-source?

### ISSUE THREAD

**Issue by tejasmanohar** [browserless/chrome#406]
I'm using the Dockerfile here as an example for some other stuff and it'd be awesome if the source for Browserless/base was published on Gist or GitHub (maybe it is and I'm missing it)

**Comment by joelgriffith** [comment]
Got ya: https://github.com/browserless/chrome/blob/master/base/Dockerfile!

**Comment by joelgriffith** [comment]
I can definitely relocate this for visibility sake. Not sure if there’s a convention, maybe a `dockerfiles` directory?

**Comment by tejasmanohar** [comment]
omg awesome! i didnt think to look in the base folder. dont think there's a convention but if there was a directory with the word "docker" in it, id open it

**Comment by joelgriffith** [comment]
Sounds good, agreed 🤝
