### ISSUE TITLE
Allow rejection by resourceType in /content endpoint

### ISSUE THREAD

**Issue by calvinl** [browserless/chrome#448]
Hi,

I noticed that a common performance optimization with puppeteer is to avoid having the browser download images and stylesheets. In most cases if you just need the rendered HTML, you don't the browser to actually download the images since all you want is the HTML output. 

In the `/content` endpoint, a `rejectRequestPattern` is provided which appears to reject requests based on the URL of the request. While this can work if we provide patterns to reject all images (jpg, jpeg, png, gif, etc). This may not catch everything. 

A proposal for the endpoint would be to reject by resourceType, which might look something like this:

```js

let rejectResourceTypes = ['image', 'stylesheet', 'font'];

page.on('request', request => {
    if (rejectResourceTypes.includes(request.resourceType())) {
      request.abort();
    } else {
      request.continue();
    }
  });
```

If this seems like a reasonable thing to add to the endpoint, I can open up a PR for this. 

Thanks!

**Comment by joelgriffith** [comment]
Yup, that’d be a great addition to the API. I’m thinking about how it interacts with our current url pattern matching, and I’m wondering if we need a better or more generic interface versus doing these implementation specific filters.

Concern being that a user gets a network request rejected but they don’t know why

**Comment by joelgriffith** [comment]
Merged! Closing.
