### ISSUE TITLE
Reuse existing Chrome instance in live debugger

### ISSUE THREAD

**Issue by ccll** [browserless/chrome#461]
I really really like the live debugger, it helps a LOT writing the code, thanks for the great project!

But lately I've found it very inconvenience automating websites which require login, when pressing 'Ctrl-Enter' to re-evalue the code, a new Chrome instance is launched and the code is run within the new instance, so I need to automate the login process in the code and re-login every time, start over from the login page all the way to the final page I'm caring about, which greatly reduced the productivity.

Is there any way to tell the live debugger to keep using the existing Chrome instance?

P.S. I've tried PREBOOT_CHROME and KEEP_ALIVE env vars, but they seem to work only with external `puppeteer.connect()` sessions, not with the live debugger.

**Comment by joelgriffith** [comment]
Sorry for the radio silence! I think this would be a great feature to have, I'll see if we can work it in somehow soon.

**Comment by ccll** [comment]
@joelgriffith That will be great!

Lately I've started trying to hack this feature myself, my first instinct is to add a new button beside the existing 'Execute' button, could be named 'New  Session' or 'New Sandbox' or 'Reset' whatever.
When clicking the 'Execute' button (or by pressing Ctrl-Enter) all the executions will re-use the same Chrome instance, once the 'New Session/New Sandbox/Reset' button is clicked, the Chrome instance will be destroyed and replaced by a new one.

I don't know if this is reasonable, just my two cents.

![image](https://user-images.githubusercontent.com/5366582/70024896-60d55600-15d6-11ea-9387-990f9fe511d3.png)

**Comment by joelgriffith** [comment]
Going to close for now as this isn't something we'll support. You can use the /sessions query and get the live pages being ran, and continue to use those  if you'd like
