### ISSUE TITLE
Disable Verbose Chrome Driver

### ISSUE THREAD

**Issue by blopker** [browserless/chrome#463]
Hello, I'm trying this out on a side project and it's working really well. Thank you!

I did notice, however, that the chrome driver is pretty chatty. It can be helpful, but it can also obscure other logs. 

I think I tracked the logging down to https://github.com/browserless/chrome/blob/17f5a8980bb97b4e30a2f3edf055195b1d0e4145/src/chrome-helper.ts#L343, where it sends `--verbose` to the driver. 

I'd like to request having some control over this flag. Maybe through an environment variable? I could see setting `CHROME_DRIVER_VERBOSE` or similar to toggle it.

For now I'm overriding the Docker command with `["/bin/sh", "-c", "node ./build/index.js 2> /dev/null"]`.

What do you think?

Thanks!

**Comment by joelgriffith** [comment]
Yup, this has bugged me for a while as well. Sadly it's needed so we can "sniff" out the port it's on and inject some custom logic via puppeteer.

I'll eventually do this work and remove the `chromedriver` dep as well, but it's a sizeable amount of time to do so, so your workaround will have to suffice for a bit :)

**Comment by blopker** [comment]
Ah, gotcha. I dug into Chromium's source a little and found how they solve this problem for their own tests. Chromium writes a file called `DevToolsActivePort` to the user directory when the dev tools start up. In the Browserless container the file shows up in a random temp folder in the pattern of `/tmp/.org.chromium.Chromium.E9nbEV/DevToolsActivePort` where `E9nbEV` is random for each invocation. The file contains just the dev port. Not sure if this is useful since a random folder is just as hard to guess as a random port, but maybe there's a way to explicitly set the path, or otherwise get it?

The other idea I had was to have node optionally capture stderr off the process object and only let it out to the console if the user wants it. Haven't looked into that though.

**Comment by blopker** [comment]
OK, I made a minimal example of what the second approach was:
```
var chromedriver = require("chromedriver");
const { Transform } = require("stream");
const VERBOSE = false;
const port = 1234;
const args = [
  "--url-base=webdriver",
  "--verbose",
  `--port=${port}`,
  "--whitelisted-ips"
];
chromedriver.start(args, true).then(proc => {
  const findPort = new Transform({
    transform: (chunk, encoding, done) => {
      const message = chunk.toString();
      const match = message.match(/DevTools listening on (ws:\/\/.*)/);

      if (match) {
        proc.stderr && proc.stderr.unpipe(findPort);
        const [, wsEndpoint] = match;
        console.log(`got port: ${wsEndpoint}`);
      }
      done(null, chunk);
    }
  });
  if (VERBOSE) {
    proc.stderr.unpipe(process.stderr);
  }
  proc.stderr.pipe(findPort);
  console.log("chromedriver is ready");
});
```
This is more or less a drop in replacement for what's currently in `chrome/src/chrome-helper.ts`, just with the option to enable or disable printing to the console. `wsEndpoint` is just printed, but would normally be saved.

Does this seem like a workable approach? What should the option be called?

**Comment by joelgriffith** [comment]
Oh nice that’s super clever! Prior to the injecting of puppeteer logic,  just looked at the process.env.DEBUG variable time see if it was “*”, and used that as verbose logging (assuming i understood your question)

**Comment by mjsommer** [comment]
Hi @blopker , I know that it has been awhile, but could you explain how you are using your mentioned command `["/bin/sh", "-c", "node ./build/index.js 2> /dev/null"]` ?

I have a build w/ and w/o the `verbose`, but the one with is so slow, it kill development. Without `verbose`, provides no active session link for debugging.

FWIW, I am using Browserless V1, for Selenium.
