### ISSUE TITLE
trouble   

### ISSUE THREAD

**Issue by RedGuitar0** [browserless/chrome#472]
If I have a large JS file (2G) browser, how can I load it successfully. This JS file is a simple array file.

**Comment by joelgriffith** [comment]
You'd have to do it the same way you'd do any other file, load it via a script tag: https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pageaddscripttagoptions, or try and read the file via NodeJS and inject it via: https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pageevaluatepagefunction-args.
