### ISSUE TITLE
Can't bind ip 

### ISSUE THREAD

**Issue by previa** [browserless/chrome#477]
bind host seems broken for a while.

$ docker run -e "HOST=xxx.251.43.23" -p 3000:3000 -e "CONNECTION_TIMEOUT=120000" -e "MAX_CONCURRENT_SESSIONS=40" --restart always -d --name browserless browserless/chrome

2019-12-15T04:43:32.538Z browserless:server { CHROME_REFRESH_TIME: 1800000,
  CONNECTION_TIMEOUT: 120000,
  MAX_CONCURRENT_SESSIONS: 40,
  QUEUE_LENGTH: 10,
  KEEP_ALIVE: false,
  MAX_CHROME_REFRESH_RETRIES: 5,
  DEFAULT_BLOCK_ADS: false,
  DEFAULT_HEADLESS: true,
  DEFAULT_LAUNCH_ARGS: [],
  DEFAULT_IGNORE_DEFAULT_ARGS: false,
  DEFAULT_IGNORE_HTTPS_ERRORS: false,
  DEFAULT_USER_DATA_DIR: undefined,
  PREBOOT_CHROME: false,
  CHROME_BINARY_LOCATION: '/usr/bin/google-chrome',
  DEBUG: 'browserless*',
  DEMO_MODE: false,
  ENABLE_CORS: false,
  ENABLE_DEBUGGER: true,
  ENABLE_DEBUG_VIEWER: true,
  ENABLE_XVBF: true,
  TOKEN: null,
  DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR: false,
  FUNCTION_BUILT_INS: [ 'url' ],
  FUNCTION_EXTERNALS: [ 'lighthouse', 'node-pdftk' ],
  WORKSPACE_DIR: '/usr/src/app/workspace',
  WORKSPACE_DELETE_EXPIRED: false,
  WORKSPACE_EXPIRE_DAYS: 30,
  FAILED_HEALTH_URL: null,
  QUEUE_ALERT_URL: null,
  REJECT_ALERT_URL: null,
  TIMEOUT_ALERT_URL: null,
  EXIT_ON_HEALTH_FAILURE: false,
  MAX_CPU_PERCENT: 99,
  MAX_MEMORY_PERCENT: 99,
  METRICS_JSON_PATH: null,
  HOST: 'xxx.251.43.23',
  MAX_PAYLOAD_SIZE: '5mb',
  PORT: 3000 } Final configuration
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available xxx.251.43.23:3000
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by joelgriffith** [comment]
Sorry for the delay. It’s possible the IP you’re trying to assign to isn’t available in the docker containers network. You have to explicitly tell the container what IPs are there in order to bind properly. https://docs.docker.com/v17.09/engine/userguide/networking/default_network/binding/ Seems useful

**Comment by previa** [comment]
Thank you for the tips.  I have use docker host mode to fix it. 

> docker run  --net=host -e "HOST=xxx.251.43.23"
