### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by luminous8** [browserless/chrome#491]
Hi,

How can we make puppeteer support webGL features?
I got an error on this website: https://www.pantheoneaudio.com/

`Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.`

Thanks!

**Comment by joelgriffith** [comment]
Unfortunately this is largely determined by where/how you run the docker image (and you'll need to install drivers). I've investigated it at some depth, and sadly there doesn't seem to be a reliable way to do this cross-platform with all the different cards and architectures out there.

**Comment by luminous8** [comment]
Thanks for your answer. Do you have any recommandations/links to get started with this?
