### ISSUE TITLE
Feature Request: Allow Disabling JavaScript in the /pdf and /screenshot APIs

### ISSUE THREAD

**Issue by DenzoNL** [browserless/chrome#495]
Hey all,

I couldn't find any existing issue or PR about this, so here it goes:
I would like to be able to use Puppeteer's `page.setJavaScriptEnabled(false)` in the `/pdf` and `/screenshot` APIs by simple setting an option in the POST body for the aforementioned APIs.

I'm aware of the fact that I can simply use Puppeteer for that, but I'd like to avoid that since I only use the APIs in my project.

If all of you are okay with an extension to the APIs like this, I'll start working on a PR as soon as possible. I'd love to hear any comments or feedback you guys might have, too.

Thanks in advance and a happy new year! 🎆

**Comment by joelgriffith** [comment]
Sounds good to me! You can add a new property in the Joi schema (schema.ts). Since it’s not specific to PDF rendering I’d make it a top level Boolean (setJavascriptEnabled), and even add it for the others (screenshot content and maybe even scrape)

**Comment by DenzoNL** [comment]
> Sounds good to me! You can add a new property in the Joi schema (schema.ts). Since it’s not specific to PDF rendering I’d make it a top level Boolean (setJavascriptEnabled), and even add it for the others (screenshot content and maybe even scrape)

Alrighty, I'll get on it today :)

**Comment by DenzoNL** [comment]
@joelgriffith Thanks, that's great to hear! Here's the PR as promised:

https://github.com/browserless/chrome/pull/497

**Comment by joelgriffith** [comment]
Merged!
