### ISSUE TITLE
Update Dockerfile to enable running on Google Cloud Run

### ISSUE THREAD

**Issue by joelpoloney** [browserless/chrome#516]
Deploying to GCR today yields this error:
`Application failed to start: Failed to create init process: Failed to load /usr/local/bin/dumb-init: permission denied`

From this thread: https://browserless.slack.com/archives/C917HV1QR/p1579129260074900. It looks like the Dockerfile needs to be updated to support GCR. Websockets are known not to work but the REST endpoint would.

**Comment by joelgriffith** [comment]
I believe https://github.com/browserless/chrome/pull/517 will fix this once it's merged

**Comment by joelgriffith** [comment]
Should be fixed now, however I haven’t checked myself.

**Comment by joelpoloney** [comment]
Confirmed working correctly on GCR. It's a little bit slower than GKE but not that bad. Was rendering pages in 1-2 seconds instead of 2-3 seconds.

Thank you for fixing so quickly!

**Comment by joelgriffith** [comment]
Yeah, https://github.com/browserless/chrome/issues/516 talks a bit about it, I think they (GCP) have to fetch/start the image and there's a few seconds of overhead therein.
