### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by 40sherrin** [browserless/chrome#525]
`const postsCollection = require("../db")
  .db()
  .collection("posts")
const ObjectID = require("mongodb").ObjectID
const User = require("./User")
let Post = function(data, userid) {
  this.data = data
  this.errors = []
  this.userid = userid
}
Post.prototype.cleanUp = function() {
  if (typeof this.data.title != "string") {
    this.data.title = ""
  } else if (typeof this.data.body != "string") {
    this.data.body = ""
  }
  // get rid of any bogus properties
  this.data = {
    title: this.data.title.trim(),
    body: this.data.body.trim(),
    createdDate: new Date(),
    author: ObjectID(this.userid)
  }
}
Post.prototype.validate = function() {
  if (this.data.title == "") {
    this.errors.push("You must provide a title")
  } else if (this.data.body == "") {
    this.errors.push("You must provide post content")
  }
}
Post.prototype.create = function() {
  return new Promise((resolve, reject) => {
    this.cleanUp()
    this.validate()
    if (!this.errors.length) {
      // save post into database
      postsCollection
        .insertOne(this.data)
        .then(() => {
          resolve()
        })
        .catch(() => {
          this.errors.push("Please try again later.")
          reject(this.errors)
        })
    } else {
      reject(this.errors)
    }
  })
}
Post.findSingleById = function(id) {
  return new Promise(async function(resolve, reject) {
    if (typeof id != "string" || !ObjectID.isValid(id)) {
      reject()
      return
    }
    let posts = await postsCollection
      .aggregate([
        {
          $match: {
            _id: new ObjectID(id)
          }
        },
        {
          $lookup: {
            from: "users",
            localField: "author",
            foreignField: "_id",
            as: "authorDocument"
          }
        },
        {
          $project: {
            title: 1,
            body: 1,
            createdDate: 1,
            author: {
              $arrayElemAt: ["$authorDocument", 0]
            }
          }
        }
      ])
      .toArray()
    // Clean up author property in each post object
    posts.map(function(post) {
      console.log("[+] something goes wrong")
      post.author = {
        username: post.author.username,
        avatar: new User(post.author, true).avatar
      }
      return post
    })
    if (posts.length) {
      console.log(posts[0])
      resolve(posts[0])
    } else {
      reject()
    }
  })
}
module.exports = Post
`

**Comment by joelgriffith** [comment]
Hey there, I’m not seeing anywhere in your code where browserless would come into play. We also don’t have any sort of user authentication as part of the project. I’m afraid your issue is likely elsewhere.

**Comment by 40sherrin** [comment]
this is from my user.js
`const bcrypt = require("bcryptjs")
const userCollection = require("../db").db().collection("users")
const validator = require("validator")
let User = function (data, getAvatar) {
    this.data = data
    this.errors = []
    if(getAvatar == undefined){
        getAvatar = false
    }else if(getAvatar){
        this.getAvatar()
    }
}
User.prototype.cleanUp = function() {
    if(typeof(this.data.username) != "string"){
        this.data.username = ""
    }else if(typeof(this.data.email) != "string"){
        this.data.email = ""
    }else if(typeof(this.data.password) != "string"){
        this.data.password = ""
    }
    // get rid of any bogus properties
    this.data = {     
        username: this.data.username.trim().toLowerCase(),
        email: this.data.email.trim().toLowerCase(),
        password: this.data.password
    }
}
User.prototype.validation = function() {
    return new Promise( async (resolve, reject) => {
    if(this.data.username == ""){
        this.errors.push("You must* provide a username")
    }else if(this.data.username != "" && !validator.isAlphanumeric(this.data.username)){
        this.errors.push("Username only contain litters and numbers")
    }else if(!validator.isEmail(this.data.email)){
        this.errors.push("You must* provide the email address for your account")
    }else if(this.data.password == ""){
        this.errors.push("You must* provide the password for your account")
    }else if(this.data.password.length > 0 && this.data.password.length < 12){
        this.errors.push("Password must at least 12 charaters")
    }else if(this.data.password > 50){
        this.errors.push("Password cannot exceed 50 charaters")
    }else if(this.data.username.length > 0 && this.data.username.length < 3){
        this.errors.push("Username must at least 3 charaters")
    }else if(this.data.username > 30){
        this.errors.push("Username cannot exceed 30 charaters")
    }
    // only if username / email is valid the check to see if its already taken
    if(this.data.username.length > 2 && this.data.username.length < 31 && validator.isAlphanumeric(this.data.username)){
        let usernameExists = await userCollection.findOne({username: this.data.username})
        if(usernameExists){this.errors.push('That username is already taken')}
    }else if(validator.isEmail(this.data.email)){
        let emailExists = await userCollection.findOne({email: this.data.email})
        if(emailExists){this.errors.push('That email already being used.')}
    }
    resolve()
})
}
User.prototype.login = function(){
    return new Promise((resolve, reject) => {
        this.cleanUp()
        userCollection.findOne({username: this.data.username}).then((attempteUser) => {
            if(attempteUser && bcrypt.compareSync(this.data.password, attempteUser.password)){
                resolve("login was successful")
            }else{
                reject("invalid username / password")
            }
        }).catch(() => {
            reject("something goes wrong with the developer's code")
        })
    })
}
User.prototype.register = function(){
    return new Promise(async (resolve, reject) => {
    // step #1 validate user data
    this.cleanUp()
    await this.validation()
    // step #2 only if there are no validation errors
    // then save the user data into a database
    if(!this.errors.length){
        // hash user password 
        let salt = bcrypt.genSaltSync(10)
        this.data.password = bcrypt.hashSync(this.data.password, salt)
        await userCollection.insertOne(this.data)
        resolve()
    }else{
        reject(this.errors)
    }
})
}
module.exports = User`

> Hey there, I’m not seeing anywhere in your code where browserless would come into play. We also don’t have any sort of user authentication as part of the project. I’m afraid your issue is likely elsewhere.
