### ISSUE TITLE
Recommend puppeteer-proxy

### ISSUE THREAD

**Issue by gajus** [browserless/chrome#549]
I have been reluctant to use Browserless.io because of a requirement to have granular control over how HTTP requests are handled (we have internal proxy for handling requests). I have since published a package that enables use of any proxy with remotely hosted Chrome instance.

https://github.com/gajus/puppeteer-proxy

It also allows to set a per-Page, per-Request proxy and properly handles authentication.

I figured it will be useful to other Browserless.io users. If you think so too, please add it to the documentation.

**Comment by joelgriffith** [comment]
Whoah, that's great! I've actually had a lot of trouble trying to get proxies to work across the board, so something like this would be fantastic to recommend.

Let me try it out with a few providers!

**Comment by joelgriffith** [comment]
I have this staged on our docsite, so closing as it’ll be live soon

**Comment by gajus** [comment]
Thank you.

**Comment by John-Theo** [comment]
Hey, any update on this issue? @joelgriffith
I had no luck looking up the document for a per-request proxy. I'm using browserless latest docker image, is this functionality already implemented?
