### ISSUE TITLE
Header/Footer pageNumber and totalPages not working

### ISSUE THREAD

**Issue by zgohr** [browserless/chrome#569]
In the latest version, at least when generating a PDF, the `pageNumber` and `totalPages` are not properly being replaced in header/footer templates.

I was able to pinpoint it being somewhere between version 1.18.1 (working) and 1.19.1 (broken.)

I'm using Docker on Google Cloud Run.

**Comment by joelgriffith** [comment]
Out of curiosity, have you tried with vanilla puppeteer to see if it works? My guess is that it's a regression inside of puppeteer.

**Comment by zgohr** [comment]
I have not yet dug any further, but I would agree with you it does seem like puppeteer itself would be the culprit.

**Comment by joelgriffith** [comment]
OK, going to close for now since it seems to be an issue inside of puppeteer and not this repo :/
