### ISSUE TITLE
Never kill the session

### ISSUE THREAD

**Issue by stevezau** [browserless/chrome#582]
Hi,

The site i am trying to log into has MFA as such I am trying to keep the login session alive for as long as possible. The site sets non persistant (session) cookies so even if i have the same chome working folder the cookies are lost.

I wanted to set CHROME_REFRESH_TIME to 0 but it appears it does not work. Any other suggestions?

Yes, it could run out of memory but i manuall restart the container in that case.

**Comment by joelgriffith** [comment]
Yup, right now we don't have support for "infinite" chrome refresh time. I'd try setting it to something like 24 hours (86400000)

**Comment by stevezau** [comment]
Thanks, 24hrs won't be enough, will try set to 1 week. thanks

**Comment by joelgriffith** [comment]
Yup, we’ll loom to add support for never terminating soon
