### ISSUE TITLE
Issue with youtube.com from Demo & Built

### ISSUE THREAD

**Issue by rainbowhat** [browserless/chrome#583]
https://chrome.browserless.io/

module.exports = async ({ page }) => {
  await page.goto('https://youtube.com');
};

Trying to get this to work with headless = true 
What's the potential issue here? I can't seem to get it to work properly for youtube in particular.

**Comment by joelgriffith** [comment]
Looks like an issue in Chromium at the pptr 2.1.x. Could you try tag `1-puppeteer-2.0.0`? Works for me locally.

**Comment by joelgriffith** [comment]
Closing as this is in a dependency of ours, and nothing I can fix atm
