### ISSUE TITLE
Headless = false, access the visual?

### ISSUE THREAD

**Issue by stevezau** [browserless/chrome#584]
Hi,

I understand you can start healess = false via query params. However, i was wondering how, if at all, we can see and interact with the screen?

We do local dev but sometimes our scripts break when running in our prod env. The other case is sometimes for maual tests we require to enter an MFA credential we must be manual. 

I was hoping to connect and see the screen some how?

**Comment by joelgriffith** [comment]
Yup, you can use the live debugger: https://docs.browserless.io/docs/watching-sessions.html
