### ISSUE TITLE
Can't login Google's service if running the service in the docker container

### ISSUE THREAD

**Issue by wangyung** [browserless/chrome#600]
I found that if the service is running in the docker container, I can't login in my Google account.
But if I run the service on the VM, everything is fine.
Any workaround for this issue??

**Comment by joelgriffith** [comment]
Could you try with `?ignoreDefaultArgs=true` in your puppeteer.connect cal and see if that helps?

**Comment by joelgriffith** [comment]
My best guess is that this is due to some browser-fingerprinting, and something we (browserless) can't directly solve necessarily.
