### ISSUE TITLE
Set --user-data-dir for PREBOOT_CHROME & KEEP_ALIVE sessions

### ISSUE THREAD

**Issue by stevezau** [browserless/chrome#602]
Hi,

I cannot see a way to set the --user-data-dir when using PREBOOT_CHROME and KEEP_ALIVE.

Logging this as a feature request so one can override the data-dir allowing to persist state & cookies etc.

**Comment by stevezau** [comment]
Looking here, it seems you can override?https://github.com/browserless/chrome/blob/master/src/config.ts#L85

**Comment by joelgriffith** [comment]
Yup, that'll set a _default_ --user-data-dir for every launch _unless_ the `connect` calls requests a different --user-data-dir, in which case a new browser is fired up and has a different directory set.

It's a bit like cache miss: if the connect request specifies a different set of launch args, then the default isn't used.

**Comment by stevezau** [comment]
Thanks, created this PR for others as not in docs.

**Comment by joelgriffith** [comment]
Added to docs now: https://docs.browserless.io/docs/docker.html#default-user-data-dir (lots of others as well)

**Comment by stevezau** [comment]
thanks!
