### ISSUE TITLE
Include 'Ubuntu' font (used as system-ui in Chrome)

### ISSUE THREAD

**Issue by lpellis** [browserless/chrome#603]
The `font-family: system-ui` font is supposed to default to 'Ubuntu' on linux systems [1], currently it is defaulting to Verdana which is a much wider font, and is breaking the layout of some sites I'm testing.

![image](https://user-images.githubusercontent.com/145486/75184192-ad9b7980-574c-11ea-9e09-151acda9c747.png)

I think it might be solved by simply including the correct font (Ubuntu) on the box.  Or maybe depending on the distribution it can be set some other way?

[1] https://fontsarena.com/blog/operating-systems-default-sans-serif-fonts/

**Comment by joelgriffith** [comment]
Fixed in https://github.com/browserless/chrome/pull/617, should be out on hosted service in a few days!
