### ISSUE TITLE
browserless/base ARM image

### ISSUE THREAD

**Issue by colorfulsing** [browserless/chrome#616]
How can I use browserless/chrome docker image on ARM? I was trying to install browserless/chrome docker image on an arm laptop but noticed it error out because it's architecture being amd64.

Is there a way to build browserless/base image as ARM arch64?

Thanks in advance!

**Comment by joelgriffith** [comment]
Haven’t tried it out! Care to paste the logs you’re seeing?

**Comment by joelgriffith** [comment]
Unfortunately not going to get to this in the forceable future...

**Comment by manuelmeister** [comment]
Is this still not feasible? I would love a linux-arm64 and darwin-arm64 image.
