### ISSUE TITLE
NEED URGENT HELP

### ISSUE THREAD

**Issue by priyes** [browserless/chrome#669]
Hi @joelgriffith, I need your your help and experience, I have to run 100+ puppeteer chromium instances concurrently which perform a task which takes about 30 min each. That means 100+ browsers running together for very long period. I can't explain the use case for now. Can u help me on suggesting, which aws EC2 instance I should use for docker based deployment? And how much a cpu and memory a browser can consume in general ?

**Comment by joelgriffith** [comment]
@priyes I'd be more than happy to offer suggestions, but please email us at help@browserless.io
