### ISSUE TITLE
Host behind reverse proxy with subpath

### ISSUE THREAD

**Issue by dewey** [browserless/chrome#726]
**Describe the bug**

In https://github.com/browserless/chrome/issues/591 a new option called `PROXY_HOST` was introduced to overwrite the server path in case Browserless is behind a reverse proxy and the path has to be rewritten. It looks like this doesn't support the `PROXY_HOST` to contain a path like: `example.com/browserless`. The requests in the frontend are still done to:

```
https://example.com/devtools/inspector.html?wss=example.com/debugger
```

**To Reproduce**
1) Set environment variables to the following:

```
        - name: PROXY_HOST
          value: "example.com/browserless"
        - name: PROXY_PORT
          value: "443"
        - name: PROXY_SSL
          value: "true"
```
2) Open example.com/browserless
3) Interface appears
4) Submit a request:

```
module.exports = async ({ page }) => {
  await page.goto('https://www.github.com');
};
```
5) Nginx 404 in the preview field on the right side

**Expected behavior**

5) Shows pre-rendered Github.com

**Comment by joelgriffith** [comment]
Closed in https://github.com/browserless/chrome/pull/1216
