### ISSUE TITLE
Screenshot clip not working - only prints viewport area

### ISSUE THREAD

**Issue by trompx** [browserless/chrome#731]
**Describe the bug**
When making a screenshot with clip options, only the area of the viewport is present on the screenshot (here only the 1400x1080 gets printed), the rest of the image is only filled with the body background color.

**To Reproduce**
1. Run browserless docker container
```
  docker run \
    -e "MAX_CONCURRENT_SESSIONS=15" \
    -e "MAX_QUEUE_LENGTH=0" \
    -e "PREBOOT_CHROME=true" \
    -e "DEFAULT_BLOCK_ADS=true" \
    -e "DEFAULT_IGNORE_HTTPS_ERRORS=true" \
    -e "CONNECTION_TIMEOUT=600000" \
    -p 3000:3000 \
    --rm -it browserless/chrome:1.33.1-chrome-stable
```
2. Execute curl post request:
```
URL=${URL:-'https://stackoverflow.com/questions/47976790/play-mp4-in-chromium-with-puppeteer-windows'}

function payload {
cat << __EoF__
{
  "url": "$URL",
  "viewport": {
    "width": 1400,
    "height": 1080
  },
  "options": {
    "fullPage": false,
    "type": "jpeg",
    "quality": 75,
    "clip": {
      "x": 0,
      "y": 0,
      "width": 1400,
      "height": 2800
    }
  }
}
__EoF__
}

curl -s -X POST \
  http://192.168.0.10:3000/screenshot \
  --output /tmp/screenshots/test.jpeg \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d "$(payload)"
```

**Expected behavior**
The whole clip area should be present on the screenshot.

**Screenshots**
![test](https://user-images.githubusercontent.com/6394620/81302766-12435080-907b-11ea-8f41-7f1757b62bc3.jpeg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 (inside VM - windows host)
 - Browser: no browser inside VM

**Additional context**
If I set fullScreen: true, the image outputted is broken, get error while loading the image.

I ended up using browserless because I couldn't make video tag (mp4) printed in screenshot with other docker images including only puppeteer. With the image browserless/chrome:1.33.1-chrome-stable the video tag displays but the clip problem I have now was not present with the local chromium of my other puppeteer images.

**Comment by trompx** [comment]
Tried with the image `chrome:1.33.0-puppeteer-1.20.0`
- clip : working
- video tag : not working (mp4 not showing in screenshot)

**Comment by trompx** [comment]
@joelgriffith Did you have the chance to look at this issue?

**Comment by joelgriffith** [comment]
Is this still present? Our screenshot API got an overhaul not too long ago...

**Comment by trompx** [comment]
Thanks for the notification. I'll try again in the following week and let you know if this has been solved.

**Comment by joelgriffith** [comment]
I'd try `latest` to verify, since it'll have the most up-to-date code changes and puppeteer version

**Comment by joelgriffith** [comment]
Going to close this for now since I haven't heard from elsewhere that things aren't functioning properly. If it happens again, or if something isn't working right, feel free to reopen or open a new issue.
