### ISSUE TITLE
Use "Concurrent Sessions" as concurrent tabs when single prebooted instance keeps alive

### ISSUE THREAD

**Issue by imShara** [browserless/chrome#793]
**Is your feature request related to a problem? Please describe.**
When you use single chrome instance, browserless will throw 429 error for concurrent requests

**Describe the solution you'd like**
It's will be nice to create concurrent **tabs** when single preboot'ed chrome instance keeps alive

**Comment by joelgriffith** [comment]
We're working towards a higher-level "strategy" for doing concurrent sessions. When done, and using an API over a library, the behavior will change from parallelizing over a browsers to pages. Its still in the early phases, so I'm going to close this issue out in favor of our parallelizing option.
