### ISSUE TITLE
Pages continiously crash whith several parallel sessions

### ISSUE THREAD

**Issue by terion-name** [browserless/chrome#797]
If I run several parallel sessions with puppeteer in browserless/chrome docker image, pages continiously crash. I've tried with 3—4 sessions, nothing special, just navigating and clicking links (first I've thought that making screenshots is the problem, but without them it is the same). Only fancy stuff is using request interceptors but this is irrelevant I suppose. And with single session everything works ok.
Another annoying thing that this errors are uncatchable on the puppeteer side, but this is likely a puppeteer problem.

launch config is as recommended in browserless docs:
```
      const launchConfig = [
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-breakpad",
        "--disable-component-extensions-with-background-pages",
        "--disable-dev-shm-usage",
        "--disable-extensions",
        "--disable-features=TranslateUI,BlinkGenPropertyTrees",
        "--disable-ipc-flooding-protection",
        "--disable-renderer-backgrounding",
        "--enable-features=NetworkService,NetworkServiceInProcess",
        "--force-color-profile=srgb",
        "--hide-scrollbars",
        "--metrics-recording-only",
        "--mute-audio",
        "--headless",
        "--no-sandbox"
      ]
      return puppeteer.connect({
        browserWSEndpoint: `ws://${process.env.CHROME_HOST || 'localhost'}:${process.env.CHROME_PORT || 3000}?${launchConfig.join('&')}`,
        // headless: false,
        ignoreHTTPSErrors: true,
        args: launchConfig
      });
```

So the final config is:
```
2020-06-06T13:49:30.885Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-breakpad",
    "--disable-component-extensions-with-background-pages",
    "--disable-dev-shm-usage",
    "--disable-extensions",
    "--disable-features=TranslateUI,BlinkGenPropertyTrees",
    "--disable-ipc-flooding-protection",
    "--disable-renderer-backgrounding",
    "--enable-features=NetworkService,NetworkServiceInProcess",
    "--force-color-profile=srgb",
    "--hide-scrollbars",
    "--metrics-recording-only",
    "--mute-audio",
    "--headless",
    "--no-sandbox",
    "--remote-debugging-port=45729",
    "--user-data-dir=/tmp/browserless-data-dir-Zd97BT",
    "--remote-debugging-pipe"
  ],
  "blockAds": false,
  "headless": true,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": true,
  "pauseOnConnect": false,
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false
}
```

example of `docker run` log
```
2020-06-06T13:49:31.200Z browserless:job TVV4WTXFK2CGY8W4A45324WSBFBU5HSB: Proxying request to /devtools/browser route: ws://localhost:45729/devtools/browser/eb63cbe3-ac45-4069-83ad-46a3dcaacaad.
Unhandled Rejection at: Promise {
  <rejected> Error: Page crashed!
      at Page._onTargetCrashed (/usr/src/app/node_modules/puppeteer/lib/Page.js:209:28)
```
Running in docker for mac, VM has 4 CPUs and 3gigs of ram and 1gig of swap with options: `"docker run -e "DEFAULT_IGNORE_HTTPS_ERRORS=true" -e "CONNECTION_TIMEOUT=-1" -e "MAX_QUEUE_LENGTH=100" -e "MAX_CONCURRENT_SESSIONS=10"  -p 3000:3000 browserless/chrome"`

I've googled for several days, most say to use `--disable-dev-shm-usage` but I use it already.

What to do?(

**Comment by SaajidJoosab** [comment]
Im running into a similar issue as well. I'm doing 6 concurrent requests and browserless starts timing out after 3-5 rounds of requests. Any ideas? Im running this on AWS c5.large instance

**Comment by shmilyoo** [comment]
launch config not work . I run same as your code, but the print args was not changed.
as the docs https://github.com/puppeteer/puppeteer/blob/v5.1.0/docs/api.md#puppeteerconnectoptions, puppeteer.connect does not accept args params

**Comment by joelgriffith** [comment]
Recent version fo puppeteer are more susceptible to page crashes, and we've got a blog post about it in the works. I'd recommend using a 2.x.x version of the image: `docker pull browserless/chrome:1-puppeteer-2.1.1`

**Comment by MarianAlexandruAlecu** [comment]
Same issue here. After running a container with 1 to 4 sessions for 2-3 hours just fine, it starts to throw
```Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed``` 

And I checked a hundred times - we are not closing the page and then doing more actions.

**Comment by joelgriffith** [comment]
Page crashes are almost always a resource constraint problem. Would someone care to share their `top` output on one of their machines when this happens?
