### ISSUE TITLE
Support Chrome Extensions

### ISSUE THREAD

**Issue by joeljeske** [browserless/chrome#799]
**Is your feature request related to a problem? Please describe.**

I want to be able to install chrome extensions in the running chrome browser. 

**Describe the solution you'd like**

I would like to be able pass the Chrome flags to enable specific on-disk extensions: 

```
   --disable-extensions-except=/path/to/extension
   --load-extension=/path/to/extension
```

**Describe alternatives you've considered**

I tried already passing those flags and it didn't appear to work. I am not sure if it is supported.

**Additional context**

As far as I know, we cannot install extensions via chrome post-launch, we must specify the extensions pre-launch via flags. Solutions to installing post-launch is great too.

**Comment by joelgriffith** [comment]
This should actually work out of the box if the extension is mounted as a volume, and the path is available to chrome. Once it’s on the containers file system, you should be good.

Our original screencast implementation actually used an extension to do so

**Comment by joeljeske** [comment]
Hmm that’s what I did. I composed my own image, copying the extension files over and then referencing it in the launch flags. 

What’s notable though, is that I was wanting to use an extension with devtools extensions. Do you think that would make a difference?

**Comment by joelgriffith** [comment]
Hrm, possibly. I'm not sure how extensions interoperate with chromium's devtools, it's not something I'm familiar with.

Alternative is to clone this repo, and try and run it with your extension (no docker) and see if that works. That'll give us some more context.

**Comment by lennardv2** [comment]
Bit old issue, but i have the same problem, loaded docker image with:
      - DEFAULT_IGNORE_DEFAULT_ARGS=["--disable-extensions"]
      - DEFAULT_LAUNCH_ARGS=["--disable-extensions-except=/extension", "--load-extension=/extension"]

But, unfortunately, the extension is not working. Neither with PREBOOT_CHROME on and off.

Should work as i check the puppeteer documentation.

So any clue why this is not working?

**Comment by dgtlmoon** [comment]
Without relevant log information in your comments on this issue it's sort of impossible to tell whats going on

In my case, I'm trying everything

```
            - BROWSERLESS_ARGS=["--disable-extensions-except=/extension/chrome", "--load-extension=/extension/chrome"]
            - DEFAULT_IGNORE_HTTPS_ERRORS=true
            - DEFAULT_IGNORE_DEFAULT_ARGS=["--disable-extensions"]
            - DEFAULT_LAUNCH_ARGS=["--disable-extensions-except=/extension/chrome", "--load-extension=/extension/chrome"]
```

```
playwright-chrome_1  | 2023-10-12T09:19:21.060Z browserless:job REFV3JBFH7P9RL4HOC0A5HMS3AQ0VSTV: Getting browser.
playwright-chrome_1  | 2023-10-12T09:19:21.060Z browserless:chrome-helper Launching Chrome with args: {
playwright-chrome_1  |   "args": [
playwright-chrome_1  |     "--no-sandbox",
playwright-chrome_1  |     "--enable-logging",
playwright-chrome_1  |     "--v1=1",
playwright-chrome_1  |     "--disable-dev-shm-usage",
playwright-chrome_1  |     "--no-first-run",
playwright-chrome_1  |     "--disable-web-security=true",
playwright-chrome_1  |     "--remote-debugging-port=38089",
playwright-chrome_1  |     "--user-data-dir=/tmp/browserless-data-dir-0fiGmU"
playwright-chrome_1  |   ],
playwright-chrome_1  |   "blockAds": true,
```

**Comment by leoplct** [comment]
Is it possible to use a Chrome Extension that use content script ?
