### ISSUE TITLE
How to attach to same session?

### ISSUE THREAD

**Issue by kesavkolla** [browserless/chrome#813]
I'm using serverless functions (FaaS) where different functions interact with smae browser instance. Eg: first function opens a page and navigate to certain steps then second function would come and read data and navigate to another page then next function comes in etc...

As I understand there are 5 (default) sessions running at the same time. I want to make sure my function connects to right session so that continuation can happen.

**Comment by joelgriffith** [comment]
I don’t think this can work with FaaS since the container is torn down every time? This is largely dependent on your hosting platform. There is some docs on reattaching here: https://docs.browserless.io/docs/chrome-flags.html#keeping-the-browser-alive
