### ISSUE TITLE
Support changing chrome options. 

### ISSUE THREAD

**Issue by BenCoughlan15** [browserless/chrome#817]
**Is your feature request related to a problem? Please describe.**
Hi there, 

I get the following error when I run protractor against this. 
`Exception: WebDriverError: <unknown>: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

**Describe the solution you'd like**
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document
The error is a common one, the local storage api is tied to this setting, I'd like to be able to set this. 

**Describe alternatives you've considered**
I've tried clearing the setting before calls, but no dice. 

**Additional context**
This all works with my local version of chrome, it's just in this image :/

**Comment by joelgriffith** [comment]
Hrm, I'm not familiar with this... how are you running the image? It might also be the site itself not able to access local-storage?
