### ISSUE TITLE
Kill pages after a specific interval

### ISSUE THREAD

**Issue by obh** [browserless/chrome#862]
Is there a way to specify a config which kills any pages active beyond a specific time? I was not able to find anything on the configuration page - https://docs.browserless.io/docs/docker.html

I understand that we can also do it by ourselves, for every page we can do a `setTimeout(forceKill(), waitInterval)`, but just curious if Browserless provides this out of the box? I'm posting it here since it might be useful for somebody else as well.

Thanks

**Comment by joelgriffith** [comment]
https://docs.browserless.io/docs/docker.html#connection-timeout allows setting a browser-level timeout (we'll close that browser + all sessions when reached)

**Comment by obh** [comment]
Thanks, should have read the manual (it was right there).
