### ISSUE TITLE
How do I know how much backlog is in the queue?

### ISSUE THREAD

**Issue by shmilyoo** [browserless/chrome#863]
My business needs to accept requests from users and generate pdf based on the html content sent by them.
According to the stress test results, when the number of chrome instances is twice the number of cpu cores, the generation is most efficient and the total time is least.
My application is deployed in k8s with Max_Concurrent_Sessions = 2, Max_Queue_Length = 20, running multiple pods.
I would like to know how to get the current queue length and capacity in each pod when users keep requesting.

browserless supports webhooks, I can set up a webhook by setting the QUEUE_ALERT_ URL to learn that a queue has occurred for a particular pod, and to learn from the source IP which pod has been queued. But still found a problem that the queue event notification only happens once, even after request stops and waits for  the chrome instance has processed all the requests, then send requests, causing the queue to occur backlog. No queue event hooks will be sent at this time.

So, could you provide a way to get the capacity of the queue(from Max_Queue_Length), and the length of the queue, either through an interface, or a metric, either way.

**Comment by joelgriffith** [comment]
You can do a GET call to /pressure on the server, which will return session information (running, rejected, queued) and more. Do you think that'd work?

**Comment by shmilyoo** [comment]
@joelgriffith maybe not.
No problem for a single pod instance, but my service is running inside k8s. Multiple pods running, accessed according to ingress traffic scheduling. I can't tell which pod is being returned by /pressure.
Could you add a field ip address in the response object? 
Or, it would be great if metric could support this.

**Comment by joelgriffith** [comment]
How about an auto-generated (or supplies) ID? IP addresses can get messy since the container doesn’t know what IP it’s “under”

**Comment by shmilyoo** [comment]
I deployed a sidecar in each pod to continuously get  /pressure interface for queue information and then report the results to the monitoring center to solve the problem.
