### ISSUE TITLE
Example on setting up WSS via nginx as proxy? 

### ISSUE THREAD

**Issue by taewookim** [browserless/chrome#871]
Trying to secure websocket connection to chrome running inside browserless container. Any tutorial on how this is done?

**Comment by joelgriffith** [comment]
Hey there, there's plenty of information on the web on how to setup wss on your nginx server: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04. Seeing as this isn't an issue in our repo, I'm going to close this.

We internally use letsencrypt on our load-balancers, and have WSS setup there.
