### ISSUE TITLE
setRequestInterception issue

### ISSUE THREAD

**Issue by luminous8** [browserless/chrome#872]
**Describe the bug**
When using
`await page.setRequestInterception(true);`
I got this issue:
`Error: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found`

**To Reproduce**
I'm on the latest version of "browserless/chrome:release-chrome-stable"

My code looks like this (my function get the html of the page and returns it)
`
(async () => {
        try {
          const page = await browser.newPage();
          await page.setViewport({ width: 1920, height: 1080 });
          await page.setExtraHTTPHeaders({
            "Accept-Language": "en,en-US;q=0,5",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8",
          });
          await page.setRequestInterception(true);
          page.on("request", (req) => {
            if (
              req.resourceType() == "stylesheet" ||
              req.resourceType() == "font" ||
              req.resourceType() == "image"
            ) {
              req.abort();
            } else {
              req.continue();
            }
          });

          const response = await page.goto(url, {
            waitUntil: "domcontentloaded",
            timeout: CONF_TIMEOUT,
          });
          if (CONF_DEBUG)
            page.on("console", (consoleObj) => console.log(consoleObj.text()));

          const html = await page.content();
          const headers = response.headers();
          return { url, html, headers };

          page.close();
        } catch (err) {
          throw new Error(`${url} getHTML : ${err.toString()}`);
        }
      })();
`

What I found online is that is that the Chrome version may be too old but it's seems weird (It works on https://chrome.browserless.io).

Any idea where to look at to fix this?

Thanks

**Comment by joelgriffith** [comment]
`browserless/chrome:release-chrome-stable` is (likely) incredibly old. Could you try `browserless/chrome:1-chrome-stable`?

**Comment by joelgriffith** [comment]
Going to close as that tag is older and no longer supported, feel free to try any recent tags supported here: https://hub.docker.com/repository/docker/browserless/chrome/tags?page=1

**Comment by luminous8** [comment]
Wow nice! I didn't know that there was other version, will check.
Thanks a lot
