### ISSUE TITLE
browserless:server undefined: Recording queued stat

### ISSUE THREAD

**Issue by shmilyoo** [browserless/chrome#874]
This error appeared after two days of running.
An error on the nodejs side when calling connect.
Eventually chrome queue overflow reported an error

![UhQHeI.png](https://s1.ax1x.com/2020/07/20/UhQHeI.png)

**Comment by Zhang** [comment]
Hm - I've run into this as well

**Comment by shmilyoo** [comment]
I've add an sidecar to chrome pod, and constantly connect the chrome instance to perform health check, and restart the chrome container if it doesn't connect.
That's the only way I can find to go.

**Comment by joelgriffith** [comment]
That error event should now be fixed. What tag are you using?

**Comment by shmilyoo** [comment]
@joelgriffith 1.33-puppeteer-1.19.0

**Comment by joelgriffith** [comment]
yeah, you'll want the most recent version `docker pull browserless/chrome:1.36-puppeteer-1.20.0`

**Comment by shmilyoo** [comment]
Yes, I saw in another issue that you recommend others to use docker image with puppeteer version 2.11.
I'll try to upgrade soon, thanks!
