### ISSUE TITLE
Accessing files mounted via docker volume

### ISSUE THREAD

**Issue by petermikitsh** [browserless/chrome#897]
**Describe the bug**

Accessing files via the `file://` protocol results in an error.

<img width="1392" alt="Screen Shot 2020-07-30 at 11 19 35 PM" src="https://user-images.githubusercontent.com/1571918/89006271-3057d000-d2bb-11ea-96dc-75198ae9073b.png">

```
$ cat $PWD/packages/storybook/dist/index.html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><title>Storybook</title>...
```

```
docker run -p 9222:3000 --rm --name chrome \
  -v $PWD/packages/storybook/dist:/opt/storybook-static \
  browserless/chrome
```

**To Reproduce**

1. Mount a volume with an `index.html` file via docker's `-v` (see command above) 
2. Access debugger and attempt navigating to file's path.

**Expected behavior**

The page would load, similar to how `http://www.example.com` functions properly:

<img width="1392" alt="Screen Shot 2020-07-30 at 11 21 41 PM" src="https://user-images.githubusercontent.com/1571918/89006366-7319a800-d2bb-11ea-8331-cba7682bc68d.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**

An unrelated project suggests mounting a volume should work:

https://github.com/spring-media/storybook-addon-image-snapshots#testing-with-a-local-static-storybook-build

**Comment by joelgriffith** [comment]
Sorry, this is more or less expected behavior, because exposing the local file system (the file:// protocol) is a recipe for security issues. I think we can add a flag to allow file protocols, but be warned to not run it as an exposed service!

**Comment by petermikitsh** [comment]
Thanks Joel. One follow-up I had, in case others comes across this:

You can still mount a volume, and use puppeteer to visit pages on the `file://` protocol. In other words, this issue seems limited to only impacting the debugger UI.

```
docker run -d --rm \
  -p 9222:3000 \
  -e "CONNECTION_TIMEOUT=600000" \
  -v $SUBPACKAGE_DIR/dist:/opt/storybook-static \
  browserless/chrome
```

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.connect({browserURL: 'http://localhost:9222',});
  const page = await browser.newPage();
  await page.goto('file:///opt/storybook-static/iframe.html?id=table--basic');
  await page.screenshot({ path: 'example4.png' });
  await browser.close();
})();
```

**Comment by joelgriffith** [comment]
Nice, I think making this closed off by default, and only opting in, is the way we’ll do it going forward.

**Comment by brandonros** [comment]
Access files shared by a container is a disaster due to permissions if you just want to pull the off the shelf Dockerfile and not roll your own with custom `chmod` / `chown` commands. Any way you can make that better? I bailed out and just did `user: root`

**Comment by joelgriffith** [comment]
For the time being, `file` protocols can now be allow via a `ALLOW_FILE_PROTOCOL=true` docker env. Closing!

**Comment by petermikitsh** [comment]
For use cases where accessing files via `file://` protocol won't cut it, you can start two docker containers, one serving your static website, the other being browserless.


```

```
<img width="590" alt="Screen Shot 2021-06-06 at 6 43 13 PM" src="https://user-images.githubusercontent.com/1571918/120948532-44e4d000-c6f7-11eb-9306-d562253fa4b6.png">

**Comment by marcellusfarias** [comment]
Has someone tried the `ALLOW_FILE_PROTOCOL=true` flag and was able to make it work? Need some help with it.
