### ISSUE TITLE
Uncaught TypeError: URL constructor: chrome://newtab is not a valid URL

### ISSUE THREAD

**Issue by larytet** [browserless/chrome#898]
**Describe the bug**
I run the container, connect to 127.0.0.1:3000, click "Execute script"
I get in the Firefox log 

```
Uncaught TypeError: URL constructor: chrome://newtab is not a valid URL.
    kAllowedOrigins http://127.0.0.1:3000/devtools/extensions/extensions.js:76
    <anonymous> http://127.0.0.1:3000/devtools/extensions/extensions.js:76
extensions.js:76:269
    kAllowedOrigins http://127.0.0.1:3000/devtools/extensions/extensions.js:76
    map self-hosted:240
    <anonymous> http://127.0.0.1:3000/devtools/extensions/extensions.js:76
    InnerModuleEvaluation self-hosted:1572
    InnerModuleEvaluation self-hosted:1572
    InnerModuleEvaluation self-hosted:1572
    evaluation self-hosted:1543 
```
**To Reproduce**

```
docker build --tag browserless .
docker run -e "DEBUG=*"  -e "ENABLE_DEBUGGER=true" -e "DEMO_MODE=false"  -e "PREBOOT_CHROME=true" -p 3000:3000 --restart always  browserless
```

**Expected behavior**

I expect to see an online debugger  and the WEB page example.com

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 78.0.2

**Comment by larytet** [comment]
The debugger works in Chrome 84.0..

**Comment by larytet** [comment]
Nothing works now `Daily limit reached, sign-up for an account at https://browserless.io`

**Comment by joelgriffith** [comment]
@larytet your message indicates that you’re issuing sessions against our demo instance. The URI for your container is like something like `ws://local host:3000` and not `wss://chrome.browserless.io`. Could you verify the right address?

**Comment by larytet** [comment]
I just opened a browser using 127.0.0.1, run the default example sample a few times.
