### ISSUE TITLE
[question only]why could chrome creat tcp link with random port to outer and successfully?

### ISSUE THREAD

**Issue by bi-kai** [browserless/chrome#901]
Start container with:
`docker run -dit -p 4000:3000 --restart always --name chrome-headless browserless/chrome:latest`

In my main, chrome only cloud use inner 3000 port to commnuicate with outside, but chrome created tcp link with random port(such as: 51690) to public web server and it's correct!

How cloud this happened? It's amazing!!!
------------------------------------------

when I start without port param:
`docker run -dit --restart always --name chrome-headless  -e "MAX_CONCURRENT_SESSIONS=100" browserless/chrome:latest`
then:
`docker exec -it chrome-headless bash`
and:
`google-chrome --no-sandbox --headless --disable-gpu --dump-dom http://10.248.195.231:8000`
I got the correct dom context, I know this is nothing about `-p xxx:3000`. I just wonder how this happened.

**Comment by joelgriffith** [comment]
Chrome binds to the machines network to listen for incoming commands, which browserless will proxy requests into. At no point should it be available on the LAN or WAN, unless you’ve setup docker to mirror all ports on the machine to the containers port

**Comment by bi-kai** [comment]
I see.
