### ISSUE TITLE
Browserless using ~37MB of ephemeral storage per /screenshot

### ISSUE THREAD

**Issue by f0ff886f** [browserless/chrome#985]
I've found that calling /screenshot for a relatively simple page with 900kB of js libs causes the ephemeral storage used by the pod running the docker container to jump 37MB _per request.

That seems pretty extreme, and worse yet, there's no way to either restrict or cleanup after browserless. Is there some env var that I missed or any way to figure out where the storage is going?

I'm using the `browserless/chrome:1.38-chrome-stable` container.

**Comment by f0ff886f** [comment]
Ah, the usage is in `/usr/src/app` and there's a nice core dump each time... :D 

```
-rw-------   1 blessuser blessuser 183M Sep 16 14:56 core.1084
-rw-------   1 blessuser blessuser 183M Sep 16 14:55 core.163
-rw-------   1 blessuser blessuser 191M Sep 16 14:55 core.271
-rw-------   1 blessuser blessuser 183M Sep 16 14:56 core.340
-rw-------   1 blessuser blessuser 199M Sep 16 14:56 core.445
-rw-------   1 blessuser blessuser 183M Sep 16 14:50 core.53
-rw-------   1 blessuser blessuser 191M Sep 16 14:56 core.553
-rw-------   1 blessuser blessuser 191M Sep 16 14:56 core.659
-rw-------   1 blessuser blessuser 191M Sep 16 14:56 core.765
-rw-------   1 blessuser blessuser 191M Sep 16 14:56 core.870
-rw-------   1 blessuser blessuser 181M Sep 16 14:56 core.977
```

**Comment by s-buchner** [comment]
Will this be fixed?

**Comment by f0ff886f** [comment]
You can workaround this by prepending `ulimit -c 0` to the execution of browserless to prevent core dumps.

**Comment by joelgriffith** [comment]
To just make sure I'm clear: is it core dups that are an issue?
