### ISSUE TITLE
Is there way to spoof dns record?

### ISSUE THREAD

**Issue by imShara** [browserless/chrome#998]
**Is your feature request related to a problem? Please describe.**
I want to access website with specific ip

**Describe the solution you'd like**
I want to make something like this:
```js
await page.goto('https://example.com', { ip: '1.2.3.4' })
```
but it not possible with browserless architecture

**Describe alternatives you've considered**
Chrome supports command line parameter `--host-rules`, it can be used like this:
```sh
chromium --host-rules='MAP example.com 1.2.3.4' https://example.com
```
and can be used with puppeteer like this:
```js
const browser = await puppeteer.launch({
  args: ['--host-rules=MAP example.com 1.2.3.4']
})
```
**BUT** it's broken for https requests, you will get `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` or `NET::ERR_CERT_AUTHORITY_INVALID` error.

Also, you can use `HOSTALIASES` variable to point file with host rules. But it works only for local hostnames, e.g `example` (not FQDN like `example.com`)

And in the end, you can write rule to `/etc/hosts` and this will work. I think this will be best solution to run browser with container with spoofed `/etc/hosts` by parameter.

**Comment by imShara** [comment]
Other way is to use `--add-host` parameter for docker container `--add-host example.com:1.2.3.4`

**Comment by joelgriffith** [comment]
We do support arbitrary CLI flags, documented here: https://docs.browserless.io/docs/chrome-flags.html#docsNav. Is there something in particular that we’d need to do to support this?

**Comment by imShara** [comment]
@joelgriffith I have not found any _working_ way to specify ip address for hostname in Chrome except `/etc/hosts` editing. My solution is to use [buildkite/puppeteer](https://github.com/buildkite/docker-puppeteer) container with --add-host parameter.

`docker run --add-host example.com:1.2.3.4 buildkite/puppeteer node …`

I think I need to create issue in puppeteer repo.

**Comment by joelgriffith** [comment]
Yup, going to close as this isn’t something we can do in our side of things
